### ISSUE TITLE
Log entry for MongodConfigBuilder$ImmutableMongodConfig

### ISSUE THREAD

**Issue by sdavids** [flapdoodle-oss/de.flapdoodle.embed.mongo#101]
Hi,

I have the following log entries:

Sep 29, 2014 4:56:48 PM MongodExecutable start
INFO: de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@4671e53b

and I cannot turn them off.

I tried

```
 <logger name="de.flapdoodle.embed" level="WARN"/>
 <logger name="de.flapdoodle.embed.mongo" level="WARN"/>
 <logger name="de.flapdoodle.embed.mongo.config" level="WARN"/>
 <logger name="de.flapdoodle.embed.mongo.config.MongodConfigBuilder" level="WARN"/>
```

all in vain.

**Comment by Loki-Afro** [comment]
@sdavids works. I guess you are in the logging - madness.

`de.flapdoodle.embed.mongo` as well as `de.flapdoodle.embed.process` use SLF4J.
