### ISSUE TITLE
MongoImportProcess shuts down Mongod on stop()

### ISSUE THREAD

**Issue by gtrog** [flapdoodle-oss/de.flapdoodle.embed.mongo#110]
I'm not sure if this is working as intended, but in trying to use this library programatically, I ran into an issue.  For our mongo tests, I would have an abstract base class with a static instance variables for the MongodStarter and MongoImportStarter and then @BeforeClass  and @AfterClass methods to set up and tear down MongodProcess.

In addition to this, the base class has utility methods that allow you to import mongo data and would do this by creating a MongoImportProcess.  I assumed that once waitFor() on the import process returns, the correct thing to do would be to clean up and call close on the MongoImportProcess instance, but doing so causes the MongodProcess to get shutdown.  

Digging into the code, I discovered that the AbstractMongoProcess class always shuts down Mongod when stopInternal() is called, even if the class extending AbstractMongoProcess has nothing to do specifically with MongodProcess.  In addition, strangely, this didn't seem to happen when running on Mac OSX, but did happen somewhat randomly when running on CentOS 5.5.  I've temporarily created a work-around where I've implemented my own 'FixedMongoImportProcess' which doesn't extend AbstractMongoProcess but instead extends AbstractProcess, so that I can bypass this shutdown logic and that seemed to do the trick.

Let me know if I was just using MongoImportProcess incorrectly or if this is in fact a bug.

**Comment by BrainCookie** [comment]
+1
> "In addition, strangely, this didn't seem to happen when running on Mac OSX ..."

I get the same behaviour running on OSX and I think it's a bug rather than an incorrect use of the `MongoImportProcess`.

**Comment by Loki-Afro** [comment]
Still not released...

**Comment by Loki-Afro** [comment]
`MongoImport` should inherit from `AbstractMongoProcess`. 

`AbstractMongoProcess` does more than just having its special shutdown magic, which indeed is kinda weird when it (sometimes) stop `mongod` itself.

However like `MongoDumpProcess` and `MongoRestoreProcess` it should just override `stopInternal` and do nothing in it. 
`AbstractMongoProcess` has this fancy `onAfterProcessStart` method where it waits till the process finished. This logic is now missing. And as a result there are imports which are runnign fine - but in the background and if you are lucky then you try to fid documents which are not imported yet. 

Currently the tests in `MongoImportExecutableTest` do not check if the files are imported if they would do I am pretty sure this race condition kikes in.
