### ISSUE TITLE
Is mongorestore possible?

### ISSUE THREAD

**Issue by mudlee** [flapdoodle-oss/de.flapdoodle.embed.mongo#111]
If I have a directory produced by mongodump, is it possible to restore with embed mongo? In common I do this with mongo binary: mongorestore -d DATABASE DUMP_DIRECTORY

**Comment by mudlee** [comment]
Anybody?

**Comment by michaelmosmann** [comment]
Hmm.. we could add this as a feature. I am not sure, if there is already an issue for this.

**Comment by mudlee** [comment]
I've not found any other related issue. Anyway, I did it in another way: instead restoring a dump, I use a db directory with the replication setup. Almost good as restoring :)

**Comment by Loki-Afro** [comment]
Isn't this done? o.O

**Comment by Loki-Afro** [comment]
It is already implemented, please check it out ;)
