### ISSUE TITLE
Enable authentication configuration

### ISSUE THREAD

**Issue by luan-cestari** [flapdoodle-oss/de.flapdoodle.embed.mongo#114]
Hi,

I notice that in the current implementation, the MongoDB is hardcoded to start without the authentication mechanism ( https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/runtime/Mongod.java#L128   http://docs.mongodb.org/v2.2/reference/configuration-options/   ) . I Have some complex use cases that I need to test using this project in the integration I would like this feature (so I could create new users and check if I get any authentication problem http://docs.mongodb.org/manual/tutorial/add-user-administrator/ ). May I fork and create a PR for this (I'm not familair with the workflow you guys have here)?

Thank you in advance
Luan

**Comment by matlockx** [comment]
Yeah, doing a fork and bringing up a pr is absolutely fine and totally appreciated :)

**Comment by luan-cestari** [comment]
Done https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/115

**Comment by matlockx** [comment]
i think it's done with #117

**Comment by mohamnag** [comment]
cant find any examples on how to enable authentication, would somebody please update docs accordingly? or at least point me to right direction?

**Comment by GaneshDoosa** [comment]
How to use this authentication mechanism ?

**Comment by ropi95** [comment]
can anyone tell me how to use with this authentication?
