### ISSUE TITLE
Mongo 3.x support

### ISSUE THREAD

**Issue by sfitts** [flapdoodle-oss/de.flapdoodle.embed.mongo#119]
It would be good to be updated to the 3.x release now that it is production.  I see that this is part of the changes in #117.  Are there plans to merge that?  If there are issues with the other changes made in the that PR perhaps the version update could be moved to a dedicated pull.  Any visibility into the plans here would be great.

**Comment by matlockx** [comment]
just merged it. when @michaelmosmann agrees on it i will do a release in the next days.

**Comment by sfitts** [comment]
Cool, thanks.

**Comment by matlockx** [comment]
1.47.1 should be available now
