### ISSUE TITLE
NoSuchFieldException on JDK 9

### ISSUE THREAD

**Issue by gunnarmorling** [flapdoodle-oss/de.flapdoodle.embed.mongo#120]
When using the plug-in on JDK 9, I'm getting the following exception:

```
java.lang.NoSuchFieldException: handle
	at java.lang.Class.getDeclaredField(Class.java:2100)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:94)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:55)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:65)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:206)
	at de.flapdoodle.embed.process.runtime.ProcessControl.fromCommandLine(ProcessControl.java:202)
	at de.flapdoodle.embed.process.runtime.NUMA.isNUMAOnce(NUMA.java:56)
	at de.flapdoodle.embed.process.runtime.NUMA.isNUMA(NUMA.java:44)
	at de.flapdoodle.embed.mongo.runtime.Mongod.enhanceCommandLinePlattformSpecific(Mongod.java:175)
	at de.flapdoodle.embed.mongo.MongodProcess.getCommandLine(MongodProcess.java:85)
	at de.flapdoodle.embed.mongo.MongodProcess.getCommandLine(MongodProcess.java:41)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:84)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:52)
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:99)
	at com.github.joelittlejohn.embedmongo.StartEmbeddedMongoMojo.execute(StartEmbeddedMongoMojo.java:271)
```

Not sure what's the best way to address this issue, but it'd be nice to be able to use the plug-in on JDK 9, too :)

**Comment by michaelmosmann** [comment]
Hmm.. funny. It looks like a change some windows related code.. Processes.windowsProcessId() is a hack to get the processId. So we need some jdk9 related changes... will be fun:)

**Comment by gunnarmorling** [comment]
Ah, I should mention that this is not on Windows, but on Fedora. IIUC, the code first tries the Unix-like approach, cannot obtain the pid there (probably due to some similar internal change), falls back to W32 and then finally fails with the exception above.

**Comment by gunnarmorling** [comment]
Btw. the second answer to [this SO question](http://stackoverflow.com/questions/35842/how-can-a-java-program-get-its-own-process-id) looks quite promising IMO. Instead of relying on JDK-internal classes, it uses JNA to obtain the information via suitable native APIs. Might be worth giving a try.

**Comment by michaelmosmann** [comment]
@proccessId: We need the processId of the mongo process, not out own.. 
@Fedora: Hmm.. funny.. so the code thinks, he runs on windows.. 
Can you give me some more information? env-vars? Because i guess the operating system..

**Comment by michaelmosmann** [comment]
as you can see here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/master/src/main/java/de/flapdoodle/embed/process/distribution/Platform.java

**Comment by gunnarmorling** [comment]
Seems like things will be much easier with JDK 9.

There is [JEP 102](http://openjdk.java.net/jeps/102) ("JEP 102: Process API Updates") which amongst others brings a new method `Process#getPid()`. So depending on the JDK in use, you could use either that new method or fall back to the current routine on earlier versions. The new method already exists and works as expected in the latest [EA build](https://jdk9.java.net/download/).

If you push that code behind an interface and load the right implementation version based on the current runtime, you could make use of that new method in a backwards-compatible manner, it'd only require to use JDK 9 for building the _de.flapdoodle.embed.process_ component using JDK 9.

**Comment by gunnarmorling** [comment]
> @Fedora: Hmm.. funny.. so the code thinks, he runs on windows.. 

I can't debug it on Fedora atm. but it is the same on Mac OS X with JDK 9. The process class is of type `java.lang.ProcessImpl`. Therefore `unixLikeProcessId()` returns null and the code then fails to determine the PID in `windowsProcessId()`. Subsequently, an NPE is raised in `AbstractProcess` when unboxing `process.getPid()` which returns null.

> you could make use of that new method in a backwards-compatible manner,

Thinking about it, if you invoke that method via reflection for the time being, even JDK < 9 could be used for compilation. If you think it's a good idea, I can send you a pull request with that change.

**Comment by michaelmosmann** [comment]
I am happy with any pull request:)

**Comment by gunnarmorling** [comment]
I'm going to close this one, as the PR is merged and a new version of process and mongo has been released. Thanks a lot for the quick release!

**Comment by mickaeltr** [comment]
Hello,

FYI, it seems that the problem reappeared with Java 10.
I am using MacOS and getting the following output:

> java.lang.NoSuchFieldException: handle
> 	at java.base/java.lang.Class.getDeclaredField(Class.java:2370)
> 	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:109)
> 	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:51)
> 	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$2.getPid(Processes.java:209)
> 	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:72)
> 	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:64)
> 	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
> 	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99)
> 	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
> 	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)

Cheers

**Comment by Loki-Afro** [comment]
@mickaeltr could you open a new issue? thanks

**Comment by francisdb** [comment]
can we please get a release including this fix?
