### ISSUE TITLE
Support for version 3.0 driver and API

### ISSUE THREAD

**Issue by dazraf** [flapdoodle-oss/de.flapdoodle.embed.mongo#122]
Hi,

Could you provide an implementation that works with Mongo Java driver 3.0.0 using the new API
(http://mongodb.github.io/mongo-java-driver/3.0/driver/getting-started/quick-tour/)?

thanks
Fuzz.

**Comment by michaelmosmann** [comment]
Hmm.. we should change the mongo client dependency to scope test. So you can choose what you want..

**Comment by dazraf** [comment]
Sounds good!

**Comment by michaelmosmann** [comment]
released .. 
in maven central tomorrow (or faster :) ...

**Comment by dazraf** [comment]
Thank you!

**Comment by dazraf** [comment]
Hi,
Thank you for the update. 
Is it possible to point the runtime config to use a locally available version of mongod please?
Thanks.

**Comment by matlockx** [comment]
#123 takes care of your question, so I close this
