### ISSUE TITLE
OSX Yosemite firewall prompt when even when using custom executable naming

### ISSUE THREAD

**Issue by scorpiodawg** [flapdoodle-oss/de.flapdoodle.embed.mongo#125]
Hello

I'm using a custom IRuntimeConfig to start an embedded mongo instance as indicated in the tutorial (using executableNaming() for instance), on OSX Yosemite. My test runs through to completion, but every time a Mongo instance is started I get the OSX prompt about the firewall ("Do you want the application “extract-username-mongod” to accept incoming network connections?"). I'm not able to add this name in the Security & Privacy settings because that dialog wants a path to the executable and this path changes each time.

How do I fix this?

Thanks

My code:
```java
    @Override protected void before() throws Throwable {
        Command command = Command.MongoD;
        // Need this to set the executable name constant so that OSX does not prompt multiple times
        IRuntimeConfig runtimeConfig = new RuntimeConfigBuilder().defaults(command).artifactStore(
                new ArtifactStoreBuilder().defaults(command)
                                          .download(new DownloadConfigBuilder().defaultsForCommand(command))
                                          .executableNaming(new UserTempNaming())).build();

        MongodStarter starter = MongodStarter.getInstance(runtimeConfig);

        IMongodConfig mongodConfig = new MongodConfigBuilder().version(Version.Main.PRODUCTION)
                                                              .net(new Net(MONGO_TEST_PORT, Network.localhostIsIPv6()))
                                                              .build();

        mongodExecutable = starter.prepare(mongodConfig);
        mongod = mongodExecutable.start();
    }
```
Dialog:

![image](https://cloud.githubusercontent.com/assets/2002884/7485825/3a94e7ce-f350-11e4-97d3-0e6044cee584.png)

**Comment by scorpiodawg** [comment]
Sorry I meant Yosemite, not Mavericks

**Comment by scorpiodawg** [comment]
Ack, sorry closed accidentally.

**Comment by michaelmosmann** [comment]
Can you try this: 
  https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#usage---custom-mongod-filename

**Comment by scorpiodawg** [comment]
That is precisely what I used, but kept seeing the popup. I just noticed that this went away overnight (weird?) -- it may be some sort of caching effect introduced by OS. Am closing this for now.

**Comment by michaelmosmann** [comment]
Hmm.. weird..
