### ISSUE TITLE
UnknownHostException while downoading:downloads.mongodb.org

### ISSUE THREAD

**Issue by lokeshtank** [flapdoodle-oss/de.flapdoodle.embed.mongo#126]
While try to setup embed.mongo junit test cases environment, I am getting following error . I am using: spring-data-mongodb: 1.6.1.RELEASE de.flapdoodle.embed.mongo 1.47.3 org.springframework: 4.0.3.RELEASE

de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOException: Could not open inputStream for http://downloads.mongodb.org/win32/mongodb-win32-i386-3.0.2.zip Caused by: java.net.UnknownHostException: downloads.mongodb.org at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)

and also its pointing to mongodb-win32-i386-3.0.2.zip but I am using windows 64 bit.

**Comment by michaelmosmann** [comment]
Hmm.. This Url works for me.. Is there any firewall or proxy?

**Comment by lokeshtank** [comment]
Hi michaelmosmann  Thanks a lot for quick reply. Yes I have firewall and proxy, But I have configured proxy setting in my eclipse. But still same error :(.

**Comment by michaelmosmann** [comment]
There a 2 problems:
1) Your code can not resolve "downloads.mongodb.org".
2) Our code thinks, that you are using a win32 platform.

for 1: can you try this with wget or curl?
for 2: can you give us the result of System.getProperty("os.name");

**Comment by lokeshtank** [comment]
here is my code
package com.bosch.test;

import junit.framework.TestCase;

import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.support.AnnotationConfigContextLoader;

import com.bosch.in.model.Device;
import com.bosch.in.service.imp.DeviceServiceImp;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
import com.mongodb.MongoClient;

import de.flapdoodle.embed.mongo.MongodExecutable;
import de.flapdoodle.embed.mongo.MongodProcess;
import de.flapdoodle.embed.mongo.MongodStarter;
import de.flapdoodle.embed.mongo.config.MongodConfigBuilder;
import de.flapdoodle.embed.mongo.config.Net;
import de.flapdoodle.embed.mongo.distribution.Version;
import de.flapdoodle.embed.process.runtime.Network;

@ContextConfiguration(classes = ApplicationConfig.class, loader = AnnotationConfigContextLoader.class)
@RunWith(SpringJUnit4ClassRunner.class)
public class DeviceServiceTest2 {

	private static final MongodStarter starter = MongodStarter
			.getDefaultInstance();

	private static MongodExecutable mongodExe;
	private static MongodProcess mongod;
	private static MongoClient mongo;
	private DeviceServiceImp deviceServiceImp;
	private MongoTemplate template;

	@BeforeClass
	public static void setUp() throws Exception {
		// System.out.println("1");
		mongodExe = starter.prepare(new MongodConfigBuilder()
		.version(Version.Main.V2_2)
				.net(new Net(12345, Network.localhostIsIPv6())).build());
		System.out.println("2");
		mongod = mongodExe.start();
		System.out.println("3");

		System.out.println("4");
		mongo = new MongoClient("12345", 12345);
		System.out.println("5");
	}

	@AfterClass
	public static void tearDown() throws Exception {
		mongod.stop();
		mongodExe.stop();
	}

	public Mongo getMongo() {
		return mongo;
	}

	@Test
	public void save() {
		System.out.println("1");

	}

}

**Comment by michaelmosmann** [comment]
Try this: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-proxy-for-download

**Comment by lokeshtank** [comment]
Thanks a lot I will try and let you.

**Comment by matlockx** [comment]
can we close this?

**Comment by hackeys** [comment]
I am also seeing same error . 
I could get it downloaded when used with wget . My maven in configured to run with proxy even then i see this error.

**Comment by herrphon** [comment]
I was getting the same error.. so I tried out SSLPoke:

```
>java SSLPoke downloads.mongodb.org 443
Picked up JAVA_TOOL_OPTIONS: -Djsse.enableSNIExtension=false
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at java.base/sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at java.base/sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)
        at java.base/sun.security.ssl.AppOutputStream.write(Unknown Source)
        at java.base/sun.security.ssl.AppOutputStream.write(Unknown Source)
        at SSLPoke.main(SSLPoke.java:31)
```

Then I noticed the line with `Picked up JAVA_TOOL_OPTIONS...`. After getting rid of this option in the environment variables, it worked :-)
