### ISSUE TITLE
Not able to Run multiple tests in one class in Mac OS machin

### ISSUE THREAD

**Issue by ashishk-jain** [flapdoodle-oss/de.flapdoodle.embed.mongo#132]
This is similar to issue #37 but still phase issue with latest builds.

I am getting similar issue but there are no exceptions.
Even thought I have used mongexe.stop in teardown method.
Individual test passes but when I run all tests together 2nd test onwards fails.
Even If I have debugger in 2nd test, then those tests passes too.

Junit 4, 
embed mongo version : 1.47.3/1.35/1.36
I have this code in teardown
@After
public void teardown() throws Exception {
_mongodExe.stop();
_mongod.stop();
}

To be very specific first db query fails and all other db query passes in the failed tests.

I am using mac OS_X OS.

**Comment by nunomrc** [comment]
I am seeing the same issue here.
I do have an exception, though:
```
java.nio.file.FileAlreadyExistsException: /var/folders/hp/53b4d2bx71sfy26dvqxfp6zh0000gn/T/extract-pc-name
```

But when I check the file on the command line, it doesn't exist.

Any help?

**Comment by Loki-Afro** [comment]
I guess this is not relevant anymore. Everything works on my OS X machine at least. reopen if i'm wrong :)
