### ISSUE TITLE
Misspelling in README.md

### ISSUE THREAD

**Issue by freemo** [flapdoodle-oss/de.flapdoodle.embed.mongo#133]
It is spelled Organization not Organisation. It is misspelled in several places in the README.

**Comment by matlockx** [comment]
As far as I know organisation is British English isn't it?  But I'm not a native speaker at all, so I'll have a look.

**Comment by freemo** [comment]
Maybe, not sure. All I know is I looked up both varients on google, organisation had about 194,000 hits and Organization had like 1 billion or something. Also I had never seent he Organisation varient. But you may be right.

**Comment by matlockx** [comment]
done with https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/commit/9b3f6c9150566b56c563e2261f0efaeba65debf7
