### ISSUE TITLE
mongo v2.6.9 & v2.6.10 are not available

### ISSUE THREAD

**Issue by someshj1** [flapdoodle-oss/de.flapdoodle.embed.mongo#134]
I need to run a v2.6.10 mongo instance but the highest 2.6.x version which I can see is 2.6.8. I want to know if there are plans to enable mongo version 2.6.10??

**Comment by michaelmosmann** [comment]
Am 10.07.2015 um 12:32 schrieb someshj1:
> I need to run a v2.6.10 mongo instance but the highest 2.6.x version
> which I can see is 2.6.8. I want to know if there are plans to enable
> mongo version 2.6.10??

yes..

**Comment by someshj1** [comment]
Thanks for the update. By when I can expect it to be released?

**Comment by michaelmosmann** [comment]
Am 10.07.2015 um 13:40 schrieb someshj1:
> Thanks for the update. By when I can expect it to be released?

did the release in the last minutes.. but you may have to wait some
hours (up to 24) to see it in maven central..

michael:)

**Comment by someshj1** [comment]
That was pretty fast :+1: . Thanks a ton.

**Comment by someshj1** [comment]
Version 1.48.1 is still not available in maven repo.

**Comment by michaelmosmann** [comment]
hmm.. damn.. i know.. I did forget the sonatype nexus stuff.. .
I will do this again in the evening.

**Comment by michaelmosmann** [comment]
.. there should be 1.48.2 in maven central in some hours. (this time i did this sonatype nexus stuff :)

**Comment by someshj1** [comment]
I can see 1.48.2 in the repo. Thanks :+1:
