### ISSUE TITLE
On windows 7, windows server 2008 version getting installed

### ISSUE THREAD

**Issue by ananth1** [flapdoodle-oss/de.flapdoodle.embed.mongo#135]
Following method returns true in Paths.java for windows 7 which in turn installs windows server plus version on windows 7.
protected boolean useWindows2008PlusVersion() {
        // Windows Server 2008 R2  or Windows 7
        String osName = System.getProperty("os.name");
        if (osName.contains("Windows Server 2008 R2")) return true;
        return osName.contains("Windows 7");
    }

**Comment by michaelmosmann** [comment]
Hmm.. can you tell me which version we should use then?

**Comment by ananth1** [comment]
2008 plus version is marked as legacy version in mongo download page with .
 Other one is https://fastdl.mongodb.org/src/mongodb-src-r3.0.5.zip . I thought we are supposed to use this. Correct me if I am wrong.

**Comment by michaelmosmann** [comment]
Currently i can not extract files from an msi-archive .. thats why we are using the the legacy version, which come with an zip-archive .. not sure, what legacy means.

Your download url points to an source archive..

**Comment by ananth1** [comment]
makes sense.. Thanks for explanation.

**Comment by ananth1** [comment]
I changed the url to this https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-3.0.6.zip and there seems to be non legacy binary. But it is not documented in there. I changed the url by looking legacy pattern.

**Comment by michaelmosmann** [comment]
We can try this change..

**Comment by Loki-Afro** [comment]
This has changed again with 3.6.0, currently there is only one windows binary left.

> Windows Server 2008 R2 64-bit and later, with SSL support x64

https://www.mongodb.com/download-center#community
