### ISSUE TITLE
Mongo process randomly fail to start 

### ISSUE THREAD

**Issue by aveuiller** [flapdoodle-oss/de.flapdoodle.embed.mongo#138]
Hello, I use your library to run integration tests on a project based on the Play Framework.
To do so, I provide a Scope, starting a mongodb server on a free port, a new mongodb server is created between each test.

This worked well, but since I added a few tests (I went from 50 to 80) it happens that the mongo server does not start, throwing this exception:

```
[error] d.f.e.p.r.AbstractProcess - failed to call onAfterProcessStart()
java.io.IOException: Could not start process: failed errno:98 Address already in use for socket: 0.0.0.0:60721
2015-11-23T16:23:01.782+0100 E NETWORK  [initandlisten]   addr already in use
    at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79) [de.flapdoodle.embed.mongo-1.50.0.jar:na]
    at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:114) ~[de.flapdoodle.embed.process-1.50.0.jar:na]
    at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53) [de.flapdoodle.embed.mongo-1.50.0.jar:na]
    at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) [de.flapdoodle.embed.mongo-1.50.0.jar:na]
    at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44) [de.flapdoodle.embed.mongo-1.50.0.jar:na]
    at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34) [de.flapdoodle.embed.mongo-1.50.0.jar:na]
    at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101) [de.flapdoodle.embed.process-1.50.0.jar:na]
    at testHelpers.WithInitBackend.before(WithInitBackend.scala:43) [it-classes/:na]
    at testHelpers.WithInitBackend.around(WithInitBackend.scala:54) [it-classes/:na]
    at org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:15) [specs2-core_2.11-3.6.jar:3.6]
[warn] d.f.e.m.r.Mongod - sendShutdown linux-host/127.0.1.1:60721
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_66]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_66]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_66]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_66]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_66]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_66]
    at de.flapdoodle.embed.mongo.runtime.Mongod.sendShutdown(Mongod.java:86) ~[de.flapdoodle.embed.mongo-1.50.0.jar:na]
    at de.flapdoodle.embed.mongo.AbstractMongoProcess.sendStopToMongoInstance(AbstractMongoProcess.java:133) [de.flapdoodle.embed.mongo-1.50.0.jar:na]
    at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:107) [de.flapdoodle.embed.mongo-1.50.0.jar:na]
    at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170) [de.flapdoodle.embed.process-1.50.0.jar:na]
[warn] d.f.e.m.AbstractMongoProcess - could not stop mongod with db command, try next
[warn] d.f.e.m.AbstractMongoProcess - could not stop mongod, try next
[warn] d.f.e.m.AbstractMongoProcess - could not stop mongod the second time, try one last thing
```

Of course this port isn't used on my machine and this kind of error happens randomly, between 0 and 4 times on an execution of every tests.
I guess the problem is coming from the frequent server restarts, but I don't really understand why.

As complementary data, here is the configuration of my mongo server:

```
abstract class WithInitBackend extends Around with Scope {
  lazy val port = Network.getFreeServerPort

  lazy val mongoCmdOptions = new MongoCmdOptionsBuilder()
    .syncDelay(0)
    .useSmallFiles(true)
    .useNoJournal(true)
    .useNoPrealloc(false)
    .build()

  lazy val mongodConfig = new MongodConfigBuilder()
    .net(new Net(port, Network.localhostIsIPv6()))
    .cmdOptions(mongoCmdOptions)
    .timeout(new Timeout(50000))
    .version(Version.Main.PRODUCTION)
    .build()

  lazy val mongoRuntimeConfig =  new RuntimeConfigBuilder()
    .defaultsWithLogger(Command.MongoD, Logger.logger)
    .processOutput(ProcessOutput.getDefaultInstanceSilent)
    .build()

  lazy val mongoServer = MongodStarter.getInstance(mongoRuntimeConfig).prepare(mongodConfig)

  def before() = {
    mongoServer.start()
  }

  def after() = {
    mongoServer.stop()
  }

  override def around[T: AsResult](t: => T) = {
    val app = new FakeApp(port) // Set the mongodb port in configuration.
    try {
      before()
      Helpers.running(app)(AsResult.effectively(t))
    } finally {
      after()
    }
  }
}
```

**Comment by michaelmosmann** [comment]
Do you use Windows or MacOS? I guess, that the shutdown command will not reach the mongod server each time or the server needs to much time to shutdown so the port is still in use.

Can you provide more logging information?

**Comment by aveuiller** [comment]
I'm using linux (ubuntu 15.04) when I get the error, it is to be noted that on a Mac OS (el capitan) the error doesn't seem to happen.

I have the following logs right before the previous stacktrace: 

    [EMBED.MONGO output]note: noprealloc may hurt performance in many applications
    [EMBED.MONGO output] 2015-11-25T09:31:50.743+0100 E NETWORK  [initandlisten] listen(): bind() failed errno:98 Address already in use for socket: 0.0.0.0:44693
    [EMBED.MONGO output] 2015-11-25T09:31:50.744+0100 E NETWORK  [initandlisten]   addr already in use
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I STORAGE  [DataFileSync] warning: --syncdelay 0 is not recommended and can have strange performance
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] MongoDB starting : pid=10052 port=44693 dbpath=/tmp/embedmongo-db-783d2aa6-5d2c-4fa5-9ff6-862bc8023b82 64-bit host=antoine-HP-Nux
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] 
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] 
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] 
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] db version v3.0.5
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] git version: 8bc4ae20708dbb493cb09338d9e7be6698e4a3a3
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] build info: Linux build2.ny.cbi.10gen.cc 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64 BOOST_LIB_VERSION=1_49
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] allocator: tcmalloc
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I CONTROL  [initandlisten] options: { net: { http: { enabled: false }, port: 44693 }, security: { authorization: "disabled" }, storage: { dbPath: "/tmp/embedmongo-db-783d2aa6-5d2c-4fa5-9ff6-862bc8023b82", journal: { enabled: false }, mmapv1: { preallocDataFiles: false, smallFiles: true }, syncPeriodSecs: 0.0 } }
    [EMBED.MONGO output] 2015-11-25T09:31:50.747+0100 I INDEX    [initandlisten] allocating new ns file /tmp/embedmongo-db-783d2aa6-5d2c-4fa5-9ff6-862bc8023b82/local.ns, filling with zeroes...
    [EMBED.MONGO output] 2015-11-25T09:31:50.751+0100 I STORAGE  [FileAllocator] allocating new datafile /tmp/embedmongo-db-783d2aa6-5d2c-4fa5-9ff6-862bc8023b82/local.0, filling with zeroes...
    [EMBED.MONGO output] 2015-11-25T09:31:50.751+0100 I STORAGE  [FileAllocator] creating directory /tmp/embedmongo-db-783d2aa6-5d2c-4fa5-9ff6-862bc8023b82/_tmp
    [EMBED.MONGO output] 2015-11-25T09:31:50.751+0100 I STORAGE  [FileAllocator] done allocating datafile /tmp/embedmongo-db-783d2aa6-5d2c-4fa5-9ff6-862bc8023b82/local.0, size: 16MB,  took 0 secs
    [EMBED.MONGO output] 2015-11-25T09:31:50.752+0100 I CONTROL  [initandlisten] now exiting
    [EMBED.MONGO output] 2015-11-25T09:31:50.752+0100 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
    [EMBED.MONGO output] 2015-11-25T09:31:50.752+0100 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
    [EMBED.MONGO output] 2015-11-25T09:31:50.752+0100 I NETWORK  [initandlisten] shutdown: going to close sockets...
    [EMBED.MONGO output] 2015-11-25T09:31:50.752+0100 I STORAGE  [initandlisten] shutdown: waiting for fs preallocator...
    [EMBED.MONGO output] 2015-11-25T09:31:50.752+0100 I STORAGE  [initandlisten] shutdown: closing all files...
    [EMBED.MONGO output] 2015-11-25T09:31:50.752+0100 I STORAGE  [initandlisten] closeAllFiles() finished
    [EMBED.MONGO output] 2015-11-25T09:31:50.752+0100 I STORAGE  [initandlisten] shutdown: removing fs lock...
    [EMBED.MONGO output] 2015-11-25T09:31:50.752+0100 I CONTROL  [initandlisten] dbexit:  rc: 48


For info, I've got the following logs on a successful test:

    [EMBED.MONGO output]2015-11-25T09:37:18.692+0100 I CONTROL  [initandlisten] MongoDB starting : pid=16838 port=43037 dbpath=/tmp/embedmongo-db-479160aa-2e4c-4cd8-b584-95cf338143d1 64-bit host=antoine-HP-Nux
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] 
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] 
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] 
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] db version v3.0.5
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] git version: 8bc4ae20708dbb493cb09338d9e7be6698e4a3a3
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] build info: Linux build2.ny.cbi.10gen.cc 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64 BOOST_LIB_VERSION=1_49
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] allocator: tcmalloc
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I CONTROL  [initandlisten] options: { net: { http: { enabled: false }, port: 43037 }, security: { authorization: "disabled" }, storage: { dbPath: "/tmp/embedmongo-db-479160aa-2e4c-4cd8-b584-95cf338143d1", journal: { enabled: false }, mmapv1: { smallFiles: true } } }
    [EMBED.MONGO output] 2015-11-25T09:37:18.693+0100 I INDEX    [initandlisten] allocating new ns file /tmp/embedmongo-db-479160aa-2e4c-4cd8-b584-95cf338143d1/local.ns, filling with zeroes...
    [EMBED.MONGO output] 2015-11-25T09:37:18.696+0100 I STORAGE  [FileAllocator] allocating new datafile /tmp/embedmongo-db-479160aa-2e4c-4cd8-b584-95cf338143d1/local.0, filling with zeroes...
    [EMBED.MONGO output] 2015-11-25T09:37:18.696+0100 I STORAGE  [FileAllocator] creating directory /tmp/embedmongo-db-479160aa-2e4c-4cd8-b584-95cf338143d1/_tmp
    [EMBED.MONGO output] 2015-11-25T09:37:18.696+0100 I STORAGE  [FileAllocator] done allocating datafile /tmp/embedmongo-db-479160aa-2e4c-4cd8-b584-95cf338143d1/local.0, size: 16MB,  took 0 secs
    [EMBED.MONGO output] 2015-11-25T09:37:18.698+0100 I NETWORK  [initandlisten] waiting for connections on port 43037
    [EMBED.MONGO output] [info] application - ReactiveMongoPlugin starting...
    [info] application - ReactiveMongoPlugin successfully started with db 'Application'! Servers:
    		[localhost:43037]
    [info] application - ReactiveMongoApi starting...
    [info] application - ReactiveMongoApi successfully started with DB 'Application'! Servers:
    		[localhost:43037]
    2015-11-25T09:37:18.705+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53718 #1 (1 connection now open)
    [EMBED.MONGO output] 2015-11-25T09:37:18.706+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53719 #2 (2 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:18.706+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53720 #3 (3 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:18.706+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53721 #4 (4 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:18.706+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53722 #5 (5 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:18.706+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53723 #6 (6 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:18.706+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53724 #7 (7 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:18.706+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53725 #8 (8 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:18.706+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53726 #9 (9 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:18.706+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53727 #10 (10 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.224+0100 I INDEX    [conn1] allocating new ns file /tmp/embedmongo-db-479160aa-2e4c-4cd8-b584-95cf338143d1/Application.ns, filling with zeroes...
    [EMBED.MONGO output] 2015-11-25T09:37:19.227+0100 I STORAGE  [FileAllocator] allocating new datafile /tmp/embedmongo-db-479160aa-2e4c-4cd8-b584-95cf338143d1/Application.0, filling with zeroes...
    [EMBED.MONGO output] 2015-11-25T09:37:19.227+0100 I STORAGE  [FileAllocator] done allocating datafile /tmp/embedmongo-db-479160aa-2e4c-4cd8-b584-95cf338143d1/Application.0, size: 16MB,  took 0 secs
    
    [Test logs...]
    
    [info] application - ReactiveMongoPlugin stops, closing connections...
    2015-11-25T09:37:19.247+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53728 #11 (11 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.248+0100 I NETWORK  [conn11] end connection 127.0.0.1:53728 (10 connections now open)
    [EMBED.MONGO output] [info] application - ReactiveMongo Connections stopped. [Success(Closed)]
    [warn] r.c.a.MongoDBSystem - MongoDBSystem Actor[akka://reactivemongo/user/Connection-347#1118423252] stopped.
    [info] application - ReactiveMongoApi stopping...
    2015-11-25T09:37:19.255+0100 I NETWORK  [conn9] end connection 127.0.0.1:53726 (9 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.255+0100 I NETWORK  [conn8] end connection 127.0.0.1:53725 (9 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.255+0100 I NETWORK  [conn1] end connection 127.0.0.1:53718 (9 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.255+0100 I NETWORK  [conn2] end connection 127.0.0.1:53719 (9 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.255+0100 I NETWORK  [conn7] end connection 127.0.0.1:53724 (8 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.255+0100 I NETWORK  [conn3] end connection 127.0.0.1:53720 (7 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.256+0100 I NETWORK  [conn4] end connection 127.0.0.1:53721 (3 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.256+0100 I NETWORK  [conn10] end connection 127.0.0.1:53727 (3 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.256+0100 I NETWORK  [conn5] end connection 127.0.0.1:53722 (3 connections now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.256+0100 I NETWORK  [conn6] end connection 127.0.0.1:53723 (2 connections now open)
    [EMBED.MONGO output] [info] application - ReactiveMongoApi connections stopped. [Success(Closed)]
    2015-11-25T09:37:19.359+0100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53796 #12 (1 connection now open)
    [EMBED.MONGO output] 2015-11-25T09:37:19.359+0100 I COMMAND  [conn12] terminating, shutdown command received
    [EMBED.MONGO output] 2015-11-25T09:37:19.359+0100 I CONTROL  [conn12] now exiting
    [EMBED.MONGO output] 2015-11-25T09:37:19.359+0100 I NETWORK  [conn12] shutdown: going to close listening sockets...
    [EMBED.MONGO output] 2015-11-25T09:37:19.359+0100 I NETWORK  [conn12] closing listening socket: 5
    [EMBED.MONGO output] 2015-11-25T09:37:19.359+0100 I NETWORK  [conn12] closing listening socket: 6
    [EMBED.MONGO output] 2015-11-25T09:37:19.359+0100 I NETWORK  [conn12] removing socket file: /tmp/mongodb-43037.sock
    [EMBED.MONGO output] 2015-11-25T09:37:19.359+0100 I NETWORK  [conn12] shutdown: going to flush diaglog...
    [EMBED.MONGO output] 2015-11-25T09:37:19.359+0100 I NETWORK  [conn12] shutdown: going to close sockets...
    [EMBED.MONGO output] 2015-11-25T09:37:19.359+0100 I STORAGE  [conn12] shutdown: waiting for fs preallocator...
    [EMBED.MONGO output] 2015-11-25T09:37:19.359+0100 I STORAGE  [conn12] shutdown: closing all files...
    [EMBED.MONGO output] 2015-11-25T09:37:19.360+0100 I STORAGE  [conn12] closeAllFiles() finished
    [EMBED.MONGO output] 2015-11-25T09:37:19.360+0100 I STORAGE  [conn12] shutdown: removing fs lock...
    [EMBED.MONGO output] 2015-11-25T09:37:19.360+0100 I CONTROL  [conn12] dbexit:  rc: 0

**Comment by michaelmosmann** [comment]
if this is still an issue, please reopen...
