### ISSUE TITLE
Embedded Mongo shuts down the real mongod process

### ISSUE THREAD

**Issue by grundid** [flapdoodle-oss/de.flapdoodle.embed.mongo#141]
When I execute the test suite with embedded mongo on a machine with an already running (real) mongod process, this process is also shut down when the tests finish.

I tried changing the name of the embedded mongo process but without help.

**Comment by michaelmosmann** [comment]
can you shutdown your installed mongo and start the test again? IMHO the test should fail now. Can you provide some sample code? which port do you use?

**Comment by grundid** [comment]
When I shutdown the installed mongo the tests do not fail. But I just realized that my old config with Spring Boot was still active, so the test would always use the embedded mongo and the installed mongo (if available). After the tests finish all connected mongo servers have been shut down.

I'm not sure if it is possible to find out the right (=embedded) mongo instance when shutting down.

**Comment by michaelmosmann** [comment]
Hmm.. it should shutdown the instance with the right port.. I must write a test for this.. 

Can you provide some code from your test setup?

**Comment by grundid** [comment]
Well, Spring Boot does most of the stuff automatically. I still don't understand all the implications.
http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-mongodb

**Comment by michaelmosmann** [comment]
My guess: change the port to something other then the default port... try your test again. It should work and should not shutdown other mongod instances.

I will write a test to check an idea of what's gone wrong.. 

If you can provide some kind of log or stacktraces.. spring.io is using our project, so i am not sure if we can solve the problem on our side.

**Comment by ogr3** [comment]
Any relation to pr #136 ?

I also experience that flapdoodle shutsdown the running mongod.

**Comment by Loki-Afro** [comment]
@ogr3 could be. But then it should be fixed now, as well as all other mongo - commands. As current spring-boot projects do not show this error (which I saw 2 years ago too) I guess this issue is resolved, somehow. If not let me know ;)
