### ISSUE TITLE
Set authenticated HttpProxy

### ISSUE THREAD

**Issue by emmanuelperu** [flapdoodle-oss/de.flapdoodle.embed.mongo#151]
We can configure Customize Proxy for Download, but we can not set user and password for this proxy.
Can we have an evolution for this ?

**Comment by Loki-Afro** [comment]
@emmanuelperu I am not that familiar with proxies but does this help for the moment: http://stackoverflow.com/a/1626616/1248724 ?

@michaelmosmann whats your opinion on this?

**Comment by Loki-Afro** [comment]
Closing because of no input from @emmanuelperu
