### ISSUE TITLE
mongod --repair

### ISSUE THREAD

**Issue by craigb78** [flapdoodle-oss/de.flapdoodle.embed.mongo#155]
Hi, 
We're using de.flapdoodle.embed.mongo to start up and shutdown mongod in our app.
A problem we're having is that if we have a forced shutdown  (eg kill -9) the mongod lock file is still on disk and we can't restart.

Is it possible to run mongod --repair using flapdoodle? I can't find an option in MongoCmdOptionsBuilder. Or is there a better way to do this?

Craig

**Comment by michaelmosmann** [comment]
On which platform you are running this?

**Comment by craigb78** [comment]
It's no longer an issue for us since we're not using mongo anymore. Thanks
