### ISSUE TITLE
Aggregation filter not working

### ISSUE THREAD

**Issue by gauravic08** [flapdoodle-oss/de.flapdoodle.embed.mongo#156]
Hi,
Aggregation filter is throwing below exception: 
Command failed with error 15999: 'exception: invalid operator '$filter''

Aggregation pipleline that i am using :
{'$project': {'data':1, plb':{$filter:{'input':'$plb', 'as': 'pl', 'cond': {'$eq':['$$pl',false]}}}}}

**Comment by Loki-Afro** [comment]
what mongo version did you use? any stacktrace?

**Comment by Loki-Afro** [comment]
Aggregation works, I guess there is something wrong with your code ...

**Comment by gauravic08** [comment]
This issue was raised almost a year ago, so i don't remember what exact issue i was facing at that time.
