### ISSUE TITLE
Mongo stop fails randomly when running on travis

### ISSUE THREAD

**Issue by sudoku007** [flapdoodle-oss/de.flapdoodle.embed.mongo#157]
Hi,

We are noticing below random errors on Travis where it tries to stop mongo but fails with this error.

The Travis build seems to be running on *_Linux Docker *_container  :  Using worker: worker-linux-docker-d1986829.prod.travis-ci.org:travis-linux-13

We are using version : **1.50.3** and from **Scala Play framework.**

Any help on why this is happening or how to fix this would be much appreciated. One hack is to catch the IllegalStateException and ignore it, which is ugly.

[info] ----------------------------------------------------
[info] Something bad happend. We couldn't kill mongod process, and tried a lot.
[info] If you want this problem solved you can help us if you open a new issue.
[info] 
[info] Follow this link:
[info] https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues
[info] 
[info] Thank you:)
[info] ----------------------------------------------------
[info]   at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:192)
[info]   at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:76)
[info]   at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:189)
[info]   at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:117)
[info]   at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170)

**Comment by wongelz** [comment]
We started seeing this after upgrading from 1.48.2 to 1.50.5, so rolled back to 1.48.2 for now.

**Comment by michaelmosmann** [comment]
I will have a look..

**Comment by michaelmosmann** [comment]
Can you provide some more log-output?

**Comment by wongelz** [comment]
I'm seeing the same log output. Looks like the same issue as #162

**Comment by michaelmosmann** [comment]
I need some log before this stacktrace ..

**Comment by michaelmosmann** [comment]
Do you provide a custom port? I would guess that the process could not be started because the port is already used. So this exception is somewhat misleading.

**Comment by wongelz** [comment]
The log before this stacktrace is my own code. Yes, I am providing a custom port. Just added a catch for the IllegalStateException with some logging, I can see the server process has a processId and isProcessRunning returns true.

**Comment by michaelmosmann** [comment]
Do you use spring boot? It is the only test using mongo?

**Comment by Loki-Afro** [comment]
No progress here... If this error is present with the current version feel free to reopen this issue. :)

**Comment by krraghavan** [comment]
For what it's worth - I see this quite often in my Jenkins setup.  I do use Spring Boot - are there known issues with Spring Boot.  Would love to get some hints on how to work around or get this fixed.  I'm using version 2.0.0
