### ISSUE TITLE
Mongo fails to stop when using a custom net config in unit tests

### ISSUE THREAD

**Issue by saiimons** [flapdoodle-oss/de.flapdoodle.embed.mongo#162]
I am using the library in unit and integration tests, and it is failing to stop when I use a custom configuration (I am trying to specify a custom port when running my tests).

In my **@BeforeClass** I do :

``` java
    final MongodStarter starter = MongodStarter.getDefaultInstance();
    final IMongodConfig mongodConfig = new MongodConfigBuilder()
                .net(new Net(MONGO_PORT, Network.localhostIsIPv6()))
                .version(Version.Main.PRODUCTION)
                .build();

    mongodExecutable = starter.prepare(mongodConfig);
    mongod = mongodExecutable.start();
```

Then in my **@AfterClass** :

``` java
    mongodExecutable.stop();
```

This last line fails when I set up a custom port, but works if I don't.

> java.lang.IllegalStateException: Couldn't kill mongod process!
> ---
> 
> Something bad happend. We couldn't kill mongod process, and tried a lot.
> If you want this problem solved you can help us if you open a new issue.
> 
> Follow this link:
> https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues
> ## Thank you:)
> 
>   at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:192)
>   at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:76)
>   at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:189)
>   at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:117)
>   at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170)
>   at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:73)
>   at MY.TEST.CLASS.tearDownClass(UserAuthenticationTest.java:99)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
>   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
>   at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
>   at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
>   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
>   at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
>   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
>   at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
>   at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
>   at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
>   at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by michaelmosmann** [comment]
How do you know this port is free?

**Comment by michaelmosmann** [comment]
I would guess that the process could not be started because the port is already used. So this exception is somewhat misleading.

**Comment by michaelmosmann** [comment]
Are there multiple tests running parallel?

**Comment by saiimons** [comment]
I worked a bit my tests and it seems that I may have made a mistake, because it is working now.
Also switched from 1.50.2 to 1.50.5
