### ISSUE TITLE
Extremely slow with 3.2 

### ISSUE THREAD

**Issue by mudlee** [flapdoodle-oss/de.flapdoodle.embed.mongo#166]
We used to use 1.50.0 Embedmongo from maven, and Version.Main.V3_0.
We needed to upgrade MongoDb version 3.2, so I updated the embedmongo version to 1.50.5 and set up the version to Version.Main.V3_2.

Now, our tests are extremely slow, min 30 times slower than before. If I use 1.50.5 with Version.Main.V3_0, everything OK, the problem is only with V3_2.

BTW, I tried to run all tests with V3_1, but tests are slow again.

Did anyone else faced with this?

**Comment by mike-houghton** [comment]
Yes! We have done just what you have described and our tests are very slow.  20-40 times slower.

**Comment by Loki-Afro** [comment]
And ... why? If you think this is an flapdoodle issue:
1. Downgrade to the version where it has been fast.
2. Add a new Version 

```
IMongodConfig mongodConfig = new MongodConfigBuilder()
        .version(XXX)
        .net(new Net(bindIp, port, Network.localhostIsIPv6()))
        .build();
```

If this is really an issue of this project, please reopen this issue and I will look into it.

**Comment by segg3r** [comment]
Seems an issue is with WiredTiger (default engine in Mongo since 3.2). As a workaround i used
```
IMongodConfig mongoConfig = new MongodConfigBuilder()
	.version(Version.V3_2_0)
	.cmdOptions(new MongoCmdOptionsBuilder()
		.useStorageEngine("mmapv1")
		.build())
	.net(new Net(port, Network.localhostIsIPv6()))
	.build();
```

Maybe WiredTiger needs more memory or smth like that?

**Comment by Loki-Afro** [comment]
@segg3r are you starting with an existing database somehow?

**Comment by bguerout** [comment]
Hello,
On [jongo](https://github.com/bguerout/jongo), our tests were slower since MongoDB 3.2.
This seems due to the WiredProtocol:

> WiredTiger uses one file per collection and one file per index, so in this workload your system is very busy creating and removing files, which would explain the timings you're seeing.


We have switched to [`ephemeralForTest`](https://docs.mongodb.com/manual/release-notes/3.2/#ephemeralfortest-storage-engine) engine: https://github.com/bguerout/jongo/pull/346
Tests are now running 2x faster than before.

```java
IMongodConfig mongodConfig = new MongodConfigBuilder()
     .version(getVersion())
     .cmdOptions(new MongoCmdOptionsBuilder().useStorageEngine("ephemeralForTest").build())
     .net(network)
     .build();
```

**Comment by pnowy** [comment]
I will add from me that we had a similar problem on Mac (selected people on our company) and that was related with the long time to resolve ip-address for localhost when embedded mongo was starting (after upgrade to MacOS Sierra).

We solved the problem according to the solution described on this post:

https://thoeni.io/post/macos-sierra-java/

Additional links worth to check about that:

https://stackoverflow.com/questions/39636962/spring-data-mongodb-somehow-extremely-slow-after-upgrade-to-macos-sierra

https://stackoverflow.com/questions/39636792/jvm-takes-a-long-time-to-resolve-ip-address-for-localhost/39698914#39698914
