### ISSUE TITLE
add support for the latest version

### ISSUE THREAD

**Issue by vladimirdolzhenko** [flapdoodle-oss/de.flapdoodle.embed.mongo#169]
We're experimenting with some latest builds and new functionality of Mongo - e.g. http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-latest.zip - and like to have ability to specify version like LATEST (or EXPERIMENTAL) that will point to the latest build.

**Comment by Loki-Afro** [comment]
This is actually part of the current version
