### ISSUE TITLE
Upgrade to mongo-java-driver 3.3.0

### ISSUE THREAD

**Issue by trangvh** [flapdoodle-oss/de.flapdoodle.embed.mongo#170]
It should be upgraded to use the latest mongo-java-driver version, namely 3.3.0.

[This commit](https://github.com/mongodb/mongo-java-driver/commit/d12a26) adds a new codec to MongoClient.

**Comment by Loki-Afro** [comment]
Thank you @trangvh I updated the driver to `3.4.2` even if it should not affected you anyhow. It is scoped with `provided`
