### ISSUE TITLE
mongodb fails to delete a temporary file

### ISSUE THREAD

**Issue by manishpatelUK** [flapdoodle-oss/de.flapdoodle.embed.mongo#171]
Using maven dependency:

```
<dependency>
                <groupId>de.flapdoodle.embed</groupId>
                <artifactId>de.flapdoodle.embed.mongo</artifactId>
                <version>1.50.1</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-lang3</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-compress</artifactId>
                    </exclusion>
                </exclusions>
                <scope>test</scope>
            </dependency>
```

Within Intellij, if I debug a test and shut the test down prematurely (e.g. at a breakpoint) the temporary file that embedded mongo creates does not get deleted (I guess the shutdown hook never runs):

```
C:\Users\XXX\AppData\Local\Temp\extract-XXX-extractmongod.exe
```

Additionally, after installing BitDefender, this seems to happen even if I run a whole run without pausing and killing prematurely. I get the message at the end of the test:

```
[mongod output] 2016-09-16 13:50:24.716  WARN 13120 --- [      Thread-11] d.f.embed.process.io.file.Files          : could not delete C:\Users\XXX\AppData\Local\Temp\extract-XXX-extractmongod.exe. Will try to delete it again when program exits.
2016-09-16 13:50:24.721  WARN 13120 --- [      Thread-19] d.f.embed.process.io.file.Files          : could not delete C:\Users\XXX\AppData\Local\Temp\extract-XXX-extractmongod.exe. Will try to delete it again when program exits.
Exception in thread "Thread-11" java.lang.IllegalStateException: Shutdown in progress
    at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
    at java.lang.Runtime.addShutdownHook(Runtime.java:211)
    at de.flapdoodle.embed.process.io.file.FileCleaner.forceDeleteOnExit(FileCleaner.java:52)
    at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:125)
    at de.flapdoodle.embed.process.extract.ExtractedFileSets.delete(ExtractedFileSets.java:76)
    at de.flapdoodle.embed.process.store.ExtractedArtifactStore.removeFileSet(ExtractedArtifactStore.java:147)
    at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:77)
    at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:90)
    at java.lang.Thread.run(Thread.java:745)
```

It would be good to have a utility function that I can use to just delete this file at the start of a test.

**Comment by yogeshlonkar** [comment]
Faced same issue, following is a work around that can be used. This should be executed before start of embedded mongo db

        String tempFile = System.getenv("temp") + File.separator + "extract-" + System.getenv("USERNAME") + "-extractmongod";
        String executable;
        if (System.getenv("OS").contains("Windows")) {
            executable = tempFile + ".exe";
        } else {
            executable = tempFile + ".sh";
        }
        Files.deleteIfExists(new File(executable).toPath());
        Files.deleteIfExists(new File(tempFile + ".pid").toPath());

**Comment by manishpatelUK** [comment]
@yogeshlonkar you're a legend, thanks.

**Comment by Loki-Afro** [comment]
@manishpatelUK @yogeshlonkar thanks, signal handling in windows is a mess, especially with java, sorry for the inconvenience

**Comment by bnegrao** [comment]
Why is this issue closed?

I'm having the same issue here in my Windows 7 machine. I'm running Spring Boot 2.0.1 and the following:

    <dependency>
      <groupId>de.flapdoodle.embed</groupId>
      <artifactId>de.flapdoodle.embed.mongo</artifactId>
      <version>2.0.3</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>de.flapdoodle.embed</groupId>
      <artifactId>de.flapdoodle.embed.process</artifactId>
      <version>2.0.1</version>
      <scope>compile</scope>
    </dependency>

**Comment by alexander-huba-axon** [comment]
It happens when some failure has shutted down mongo or tests with mongo prematurely as @manishpatelUK kindly pointed out. 
**Possible solution**: delete this file backing up it beforehand. Worked for me.
