### ISSUE TITLE
Race conditions between JobKillers for shutdown

### ISSUE THREAD

**Issue by cmoetzing** [flapdoodle-oss/de.flapdoodle.embed.mongo#172]
When I use embed.mongo I always get errors when shutting down the embedded db. This only occurs on windows (see linux.txt vs. windows.txt).
[windows.txt](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/files/500479/windows.txt)
[linux.txt](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/files/500470/linux.txt)

Looking into the code I found following structure:
MongodProcess > AbstractMongoProcess > AbstractProcess > IStopable
MongodExecutable > Executable > IStopable

Starting an embedded mongo is done via 
`MongoExecutable.start() { return new MongoProcess() }`
for _mongod_. The Process wraps the executable. Since _Executable_ and _AbstractProcess_ both register a _JobKiller_ that is calling stop() and both have a separate flag
`if (!stopped) {` my guess is that the mongo is shutdown twice (for the process and for the executable).

From my quick analysis I would say the process should delegate all stop() related tasks to the executable. Currently the executable could be changed to not implement _IStoppable_ because the process does everything.

What I can not understand is why it works for linux as the race condition should be present there aswell.

I am willing to provide a pull request. I would envision something like this:
The Process asks the executable if it did register a _JobKiller_. If it did, it does not do it itself. If it didn't the process takes care of registering a _JobKiller_.

Also, this looks loosely related to issue #22 (where the last to commenters said it isn't fixed for them)?

**Comment by cmoetzing** [comment]
Added https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/pull/46 as 	basis for discussion.

**Comment by Loki-Afro** [comment]
@cmoetzing can i close this issue or is here something to do?
