### ISSUE TITLE
Can’t control where to put the Mongo binaries

### ISSUE THREAD

**Issue by mrmanc** [flapdoodle-oss/de.flapdoodle.embed.mongo#177]
When embedded Mongo starts, it downloads binaries to the directory specified in the [config](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-artifact-storage). In a shared continuous integration environment it is preferable to be able to control this location using environment variables, to avoid every developer who uses this library having to remember to configure the artifact store path.

Would you be open to me starting a PR to provide this functionality? I’m thinking it would be a small change (along with tests) to [DownloadConfigBuilder](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/config/DownloadConfigBuilder.java#L47) to check an environment variable for a default location before using UserHome.

**Comment by matlockx** [comment]
sure! Go on. Without looking it up, shouldn't it be located in the users home which runs the ci server? So should be shared by default or not?

**Comment by mrmanc** [comment]
I think the user’s home directory is a good default, but in our case (using GoCD) the user’s home directory is created by the CI agent package in a location without much storage (`/var`). I agree the artifacts should be shared, and by using an environment variable that should continue—it means we can stick a line in the user’s profile and avoid having that configuration in every code base.

How do you feel about `EMBEDDED_MONGO_ARTIFACTS` for the environment variable?

**Comment by Loki-Afro** [comment]
This has been merged, closing issue...
