### ISSUE TITLE
publish 1.50.6 (non-SNAPSHOT) artifact (request)

### ISSUE THREAD

**Issue by emanresusername** [flapdoodle-oss/de.flapdoodle.embed.mongo#180]
had a little scare today with some tests that seemingly mysteriously stopped working over the weekend. 
after some sleuthing, found it was due to the `de.flapdoodle.embed.process` `1.50.3-SNAPSHOT` artifact [being modified](https://oss.sonatype.org/content/repositories/snapshots/de/flapdoodle/embed/de.flapdoodle.embed.process/)
was easy enough to pin back to `1.5.2` for that, but for this `1.5.5` doesn't work (for us), so would help us rest easier to know that there was a stable `1.5.6` artifact out there just in case something similar happens to the latest snapshot

**Comment by Loki-Afro** [comment]
Well 2.0.0 is released ;)
