### ISSUE TITLE
MongoS cannot be started under version 3.4

### ISSUE THREAD

**Issue by rlodge** [flapdoodle-oss/de.flapdoodle.embed.mongo#182]
Because apparently they've removed the "chunkSize" parameter.  You get:

`Error parsing command line: unrecognised option '--chunkSize'[mongos error] `

Can the code around line 40 of de.flapdoodle.embed.mongo.runtime.Mongos be changed to make this configurable somehow?

**Comment by Loki-Afro** [comment]
This has been fixed in e88599588c5ebc12323ef9a08018a691b1148e6a and should be in version 2.0.0 :)
