### ISSUE TITLE
How can I restart embedded mongodb after adding a user ?

### ISSUE THREAD

**Issue by madhawa-gunasekara** [flapdoodle-oss/de.flapdoodle.embed.mongo#197]
I'm writing some integration tests which I need to enable MONGODB-CR authentication to the mongo server.  How can I do it? I know MONGODB-CR is no longer use in MONGODB. I'm using MONGO 2.4

Any help regarding this.

**Comment by Loki-Afro** [comment]
I do not know how exactly this works in mongodb, however I know that you have to pass `--auth`to the mongod instance or provide a config file.

This can be done by:

```
MongodConfigBuilder builder = ...
builder.cmdOptions(new MongoCmdOptionsBuilder().enableAuth(true).build());
...
````

hope that helps :)
