### ISSUE TITLE
MongoImportProcess shouldn't shutdown the database when import fails

### ISSUE THREAD

**Issue by thall-csky** [flapdoodle-oss/de.flapdoodle.embed.mongo#198]
Currently when mongo import fails it stops the database.
Like MongoRestoreProcess, MongoImportProcess should override stopInternal, something like:

@Override public void stopInternal() {
        // Nothing to stop since we are just running mongo import and don't want to kill the mongo instance
}

**Comment by Loki-Afro** [comment]
hey @thall-csky this is fixed by gh-191, sorry for the delay :)
