### ISSUE TITLE
Default embedded mongodb downloaded even when setting custom download URL

### ISSUE THREAD

**Issue by stevenikkola** [flapdoodle-oss/de.flapdoodle.embed.mongo#202]
I asked a question about this on [stackoverflow](http://stackoverflow.com/questions/43859116/how-to-prevent-the-default-embedded-mongodb-from-being-downloaded) in case that is the better place for this (as I may just be doing something wrong rather than this being a defect), but haven't got any replies, so posting this here.

Here are the same details I posted:

I am using version 2.0.0 of flapdoodle to run embedded mongo integration tests in a Java Springboot application.

In a `@DataMongoTest` test case I am working on, I am using the MongodConfigBuilder to set a specific version:
`	mongodExe = starter.prepare(new MongodConfigBuilder()
			.version(Versions.withFeatures(new GenericVersion("3.4.2"), Feature.SYNC_DELAY))
			.net(new Net("localhost", 12345, Network.localhostIsIPv6())).build());`

Later, I am also creating an IRuntimeConfig to set a custom downloadUrl to ensure all dependencies are from within my local network. This all works as expected and the specified embedded mongodb/version is pulled from the URL I am specifying. However, before it does this, it downloads what must be the default version of mongo as well (currently 3.2.2):

For example:
`{"message":"Download 3.2.2:OS_X:B64 : 10 %","logger_name":"org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo","thread_name":"main","level":"INFO"}
    {"message":"Download 3.2.2:OS_X:B64 : 20 %","logger_name":"org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo","thread_name":"main","level":"INFO"}
    {"message":"Download 3.2.2:OS_X:B64 : 30 %","logger_name":"org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo","thread_name":"main","level":"INFO"}
`

What do I need to set so the default version will not be downloaded? It is not used, so it is unnecessary, and it is pulling from an external resource which I want to avoid.

Also: additional question: when setting a mongo version (in this part): `.version(Versions.withFeatures(new GenericVersion("3.4.2"), Feature.SYNC_DELAY))` , how do I know what 'features' to include? Any more info on that part?

**Comment by Loki-Afro** [comment]
Could you please provide a simple example project?
