### ISSUE TITLE
Receiving de.flapdoodle.embed.process.exceptions.DistributionException: java.nio.file.FileAlreadyExistsException

### ISSUE THREAD

**Issue by erip** [flapdoodle-oss/de.flapdoodle.embed.mongo#203]
Full disclosure, I'm using [Embed Mongo](https://github.com/SimplyScala/scalatest-embedmongo), but I think the error is caused by the way I'm handing my `RuntimeConfigBuilder`.

Currently, I'm building my `RuntimeConfigBuilder` like this:

```
  val runtimeConfig = new RuntimeConfigBuilder()
    .defaults(Command.MongoD)
    .processOutput(ProcessOutput.getDefaultInstanceSilent)
    .artifactStore(new ExtractedArtifactStoreBuilder()
    .defaults(Command.MongoD)
    .download(new DownloadConfigBuilder()
      .defaultsForCommand(Command.MongoD).build())
    // Following line creates file "$TMPDIR/extractextractmongod"
    .executableNaming(new NoopTempNaming()))
    .build()
```

This creates a temp file which is never deleted. Is there a way to ensure this file is deleted automatically? If not, I get an exception because the file already exists between successive test runs. My current workaround is a bit of a kludge, which assumes that my file will always be in `"$TMPDIR/extractextractmongod"`:

```File(System.getenv("TMPDIR") + "extractextractmongod").delete()```

**Comment by Loki-Afro** [comment]
Could you provide a small example project? I am not that fit in scala... :/

**Comment by erip** [comment]
I think it's related to #171. I can try to make a dumb app later to replicate behavior.

**Comment by erip** [comment]
Ah, I think my issue may have been a multithreading issue. If I can repro, I'll post an example app. Until then, I'll close this.
