### ISSUE TITLE
Binary downloaded even though it exists

### ISSUE THREAD

**Issue by roberterdin** [flapdoodle-oss/de.flapdoodle.embed.mongo#204]
If the file structure is as follows, i.e. the default, the behaviour is as expected. The binary is only downloaded if does not exist.
```
artifactStorePath/
├───extracted/
│   └───Windows-B64--3.2.1/
│        └──extractedmongod.exe
└───win32/
│   └───mongodb-win32-x86_64-3.2.1.zip
```
If the zip file is removed as follows, it will be downloaded again the next time it is executed. Even though the actual executable is still available.
``` 
artifactStorePath/
├───extracted/
│   └───Windows-B64--3.2.1/
│        └──extractedmongod.exe
└───win32/
```

The .zip file is ~150MB, compared to the 20MB of the executable. We have to package the executable in some cases. Having to package it for every platform bloats up the file size of the application significantly if the .zip files have to be present.

Is there a way to specify an exact path to the executable? If not, would you accept a PR that changes the logic such that the `extracted` folder is checked in order to determine whether the binary has to be downloaded?

Cheers

**Comment by roberterdin** [comment]
I looked at the code and figured out that this concerns https://github.com/flapdoodle-oss/de.flapdoodle.embed.process. Would you be willing to accept a PR that addresses this issue or is it behaving as expected?

**Comment by barryearles** [comment]
On my.
Pp

**Comment by roberterdin** [comment]
I found a workaround (having a nice conversation with myself here :smile:). All the irrelevant files can be delted from the archive and only the mongod executable left in there... it's a bit hacky but on the plus side it decreases the size.

**Comment by michaelmosmann** [comment]
:)

... there is refactoring ahead to make these things smoother.

**Comment by Loki-Afro** [comment]
@roberterdin closing for https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/232 and you found your own workaround ;)
