### ISSUE TITLE
Support using library in hermetic environments

### ISSUE THREAD

**Issue by ittaiz** [flapdoodle-oss/de.flapdoodle.embed.mongo#205]
We want to use wix-embedded-mysql in [Bazel](https://github.com/wix/wix-embedded-mysql/issues/bazel.build) which strongly encourages you to have tests which are isolated from the internet.
For that matter we want to allow preparing the installer (downloading/extracting) before the actual test run (in Bazel such downloads should happen in the fetch phase).
What I've done in the [wix-embedded-mysql](https://github.com/wix/wix-embedded-mysql) project is add another module with a runnable jar which has a cli entry point for this which accepts a cache dir and a version.
Are you open to such a contribution?

mysql [PR](https://github.com/wix/wix-embedded-mysql/pull/108)

**Comment by Loki-Afro** [comment]
I guess if it is in the same manner as https://github.com/wix/wix-embedded-mysql/pull/108 there shouldn't be a problem.

@michaelmosmann  what do you think?

**Comment by michaelmosmann** [comment]
Can we achieve this without adding a sub-module?

**Comment by ittaiz** [comment]
We can but then you have a few options:
1. Expose only a main without a runnable jar- not really useful for users since they need to "guess" the correct classpath
2. Add assembly plugin to current module- might be a bit weird to have this tool as a "cannonical" runnable jar of this module. It's not it's essence but an additional way to use it. Additionally if we'll need to use a library for argument parsing we're limited there since it will add it to library users.

That's why I recommend adding another module.
BTW, I appreciate the responsiveness, thanks!

**Comment by michaelmosmann** [comment]
ok.. so let's do it..
