### ISSUE TITLE
Can embedded Mongo keep the date between the runs?

### ISSUE THREAD

**Issue by muxmeg** [flapdoodle-oss/de.flapdoodle.embed.mongo#206]
I couldn't find out how can I keep using the old data that I've saved into Mongo in the previous execution, like in embedded H2 DB. This way I could use it not only for tests but for small applications development too.
Is this supported?

**Comment by michaelmosmann** [comment]
You must provide a custom database path...
...but I can not recommend this for any non-fun-application.




Am 21. Juli 2017 2:11:54 nachm. schrieb muxmeg <notifications@github.com>:

**Comment by muxmeg** [comment]
I've tried it by adding this line to application.properies:
`spring.mongodb.embedded.storage.database-dir=mongoEmbedded`
It saves to this folder now, but the DB is still empty after a restart.

I wonder, why do you think it doesn't suit for local development? I've used embedded H2 like this some time ago and it was fine.

**Comment by Loki-Afro** [comment]
@muxmeg Well H2 is designed for such purposes. Mongodb is not.

I would recommand using something like docker with a volume or vagrant. Since Mongodb is schemaless this is really not a problem. Even for tiny applications.

**Comment by muxmeg** [comment]
Thanks, I'll use your advice!
