### ISSUE TITLE
Downloading 32 bit mongodb on a 64 bit Windows environment

### ISSUE THREAD

**Issue by habak67** [flapdoodle-oss/de.flapdoodle.embed.mongo#207]
Hello.

I'm running Windows 7 Enterprise and when running MongoDB manually i succesfully run the 64 bit version  (x86_64). When I use the embedded Mongodb it however download and start the 32 bit version (Extract C:\Users\s38709\.embedmongo\win32\mongodb-win32-i386-3.2.1.zip extract mongodb-win32-i386-3.2.1/bin/mongod.exe) and then I get an error message about wiredTiger not included.

[mongod output] 2017-07-22T11:52:11.051+0200 I CONTROL  [initandlisten] MongoDB starting : pid=9436 port=49195 dbpath=C:\Users\s38709\AppData\Local\Temp\embedmongo-db-e1f07c00-bb66-4f04-88a3-cfe24d979c87 32-bit host=B5481049
[mongod output] 2017-07-22T11:52:11.051+0200 I CONTROL  [initandlisten] targetMinOS: Windows Vista/Windows Server 2008
[mongod output] 2017-07-22T11:52:11.051+0200 I CONTROL  [initandlisten] db version v3.2.1
[mongod output] 2017-07-22T11:52:11.051+0200 I CONTROL  [initandlisten] git version: a14d55980c2cdc565d4704a7e3ad37e4e535c1b2
[mongod output] 2017-07-22T11:52:11.051+0200 I CONTROL  [initandlisten] allocator: tcmalloc
[mongod output] 2017-07-22T11:52:11.051+0200 I CONTROL  [initandlisten] modules: none
[mongod output] 2017-07-22T11:52:11.051+0200 I CONTROL  [initandlisten] build environment:
[mongod output] 2017-07-22T11:52:11.051+0200 I CONTROL  [initandlisten]     distarch: i386
[mongod output] 2017-07-22T11:52:11.051+0200 I CONTROL  [initandlisten]     target_arch: i386
[mongod output] 2017-07-22T11:52:11.051+0200 I CONTROL  [initandlisten] options: { net: { http: { enabled: false }, port: 49195 }, security: { authorization: "disabled" }, storage: { dbPath: "C:\Users\s38709\AppData\Local\Temp\embedmongo-db-e1f07c00-bb66-4f04-88a3-cfe24d979c87", journal: { enabled: false }, mmapv1: { preallocDataFiles: false, smallFiles: true }, syncPeriodSecs: 0.0 } }
[mongod output] 2017-07-22T11:52:11.052+0200 I STORAGE  [initandlisten] exception in initAndListen: 28663 Cannot start server. The default storage engine 'wiredTiger' is not available with this build of mongod. Please specify a different storage engine explicitly, e.g. --storageEngine=mmapv1., terminating
[mongod output] 2017-07-22T11:52:11.052+0200 I CONTROL  [initandlisten] dbexit:  rc: 100
[mongod output] 11:52:11.118 [main] ERROR d.f.e.p.runtime.AbstractProcess - failed to call onAfterProcessStart()

I managed to "fix" it by setting a command option to use mmapv1

    	IMongoCmdOptions mco = new MongoCmdOptionsBuilder().useStorageEngine("mmapv1").build();
        return new MongodConfigBuilder().version(Version.Main.PRODUCTION).cmdOptions(mco).build();

But I still wonder why it downloads the 32 bit version when I'm running a 64 bit Windows version and is there any way to configure so that a 64 bit version is downloaded.

In the end I really want to use Spring boot with autoconfiguration support for embedded mongodb (which uses flapdoodle) and in this environment I don't know how to set the command option to fix the wiredTiger issue. Spring boot autoconfiguration is really nice when everything works but when it doesn't... (a little bit to much black magic for my knowledge :-)

**Comment by Loki-Afro** [comment]
make sure operating system mongodb and your jdk have matching bitness

**Comment by habak67** [comment]
Thank you for guiding me in the correct direction. For some reason I had selected an old 32 bit JDK for my eclipse project. Now I have changed to a new 64 bit version and everything works nice.

[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten] MongoDB starting : pid=10372 port=49705 dbpath=C:\Users\s38709\AppData\Local\Temp\embedmongo-db-9269f3d9-123e-4f44-b408-4897c5f765a3 64-bit host=B5481049
[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten] targetMinOS: Windows 7/Windows Server 2008 R2
[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten] db version v3.2.1
[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten] git version: a14d55980c2cdc565d4704a7e3ad37e4e535c1b2
[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten] allocator: tcmalloc
[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten] modules: none
[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten] build environment:
[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten]     distmod: 2008plus
[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten]     distarch: x86_64
[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten]     target_arch: x86_64
[mongod output] 2017-07-22T14:20:47.959+0200 I CONTROL  [initandlisten] options: { net: { http: { enabled: false }, port: 49705 }, security: { authorization: "disabled" }, storage: { dbPath: "C:\Users\s38709\AppData\Local\Temp\embedmongo-db-9269f3d9-123e-4f44-b408-4897c5f765a3", journal: { enabled: false }, mmapv1: { preallocDataFiles: false, smallFiles: true }, syncPeriodSecs: 0.0 } }
[mongod output] 2017-07-22T14:20:47.960+0200 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=8G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=0,log_size=2GB),statistics_log=(wait=0),,log=(enabled=false),
[mongod output] 2017-07-22T14:20:48.117+0200 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
[mongod output] 2017-07-22T14:20:48.120+0200 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
[mongod output] 2017-07-22T14:20:48.120+0200 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory 'C:/Users/s38709/AppData/Local/Temp/embedmongo-db-9269f3d9-123e-4f44-b408-4897c5f765a3/diagnostic.data'
[mongod output] 2017-07-22T14:20:48.187+0200 I NETWORK  [initandlisten] waiting for connections on port 49705

**Comment by ogerardin** [comment]
> make sure operating system mongodb and your jdk have matching bitness

IMHO this is too strong a requirement, as technically a 32-bit JVM is perfectly able to control a 64-bit version of MongoDB (on a 64-bit OS of course).

Since this is related to the OS bitness detection in `de.flapdoodle.embed.process.distribution.BitSize`, I have filed an issue in project de.flapdoodle.embed.process: https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/32

Thanks for considering it :)

**Comment by harmoney-max** [comment]
Was the JAVA version running on my local machine. I downloaded the last one for 64 bit, but for some reason, download a mongo embedded version for 32 bit. I did the change to an older java version (java version "1.8.0_271") and works perfectly. Thanks so much for your aport.
