### ISSUE TITLE
Support for mongoDB 3.4.9

### ISSUE THREAD

**Issue by keraton** [flapdoodle-oss/de.flapdoodle.embed.mongo#213]
Hi could you support mongoDB 3.4.9 ?

**Comment by michaelmosmann** [comment]
i think so.. can you make an pull request? the other way will take a little bit longer..

**Comment by keraton** [comment]
Ok let me see this.

**Comment by lipnitsk** [comment]
@michaelmosmann Any plans on a release sometime soon?

**Comment by Loki-Afro** [comment]
@lipnitsk there is a new release out
