### ISSUE TITLE
Customize Download URL does not work properly

### ISSUE THREAD

**Issue by cimoca** [flapdoodle-oss/de.flapdoodle.embed.mongo#214]
I have a spring boot project 1.5.3.RELEASE that uses a managed version 1.50.5 for de.flapdoodle.embed.mongo.

I set in IRuntimeConfig .proxyFactory and .downloadPath and in IMongodConfig .version(Version.Main.PRODUCTION)

When  I run the test case mongodb-linux-x86_64-3.2.1.tgz is downloaded correctly from the external path and Mongo is started but another attempt is made to download version 3.2.2 from http://fastdl.mongodb.org

Because the bamboo server does not have access to it the tests case fails.

"java.io.IOException: Could not open inputStream for http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.2.tgz
Caused by: java.net.SocketTimeoutException: connect timed out
at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127)

How can I avoid downloading the second time from http://fastdl.mongodb.org? Why if I specify 
the version Version.Main.PRODUCTION which maps to V3_2(V3_2_1), version 3.2.2 is still being downlaoded

Thanks so much!

**Comment by cimoca** [comment]
Found the problem. please ignore.

**Comment by bdetweiler** [comment]
@cimoca How did you solve this? I'm having a similar issue.
