### ISSUE TITLE
API report for Flapdoodle Embedded MongoDB

### ISSUE THREAD

**Issue by lvc** [flapdoodle-oss/de.flapdoodle.embed.mongo#215]
Hi,

There is a report on backward binary compatibility and API changes for the library: https://abi-laboratory.pro/java/tracker/timeline/de.flapdoodle.embed.mongo/

It's generated for http://central.maven.org/maven2/de/flapdoodle/embed/de.flapdoodle.embed.mongo/.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![de flapdoodle embed mongo-2](https://user-images.githubusercontent.com/1517837/31269199-1a4d9dc0-aa88-11e7-98b9-90f645305585.png)
![de flapdoodle embed mongo-1](https://user-images.githubusercontent.com/1517837/31269200-1a4de474-aa88-11e7-8640-b888ce992855.png)

**Comment by matlockx** [comment]
thanks, updated the readme
