### ISSUE TITLE
Extract dll files to support alternative MongoDB distributions on Windows

### ISSUE THREAD

**Issue by joankaradimov** [flapdoodle-oss/de.flapdoodle.embed.mongo#216]
By tweaking the `downloadPath` of `DownloadConfig` and `version` of `MongodConfig` I was able to get MongoDB Enterprise to download. However, it refused to run on Windows. The reason is that there are some DLLs that are missing (libeay32.dll, libsasl.dll, netsnmp.dll, ssleay32.dll)

Manually copying these DLLs to the `Temp` directory fixes the problem and mongod starts.

This does not appear to be a problem in OSX and Linux. The libraries are either statically linked (less likely) or the ones that are distributed with the OS are used (more likely).

Is it sensible to request this feature? I noticed the existence of an `addLibraryFiles` method in [de.flapdoodle.embed.process](https://github.com/flapdoodle-oss/de.flapdoodle.embed.process), but I wasn't able to implement it in reasonable time and make a pull request.

I know this is probably not a supported scenario, but the in-memory storage engine in the Enterprise Edition is noticeably faster. And even if someone doesn't have the license, there's this piece of the [license](https://www.mongodb.com/subscription-agreement/november-2016) which makes it ok to use it for development purposes...

> (b) Free Evaluation and Development. MongoDB grants you a royalty-free, nontransferable (except to your Affiliates), and nonexclusive license to **use and reproduce the Software in your internal environment for evaluation and development purposes**. You will not use the Software for any other purpose, including testing, quality assurance or production purposes without purchasing an Enterprise Advanced Subscription. We provide the free trial of our Software on an “AS-IS” basis without any warranty.

**Comment by michaelmosmann** [comment]
..hmm.. interesting. It should be not that hard to fix this. But not this week.

Michael:)


Am 8. Oktober 2017 5:31:30 nachm. schrieb Joan Karadimov 
<notifications@github.com>:

**Comment by Loki-Afro** [comment]
@joankaradimov will get fixed with https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/232
