### ISSUE TITLE
Consecutive tests with Spring/JUnit fail with java.io.IOException: Could not start process: <EOF>

### ISSUE THREAD

**Issue by ogerardin** [flapdoodle-oss/de.flapdoodle.embed.mongo#218]
Note: this is different from https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/167, in my case the problem occurs only during consecutive stops and starts of Mongo.

I'm using Embedded Mongo with Spring Boot. I have a few JUnit tests that run with SpringRunner and use Mongo. Each of these tests runs fine separately, but if I run them in sequence using IntelliJ or Maven test, some of them fail with the exception:  

`java.io.IOException: Could not start process: <EOF>`

If I look at the log just before the exception, I see the following lines:

```
2017-10-27T20:40:08.770+0200 E NETWORK  [initandlisten] listen(): bind() failed Address already in use for socket: 127.0.0.1:27017
2017-10-27T20:40:08.770+0200 E NETWORK  [initandlisten]   addr already in use
2017-10-27T20:40:08.770+0200 E NETWORK  [initandlisten] Failed to set up sockets during startup.
2017-10-27T20:40:08.770+0200 E STORAGE  [initandlisten] Failed to set up listener: InternalError: Failed to set up sockets
```

So apparently the socket from the last mongo run is still in use when the new process tries to start. Is there a proper way to avoid this? Should I randomize the port? Insert a wait after the test has run? Or is there something else I can do to make sure the port is free?

I should add that the behaviour is the same under Windows and Mac OS.

**Comment by Loki-Afro** [comment]
I think DirtiesContext is the key word here https://stackoverflow.com/a/15948370/1248724

**Comment by ogerardin** [comment]
Spot on! That did the trick. Now all tests pass even when they are run together.
Thank you!
