### ISSUE TITLE
[question] production usage experience?

### ISSUE THREAD

**Issue by archenroot** [flapdoodle-oss/de.flapdoodle.embed.mongo#219]
Hi guys,

thank you first of all for this stuff. Now with rise of microservices based on event sourcing, CQRS patterns, the central truth has moved into so called Event Store while local instances bounded to microsrvice can be reuild completely from scratch.  

So I started thinking that as soon as local service database lives together and only with its service as parent, deploying service with embedded mongo (or any other) database could be quite nice idea to simplify the deployment and config. 

Any thoughts?

**Comment by Loki-Afro** [comment]
Just use it as compile dependency the rest is up to dependency injection and some glue code or am I missing something?

**Comment by archenroot** [comment]
Not really, the only idea is that when the service goes up, the database as well, and on any kind of shutdown/restart, the database is killed/restarted as well. So the point of view is service and database is single component

**Comment by Loki-Afro** [comment]
You should consider a container or similar as a service without bundling a database directly into your application. But everything has its pro and cons...

**Comment by archenroot** [comment]
@Loki-Afro thanks loki. Well that is true in old-fashioned scenarios, but in event driven microservices architecture local service database can bee seen as service itself, it is just persistent component.

But I understand when you do high-performance microservices you will need to separate service and persistence layers as they need to scale independently...

Thanks for comments.
