### ISSUE TITLE
Race conditions between JobKillers

### ISSUE THREAD

**Issue by adutra** [flapdoodle-oss/de.flapdoodle.embed.mongo#22]
Currently two shutdown hooks are registered when launching Embedmongo:
1. `de.flapdoodle.embed.process.runtime.AbstractProcess.JobKiller`
   1. Stops Mongod process
   2. Deletes temporary database dir
2. `de.flapdoodle.embed.process.runtime.Executable.JobKiller`
   1. Deletes executable file

This creates a race condition: if `Executable.JobKiller` is executed first, it will throw an `IOException` because the executable file is locked by the Mongod process.

Currently the `IOException` is swallowed by `Files.forceDelete()`, which tries to delete the file again later. But this is not a proper way to deal with the race condition (see [Issue 23](https://github.com/flapdoodle-oss/embedmongo.flapdoodle.de/issues/23)).

I can see two ways to fix this:
1. Use only one shutdown hook to perform all actions in the proper order;
2. Make `Executable.JobKiller` wait on a lock or semaphore before trying to delete the executable file.

**Comment by LaughXP** [comment]
when I run my code in windows 7 ,it will happends this error.Ubuntu is not.
