### ISSUE TITLE
 Cannot run program "/tmp/extract-d928b77d-d707-419e-9326-c8272346c1ceextractmongod

### ISSUE THREAD

**Issue by emichaf** [flapdoodle-oss/de.flapdoodle.embed.mongo#220]
Receive error:
java.io.IOException: Cannot run program "/tmp/extract-d928b77d-d707-419e-9326-c8272346c1ceextractmongod": error=2, No such file or directory
Caused by: java.io.IOException: error=2, No such file or directory

Executing tests in docker (in kubernetes) with system:
Platform : JVM : Oracle Corporation version: 1.8.0_111-internal-alpine-r0-b14 OS : Linux version: 3.10.0-514.26.2.el7.x86_64 arch: amd64 cores: 4

components in Docker image used:
Badeimage: frolvlad/alpine-glibc
DOCKER_VERSION=1.13.1 
DOCKER_COMPOSE_VERSION=1.11.1
MAVEN_VERSION 3.3.9
kubectl v1.6.4

**Comment by emichaf** [comment]
Solved

**Comment by matlockx** [comment]
@emichaf maybe you could write shortly how you fixed the problem? might not be embedmongo related but could help other people later with a same problem. thx

**Comment by emichaf** [comment]
It was a combination of the Image build -> added base image with  glibc support and set env LC_ALL=C, then set privileged: true for container in POD for Kubernetes.

**Comment by saschpe** [comment]
Just in case, we stumbled across the same issue as we where using **openjdk:8-alpine3.9** in our CI environment. Switching to **openjdk:8** helped as we didn't want to maintain another Dockerfile for a particular CI build (even though adding glibc to Alpine isn't difficult: https://github.com/saschpe/docker-android-sdk/blob/master/Dockerfile#L22)
