### ISSUE TITLE
writeConcern=journal query param is ignored

### ISSUE THREAD

**Issue by asarkar** [flapdoodle-oss/de.flapdoodle.embed.mongo#222]
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/runtime/Mongod.java#L156 looks for `--nojournal` but what about when the user wants to set `writeConcern=journal`? Specifying it with the URI is not working for embedded. I'm not a Mongo expert, so if there's a way to enable journaling, let me know.

**Comment by asarkar** [comment]
After some digging, it appears that the URI option is ignored. The only way I found is by baking it in the `IMongodConfig`. Here's a Scala version:

```
new MongodConfigBuilder()
      .version(Version.Main.PRODUCTION)
      .net(new Net(host, port, Network.localhostIsIPv6))
      .cmdOptions(new MongoCmdOptionsBuilder().useNoJournal(false).build())
      .build
```

**Comment by Loki-Afro** [comment]
@asarkar thanks for providing the solution ;) Sorry for the late reply, did not have much time this year yet
