### ISSUE TITLE
Is there an ETA on the next release?

### ISSUE THREAD

**Issue by roberttaylor426** [flapdoodle-oss/de.flapdoodle.embed.mongo#228]
Hi, I'm the author of [a downstream project](https://github.com/sourcemuse/GradleMongoPlugin) that leverages your library; thanks for all your efforts!

I was wondering when you anticipate making your next release? I have a number of users who are eager for Mongo 3.6 support, but we're blocked right now as this is currently unavailable in the 2.0.0 release. I notice support was added in [a recent PR](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/224).

**Comment by Loki-Afro** [comment]
@michaelmosmann ping

**Comment by matlockx** [comment]
I can do a release tomorrow evening if @michaelmosmann cannot until then

**Comment by roberttaylor426** [comment]
Bump. :-)

**Comment by matlockx** [comment]
2.0.1 should be available now

**Comment by roberttaylor426** [comment]
Great, thanks!
