### ISSUE TITLE
High CPU usage with Mongo 3.6

### ISSUE THREAD

**Issue by thetric** [flapdoodle-oss/de.flapdoodle.embed.mongo#229]
After upgrading from Mongo 3.4.10 to 3.6.0 I have noticed a significant higher CPU usage of the "extract" process. `top` shows about 80% CPU time spent, the older version nearly zero.

I'm using the embedded Mongo in combination with Spring Boot 1.5.

Should I provide a minimal reproduction repo?

Edit: OS: Arch Linux, Java 1.8.152 (64bit)

**Comment by Loki-Afro** [comment]
@thetric maybe the compression level is different? Can you verify that?

**Comment by thetric** [comment]
The Mongo archives for the versions 3.2.2, 3.4.10 and 3.6.2 are compressed .tgz files

**Comment by Loki-Afro** [comment]
@thetric of course but the compression rate is interesting ;)

**Comment by Loki-Afro** [comment]
No big difference 
```
zarathustra@freya ~/Downloads % gunzip -l mongodb-*
  compressed uncompressed  ratio uncompressed_name
    86794614    239462400  63.7% mongodb-linux-x86_64-3.4.10.tar
    86708025    250152960  65.3% mongodb-linux-x86_64-3.6.2.tar
   173502639    489615360  64.5% (totals)
zarathustra@freya ~/Downloads % time tar xvf mongodb-linux-x86_64-3.4.10.tgz
x mongodb-linux-x86_64-3.4.10/README
x mongodb-linux-x86_64-3.4.10/THIRD-PARTY-NOTICES
x mongodb-linux-x86_64-3.4.10/MPL-2
x mongodb-linux-x86_64-3.4.10/GNU-AGPL-3.0
x mongodb-linux-x86_64-3.4.10/bin/mongodump
x mongodb-linux-x86_64-3.4.10/bin/mongorestore
x mongodb-linux-x86_64-3.4.10/bin/mongoexport
x mongodb-linux-x86_64-3.4.10/bin/mongoimport
x mongodb-linux-x86_64-3.4.10/bin/mongostat
x mongodb-linux-x86_64-3.4.10/bin/mongotop
x mongodb-linux-x86_64-3.4.10/bin/bsondump
x mongodb-linux-x86_64-3.4.10/bin/mongofiles
x mongodb-linux-x86_64-3.4.10/bin/mongooplog
x mongodb-linux-x86_64-3.4.10/bin/mongoreplay
x mongodb-linux-x86_64-3.4.10/bin/mongoperf
x mongodb-linux-x86_64-3.4.10/bin/mongod
x mongodb-linux-x86_64-3.4.10/bin/mongos
x mongodb-linux-x86_64-3.4.10/bin/mongo
tar xvf mongodb-linux-x86_64-3.4.10.tgz  1.11s user 0.36s system 73% cpu 1.982 total
zarathustra@freya ~/Downloads % time tar xvf mongodb-linux-x86_64-3.6.2.tgz
x mongodb-linux-x86_64-3.6.2/README
x mongodb-linux-x86_64-3.6.2/THIRD-PARTY-NOTICES
x mongodb-linux-x86_64-3.6.2/MPL-2
x mongodb-linux-x86_64-3.6.2/GNU-AGPL-3.0
x mongodb-linux-x86_64-3.6.2/bin/mongodump
x mongodb-linux-x86_64-3.6.2/bin/mongorestore
x mongodb-linux-x86_64-3.6.2/bin/mongoexport
x mongodb-linux-x86_64-3.6.2/bin/mongoimport
x mongodb-linux-x86_64-3.6.2/bin/mongostat
x mongodb-linux-x86_64-3.6.2/bin/mongotop
x mongodb-linux-x86_64-3.6.2/bin/bsondump
x mongodb-linux-x86_64-3.6.2/bin/mongofiles
x mongodb-linux-x86_64-3.6.2/bin/mongoreplay
x mongodb-linux-x86_64-3.6.2/bin/mongoperf
x mongodb-linux-x86_64-3.6.2/bin/mongod
x mongodb-linux-x86_64-3.6.2/bin/mongos
x mongodb-linux-x86_64-3.6.2/bin/mongo
x mongodb-linux-x86_64-3.6.2/bin/install_compass
tar xvf mongodb-linux-x86_64-3.6.2.tgz  1.16s user 0.45s system 81% cpu 1.975 total
```


Is there a difference when using the current version with 3.6 vs the current version with 3.4?

**Comment by thetric** [comment]
@Loki-Afro Can you reproduce this on your machine, too?

**Comment by Loki-Afro** [comment]
@thetric at least not on OSX at the moment

```
public class ExampleTest {
	private static final int PORT = 12345;
	private final IFeatureAwareVersion mongoVersion;
	private MongodExecutable mongodExe;
	private MongodProcess mongod;

	private Mongo mongo;
	private static final String DATABASENAME = "mongo_test";
	private Stopwatch stopwatch;

	public ExampleTest() {
		this.mongoVersion = Version.V3_6_0;
	}

	@Before
	public void setUp() throws Exception {
		stopwatch = Stopwatch.createStarted();
		MongodStarter runtime = MongodStarter.getDefaultInstance();
		mongodExe = runtime.prepare(new MongodConfigBuilder().version(this.mongoVersion).net(new Net(PORT,
				Network.localhostIsIPv6())).build());
		mongod = mongodExe.start();

		mongo = new MongoClient(new ServerAddress(Network.getLocalHost(), PORT));
	}

	@After
	public void tearDown() throws Exception {
		mongod.stop();
		mongodExe.stop();
		stopwatch.stop();

		System.out.println("Took:" + stopwatch.elapsed(TimeUnit.MILLISECONDS) + "ms for " + this.mongoVersion.toString());
	}

	public Mongo getMongo() {
		return mongo;
	}

	@Test
	public void testInsert1() {
		DB db = mongo.getDB("test");
		DBCollection col = db.createCollection("testCol", new BasicDBObject());
		col.save(new BasicDBObject("testDoc", new Date()));
	}
}
```

with `this.mongoVersion = Version.V3_4_3;`or `Version.V3_6_0` the results are around 2200 - 2550 ms of course these tgz are predownloaded.

But if there is an issue it should be visible with this simple test if I got you right

**Comment by Loki-Afro** [comment]
@thetric so can you provide some example with some stats?

**Comment by thetric** [comment]
Oh, I have mistaken the `extractd` process for the extraction process of the Mongo, but it _is_ the Mongo process. Sorry for the confusion.

The real problem for the higher CPU usage seems to be the Mongod flag `--syncdelay=0`. Omitting this flag decreases the system load to the same level as with older Mongo versions.
Why is this flag specified? The [Mongo docs](https://docs.mongodb.com/manual/reference/parameters/#param.syncdelay) don't recommend changing the default value.

For comparison:
```sh
mongod --oplogSize 64 --dbpath /tmp/d --noprealloc --nojournal --port 22222 --syncdelay=0

mongod --oplogSize 64 --dbpath /tmp/d --noprealloc --nojournal --port 22222
```

**Comment by thetric** [comment]
Here some stats for a comparison (measured on a Intel i7 7820HQ, 32 GB mem)

* Linux (`top` cpu time)
  * `--syncdelay=0`: ~80%
  * default syncdelay: <1%
* Windows 10
  * `--syncdelay=0`: ~10% CPU
  * default sync delay: <1%

Perhaps you should drop `Feature.SYNC_DELAY` from `V3_6_0` and `LATEST_NIGHTLY` in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java#L206?

**Comment by Loki-Afro** [comment]
I'll not change the code I did some testing and some unit tests start to fail randomly (because mongodb did not persist the data yet(?) - can't verify)

Take a look here https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/#custom-command-line-options thats how you are able to disable sync delay
