### ISSUE TITLE
Add support for different Linux flavors to enable SSL

### ISSUE THREAD

**Issue by lipnitsk** [flapdoodle-oss/de.flapdoodle.embed.mongo#233]
The Linux binary downloaded by the current code comes from `URL`/linux/mongodb-linux-`32/64bit`-`version`.tgz. Unfortunately that binary does not come compiled with SSL support. Due to different SSL implementations and library names, mongoDb provides the following distro-specific binaries (in 64-bit form only) in addition to the generic `linux` one:
- Amazon Linux
- Debian 7
- Debian 8
- RHEL 6
- RHEL 7
- SUSE 11
- SUSE 12
- Ubuntu 12.04
- Ubuntu 14.04
- Ubuntu 16.04 ARM (for some versions)
- Ubuntu 16.04

Since the distro versions change and are not the same combination for all Mongo releases, it would make sense to make it flexible and dynamically configurable to reduce maintenability issues. I have not found a way to force a particular distro today, is there a way? The only customization API I found was a way to change the base `URL`, not the full download path for a particular version.

**Comment by Loki-Afro** [comment]
hi there, sorry this is not possible.
You would need root access to install those packages.

If you really need on your fancy linux box a mongodb: install it. 
start it before the tests, stop it afterwards or just let it run.

**Comment by lipnitsk** [comment]
Okay, thanks for the quick response. FYI, I think what I need is possible via the `GenericVersion` class.

**Comment by Loki-Afro** [comment]
What exactly do you need? ;)

**Comment by lipnitsk** [comment]
I'm trying to use mongo with SSL enabled (with the [Gradle mongo plugin](https://github.com/sourcemuse/GradleMongoPlugin)). I was able to get around the version issue by using a custom version. I am now trying to find a more graceful way to shutdown mongod when SSL is enabled. `AbstractProcess.stop()` does not seem to work on Windows. On Linux, it works at the last step of `ProcessControl.stopOrDestroyProcess()` (`process.destroy()`), but that is not ideal either, since in that case `waitForProcessGotKilled()` throws an `IllegalStateException`

**Comment by lipnitsk** [comment]
Maybe a method similar to `Mongod.sendShutdown()`, but one that takes an `sslPEMKeyFile` and `sslPEMKeyPassword` can be developed so that an authenticated shutdown command is sent to mongod? Do you think that is feasible and reasonable?

**Comment by Loki-Afro** [comment]
@lipnitsk I guess this is a very special case. Wouldn't it be enough if `de.flapdoodle.embed.mongo.AbstractMongoProcess#sendStopToMongoInstance` is overridable?

**Comment by lipnitsk** [comment]
@Loki-Afro that sounds like it could work? I'm not that familiar with overriding functions pulled in from dependencies (in this case your project is a dependency of gradle mongo plugin, which is in turn a dependency of my project), but if that can be done easily for just that one function then that sounds good. Would you still need to modify the code to make it overridable?

**Comment by lipnitsk** [comment]
Yeah, @roberttaylor426 is very responsive, so shouldn't be too much of a problem. So can I override the existing function in the current embed.mongo 2.0.1 release, or would you still need to change this project?

**Comment by Loki-Afro** [comment]
A change is required, currently that method is final. But you should try it out if it works out for you.

Sorry for the late reply :/
