### ISSUE TITLE
2.0.2-SNAPSHOT not found at repository

### ISSUE THREAD

**Issue by doleron** [flapdoodle-oss/de.flapdoodle.embed.mongo#234]
2.0.2-SNAPSHOT not found at https://oss.sonatype.org/content/repositories/snapshots/de/flapdoodle/embed/de.flapdoodle.embed.mongo/

**Comment by Loki-Afro** [comment]
@matlockx could you please publish a snapshot?

**Comment by matlockx** [comment]
Give me some minutes

**Comment by matlockx** [comment]
https://oss.sonatype.org/content/repositories/snapshots/de/flapdoodle/embed/de.flapdoodle.embed.mongo/2.0.2-SNAPSHOT/

**Comment by doleron** [comment]
Thank you Guys!

**Comment by salexfo** [comment]
Now you get a 404 if you try to access this URL
