### ISSUE TITLE
Unable to use '--archive' with mongodump

### ISSUE THREAD

**Issue by kimside** [flapdoodle-oss/de.flapdoodle.embed.mongo#237]
In MongoDump.java this happens on line 67:

if (config.getArchive() != null) {
         ret.add("--archive");
         ret.add(config.getArchive());
}
This will ignore the fact that the mongodump argument for 'archive' should be
mongodump --archive=[anArchive]

and not
mongodump --archive [anArchive]

causing the dump not to happen at all when using this flag.

**Comment by Loki-Afro** [comment]
Thanks for submitting the issue, will be part of the next release :)
