### ISSUE TITLE
Add toString to GenericFeatureAwareVersion

### ISSUE THREAD

**Issue by philwebb** [flapdoodle-oss/de.flapdoodle.embed.mongo#240]
Would it be possible for `de.flapdoodle.embed.mongo.distribution.Versions.GenericFeatureAwareVersion` to have a `toString` method similar to the one provided by `de.flapdoodle.embed.mongo.distribution.Version`.

**Comment by Loki-Afro** [comment]
@philwebb why not just use `asInDownloadPath` of `IVersion`? Don't want to rely on `toString` methods :/

**Comment by philwebb** [comment]
AFAICT We're not using `toString` directly, it's probably just there to help with logging/debugging. Perhaps @wilkinsona can remember why we added `ToStringFriendlyFeatureAwareVersion` in our own codebase.

There is a bit of a discrepancy as things stand since `Version.V3_6_2.toString()` gives you "Version{3.6.2}" but `GenericFeatureAwareVersion.withFeatures(Version.V3_6_2).toString()` gives you a default Object string value.

**Comment by Loki-Afro** [comment]
@philwebb this is true, adding the `toString` to `GenericFeatureAwareVersion`doesn't harm anyone but you should relay on `asInDownloadPath` ;)
