### ISSUE TITLE
[Question] Docker image for embed mongo?

### ISSUE THREAD

**Issue by kkocel** [flapdoodle-oss/de.flapdoodle.embed.mongo#242]
I would like to ask if there is some publicly available Docker image that allows embed mongo library do be run? I'm asking because I'm running into the same problem as this user: https://stackoverflow.com/questions/49492457/gitlab-pipeline-with-embedded-mongodb

**Comment by Loki-Afro** [comment]
@kkocel to resolve that stackoverflow issue some custom configuration regarding where to store the binaries/tmp files is required but it should run without any problems then I guess. 

A docker container of embed mongo seems pretty useless. If you want mongodb in an docker container well ... use the official mongodb docker container and connect your build container to it.

if I should look into that stackoverflow issue a same Dockerfile with some code would be nice ;)

**Comment by ghostbuster91** [comment]
Hi, 

I just run into the same issue. 
We have a spring application which connects to mongodb. To do that we use docker-compose to easily connect mongoDb container with our spring-app container. The docker file for our spring app is created in a such way that it invokes `build` command which invokes tests under the hood. Obviously our tests don't use any real instance of mongoDb but they spawn an embeded one which fails inside the docker :(. 

Are we doing something wrong?

Here is the docker file:
```
FROM openjdk:8-jdk-alpine as builder

RUN mkdir /workspace
WORKDIR /workspace
ADD gradle /workspace/gradle
ADD src /workspace/src
ADD build.gradle /workspace/build.gradle
ADD gradlew /workspace/gradlew

RUN ./gradlew build

FROM openjdk:8-jdk-alpine

COPY --from=builder /workspace/build/libs/app.jar .

ENTRYPOINT ["java","-jar","app.jar"]
```

**Comment by Loki-Afro** [comment]
@ghostbuster91 @kkocel https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/226 does this resolve the issue? using alpine is always kinda weird never got a single docker image just working out of the box switched to debian or centos as base images ...

**Comment by kkocel** [comment]
Yes, it resolved my issue :)

**Comment by Loki-Afro** [comment]
@kkocel just for the future ... could you post your Dockerfile line which resolved that issue? ;)

**Comment by ghostbuster91** [comment]
It would be very helpful because I wasn't able to fully resolve my problem.

I followe your links @Loki-Afro and managed to install missing `ld-linux-x86-64.so.2` library. But still I got an error message that I am missing some symbols:

```
ldd /root/.embedmongo/extracted/Linux-B64--3.2.2/extractmongod 
        /lib64/ld-linux-x86-64.so.2 (0x7f8018f8b000)
        librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f8018f8b000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f8018f8b000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f8018c39000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f8018f8b000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f8018a27000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f8018f8b000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f8018f8b000)
        ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f8018800000)
Error relocating /root/.embedmongo/extracted/Linux-B64--3.2.2/extractmongod: gnu_get_libc_version: symbol not found
Error relocating /root/.embedmongo/extracted/Linux-B64--3.2.2/extractmongod: __wcstol_internal: symbol not found
Error relocating /root/.embedmongo/extracted/Linux-B64--3.2.2/extractmongod: __sbrk: symbol not found
Error relocating /root/.embedmongo/extracted/Linux-B64--3.2.2/extractmongod: strtoq: symbol not found
Error relocating /root/.embedmongo/extracted/Linux-B64--3.2.2/extractmongod: __register_atfork: symbol not found
Error relocating /root/.embedmongo/extracted/Linux-B64--3.2.2/extractmongod: strtouq: symbol not found
Error relocating /root/.embedmongo/extracted/Linux-B64--3.2.2/extractmongod: backtrace: symbol not found
```

Switching to https://hub.docker.com/r/frolvlad/alpine-oraclejdk8/ doesn't work neither.

**Comment by ghostbuster91** [comment]
Using `openjdk:8` as a base image solved my problem.

**Comment by Loki-Afro** [comment]
@ghostbuster91 which is not based on alpine ... ;)
