### ISSUE TITLE
Cannot apply schema (unknown top level operator: $jsonSchema)

### ISSUE THREAD

**Issue by tom4s-0** [flapdoodle-oss/de.flapdoodle.embed.mongo#245]
String commandBody = resource("schema_file.json")
    Jongo jongo = new Jongo(DB)
    jongo.runCommand(commandBody).throwOnError().as(Object.class)

is throwing

     com.mongodb.MongoCommandException: Command failed with error 2: 'unknown top level operator: $jsonSchema' on server localhost:port_number. The full response is { "ok" : 0.0, "errmsg" : "unknown top level operator: $jsonSchema", "code" : 2 }

If Mongo 3.6 is used, this error shouldn't be happening. Has anyone been able to successfully apply schema?

**Comment by Loki-Afro** [comment]
@tom4s-0 what is Jongo ...?

**Comment by tom4s-0** [comment]
@Loki-Afro http://jongo.org/

**Comment by Loki-Afro** [comment]
@tom4s-0 https://stackoverflow.com/a/33595614/1248724 ... there are many erros like this in google and I don't know what jongo does there ... qhy don't you open an issue in the jongo issue tracker?

**Comment by tom4s-0** [comment]
@Loki-Afro It is not related to Jongo. I think issues like the one described above in SO are often caused by Mongodb version a person uses. Also, I use exactly the same method to apply schema on real Mongo database, and it works fine, so it really doesn't seem like a Jongo problem. This error makes me think `de.flapdoodle.embed.mongo` might be using lower Mongodb version than 3.6. And schema validations were introduced only in 3.6.

**Comment by tom4s-0** [comment]
@Loki-Afro Have you ever been able to apply schema validation on embedded db?

**Comment by tom4s-0** [comment]
@Loki-Afro Have you ever been able to apply schema validation on embedded db?

**Comment by Loki-Afro** [comment]
@tom4s-0 I never tried out mongodb schema validation in any scenario.

Can you please write a simple Unit test which demonstrates the issue you are facing - if possible without Jango?
