### ISSUE TITLE
Allow process output control through MongosSystemForTestFactory

### ISSUE THREAD

**Issue by mp911de** [flapdoodle-oss/de.flapdoodle.embed.mongo#250]
It would be great to configure process output behavior through `MongosSystemForTestFactory` for the individual processes. In our case, we want to conditionally stream output/disable output within our tests. Introducing a `Function<IMongodConfig, ProcessOutput>` or `Function<Command, ProcessOutput>` would be a great way to achieve that.

**Comment by michaelmosmann** [comment]
@mp911de solved after a bigger refactoring -> https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/tree/embed-mongo-4.x
