### ISSUE TITLE
Used embedded mongodb in production

### ISSUE THREAD

**Issue by npierreyves** [flapdoodle-oss/de.flapdoodle.embed.mongo#254]
I would like to know if it is possible to define a different directory for the download / use of mongo.
Indeed, I wish to use mongo embedded in production ? 
I want to define a folder or install it from mongoembedded will already exist to avoid the download phase that will not be possible from the production server.

Thank for you help ;)

**Comment by Loki-Afro** [comment]
@npierreyves 

Different Artifact location ? https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-artifact-storage

I would not recommend using embed mongo as a production mongo replacement at all. Use docker or better a dedicated server/cluster. And seriously running a production database without a decent backup and not even a fail over strategy? ....

**Comment by torsten-liermann** [comment]
I also use embedded mongo in production. "Production" is a fearsome term. But in my case it is a small installation on site. Virtualization is out of the question. A spring-boot application launches MongoDB embedded, exposing only a search interface publicly and indexing metadata. If this application is terminated, the MongoDB process must also be terminated. Backup is not required because the indexing process is repeatable.

**Comment by Loki-Afro** [comment]
@npierreyves https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#custom-database-directory this may help

**Comment by npierreyves** [comment]
Sorry i edit my previous post ;)
I tried to set a custom database directory (springboot : spring.mongodb.embedded.storage.database-dir who set "new Storage(this.embeddedProperties.getStorage().getDatabaseDir()" but collection is empty after application reboot !

**Comment by Loki-Afro** [comment]
@npierreyves then I suggest looking into the spring boot code, the snippet mentioned above works, try it out. ;)

**Comment by npierreyves** [comment]
Hello and thank for your previous reply

I keep looking at my data problem that disappears at each startup and I realized that I have the following messages:
"Unclean shutdown ... mongod.lock is not empty"
"Dropping unused ident: Collection ..."
"Dropping unused ident: index ..."

I understand that apparently the base stops badly .. but how can I make it stop properly when closing my application?

**Comment by Loki-Afro** [comment]
@torsten-liermann may you sahre your spring boot hacks to get this working? ;)
