### ISSUE TITLE
Mongo versions (many 3.6 versions right now) don't always work because versions are whitelisted in Version.java

### ISSUE THREAD

**Issue by glajchs** [flapdoodle-oss/de.flapdoodle.embed.mongo#255]
Right now, in Version.java `https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java`, specific versions are called out.  As new versions get introduced, they aren't always added to this list, or even if they are, they take time to propagate through the release cycle of this repo, and then through the release cycle of other places where this plugin is used (in our case, maven central).  The result is that the latest versions supported right now in the 2.0.3 version in maven central are 3.6.0 and 3.6.2.  We're trying to use 3.6.5, and the version doesn't match exactly.

Can you change this to look for the "latest version below the number specified"?  So if we use 3.6.5, it will downgrade to using the config found in the 3.6.2 version.

Right now this is manifesting itself because I can download the 3.6.5 version, but it won't start, because it's not grabbing the param overrides that exist in 3.6.2 in Version.java, namely the one to omit --nohttpinterface.  Because of this, mongo won't start because this option is passed, and is not allowed in 3.6.x.

**Comment by Loki-Afro** [comment]
@glajchs I prefer to have the exact version specified and now black magic auto downgrading version if not defined. This would lead to not reproducible builds.

I would also suggest that you abstract away some kind of JUnit rule or Factory with a version specified for your application, adding there a GenericVersion with with the same parameters as with the previous version should mostly work. 

In case of 3.6.5 you can look it up here https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java and use it like here https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#custom-version

**Comment by glajchs** [comment]
In this case we're using a plugin that in turn uses your plugin, so a direct override is harder.
Once you get a new release out the door (2.0.4) with the 3.6.5 version specified, we can ingest that pretty easily.  For the time being, I'll try to suggest the "black magic" style of fix into that repository to see if they are more amenable to the idea.
`https://github.com/joelittlejohn/embedmongo-maven-plugin/blob/master/src/main/java/com/github/joelittlejohn/embedmongo/AbstractEmbeddedMongoMojo.java#L108`

As for your argument about it leading to not reproducible builds, you might want to consider special casing versions later than the latest defined.  i.e. not let people specify unknown old versions, but at least let them try versions newer than are defined.  This would give you some breathing room each time a point release of mongo comes out until you can get your release with the matching version numbers out.

**Comment by Loki-Afro** [comment]
@glajchs well sprint boot does this well I guess ... you may look at their code too?

**Comment by joelittlejohn** [comment]
If I understand @glajchs correctly, the suggestion here is to use the newest known set of arguments, _iff_ the version specified is greater than the newest known version. I don't actually see how this would lead to no-reproducible builds. Maybe I've missed something, or I'm maybe not understanding @glajchs suggestion.

For a reproducible build, the de.flapdoodle.embed.mongo version will be fixed, so the last known version and last known set of arguments is fixed, and the mongo version will be fixed (by me). Which part is dynamic?

**Comment by glajchs** [comment]
Yep, I tried to implement the black magic in the library above this, and all I was lacking was a getter on getFeatures, which even if you use Version instead of IFeatureAwareVersion, is currently private without any getters.

**Comment by Loki-Afro** [comment]
@glajchs well if that's all you need :) - done
