### ISSUE TITLE
Very slow on new Versions

### ISSUE THREAD

**Issue by tosi88** [flapdoodle-oss/de.flapdoodle.embed.mongo#260]
Hey,

I have played around with:
https://github.com/springframeworkguru/spring-boot-mongodb/tree/embeded_mongodb

a little bit. Especially since there was an old version of flapdoodle used in the mvn (1.50.5) I updated the dependency to 2.1.1 and rerun the application. 

With v. 1.50.5: It took around 5-6 seconds for start-up.
With v. 2.1.1: It took around 50 seconds, even after several restart (downgrading to 1.50.5 lets it start in 5 seconds again).

I am running Java 8 on a mac book...

Is this a known issue and can it be improved? I guess it might have something to do with the storage enginge changes between the version, but not sure. 

Thanks and best
tos

**Comment by Loki-Afro** [comment]
@TobiasAtSovanta consider updating to the current version of spring boot first. Should not have a big impact but to avoid any other circumstances.
I'm not familiar with the current spring boot setup but this looks promising https://www.baeldung.com/spring-boot-embedded-mongodb (July 2018)

Then what version of mongodb do you try to run?

**Comment by tosi88** [comment]
Hey, 

thanks for the quick response. Spring Boot version does not matter, updating to the current 2.0.4.RELEASE still results in poor startup time.
The MongoDB version that is printed to the console on startup is: db version v3.2.2.  Change this to a new one 3.6.5, but still very slow on startup... Even without using the dependency  

        <dependency>
            <groupId>cz.jirutka.spring</groupId>
            <artifactId>embedmongo-spring</artifactId>
            <version>RELEASE</version>
        </dependency>

the startup performance was slow... any ideas left?

**Comment by Loki-Afro** [comment]
@tosi88 take a look here https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/166

Can you verify that with `mmapv1`everything is fast again?

**Comment by juanplopes** [comment]
I'm having the same problem. I use embedded mongo for a suite of 47 unit tests that used to run in 800ms with 1.50 and now it's taking 12 seconds. I tried changing the storage engine, but it's still slow.

**Comment by matlockx** [comment]
I'm gonna look into that too. Thanks for pointing out

**Comment by Loki-Afro** [comment]
@tosi88 could you share your full project?

What mac os version you are using?

**Comment by tosi88** [comment]
Hey, 
thanks for confirming the behavior @juanplopes 👍  and @matlockx for having a look at it :). Concerning the your questions @Loki-Afro 
- My mac-version is: 10.13.4  High Sierra. 
- The full project is exactly the one from the git-hub link I posted initially - I in fact only changed the flapdoodle version to provoke the issue.

**Comment by Loki-Afro** [comment]
1. using the repository from the first post
https://github.com/springframeworkguru/spring-boot-mongodb/tree/embeded_mongodb

and adding 

```
		<dependency>
			<groupId>de.flapdoodle.embed</groupId>
			<artifactId>de.flapdoodle.embed.mongo</artifactId>
			<scope>test</scope>
		</dependency>
````
**will result in version 2.0.3 NOT 1.50.5** with mongodb version v3.2.2
2. with the test result of 1. on my mac (10.13.6, i5 with 2,3 GHz, java 8 update 181) 
The test (which actually checks if all the wiring work) runs in Intellij in around 100ms after it downloaded the first time the mongodb binary files.

via mvn test the actually test phase took around 4s because some other spring maven plugin is doing a bit more.
 
By actually placing a breakpoint in `guru.springframework.SpringBootMongodbApplicationTests#contextLoads` one can grab the random generated port of the new running mongodb and connect to it from elsewhere

To check if weirdTiger is enabled or not one could issue this command:

````
zarathustra@hel ~ % mongo localhost:53597                                                                                                                                                             
MongoDB shell version v4.0.1
connecting to: mongodb://localhost:53597/test
MongoDB server version: 3.2.2
WARNING: shell and server versions do not match
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        http://docs.mongodb.org/
Questions? Try the support group
        http://groups.google.com/group/mongodb-user
> db.serverStatus().storageEngine
{ "name" : "wiredTiger", "supportsCommittedReads" : true }
```

3. 
updating from 2.0.3 to 2.1.1 by declaring the following dependency
```
		<dependency>
			<groupId>de.flapdoodle.embed</groupId>
			<artifactId>de.flapdoodle.embed.mongo</artifactId>
			<version>2.1.1</version>
			<scope>test</scope>
		</dependency>
```
results in a test time of around 110 ms so not a real difference yet.
4.
- based on 3., so with 2.1.1
to use mongodb version 3.6.5 the most convenient way is by changing the `application.properties`
in `spring-boot-mongodb/src/main/resources/application.properties`
one has to add 2 things here
```
# your point to debug whats going on is right here: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoProperties
# to get the right version
spring.mongodb.embedded.version=3.6.5
# enable the features, see https://github.com/spring-projects/spring-boot/issues/12575 to get more info on that
spring.mongodb.embedded.features=[sync_delay","storage_engine","only_64bit","no_chunksize_arg","mongos_configdb_set_style","no_http_interface_arg","only_with_ssl","only_windows_2008_server","no_solaris_support","no_bind_ip_to_localhost]
```
And what do I get? An actual test time of around 110 ms with weird tiger enabled
as one can see here
```
zarathustra@hel ~ % mongo localhost:54289
MongoDB shell version v4.0.1
connecting to: mongodb://localhost:54289/test
MongoDB server version: 3.6.5
WARNING: shell and server versions do not match
> db.serverStatus().storageEngine
{
        "name" : "wiredTiger",
        "supportsCommittedReads" : true,
        "readOnly" : false,
        "persistent" : true
}
```
4. the following dependency has nothing to do at all with this project, neither the one I referenced in 1. (take a look in the effective pom)
```
   <dependency>
        <groupId>cz.jirutka.spring</groupId>
        <artifactId>embedmongo-spring</artifactId>
        <version>RELEASE</version>
    </dependency>
```
based on what I found in some old tutorials this way necessary before spring boot integrated embed mongo itself- so no need for that at all anymore.

What am I missing? An actual test probably. 
So what is going on in your tests? Can you post some here please?

**Comment by tosi88** [comment]
Hey,

thanks for point out 4. - didn't know that it has been integrated as part of spring mongo iteself.
concerning1: 
The dependency:
        <dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo</artifactId>
            <version>1.50.5</version>
        </dependency>
has already been in the pom.xml. Hope you found it - I did not change anything there.

I was not talking about test performance (as juanplopes), but about the actuall startup of the project:

Attached the start-up log with version 2.1.1 and v 1.50.5 as well as more detailed system information
<img width="264" alt="screen shot 2018-08-11 at 15 40 23" src="https://user-images.githubusercontent.com/21080529/43992248-ef84d886-9d7c-11e8-8a1e-7216b8916cd2.png">

[1_50_5.txt](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/files/2280273/1_50_5.txt)
[2_1_1.txt](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/files/2280274/2_1_1.txt)

**Comment by Loki-Afro** [comment]
@tosi88 regarding 1. I looked again in the pom and yes there it is 
```
<dependency>
 <groupId>de.flapdoodle.embed</groupId>
  <artifactId>de.flapdoodle.embed.mongo</artifactId>
  <version>1.50.5</version>
 </dependency>
```
**which is just wrong.** I pulled the master and made my tests again ist and there is no such dependency ;)

**Comment by tosi88** [comment]
Thanks a lot - great :) :) :)
Did the following things:
- specified the right dependency - i.e. pulling the master of the flapdoodle project
- removed the unneccessary cz.jirutka.spring dependency (did not know that spring boot has the embedded mongoDB feature already build-in - thanks for pointing this out!)

Tried to set:
- spring.mongodb.embedded.version=3.6.5 in the application properties however lead to 403 when trying to download the corresponding version from mongodb. But this is not an issue that seems to be on your responsibility :). 

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-3.6.5.tgz

**Comment by tosi88** [comment]
Hey @Loki-Afro,

thanks now it works.
Would not have expected that features means error handling, did not get the point from the git-hub issue link... Can even use mdb version 4.0.1 now 🥇 :).

**Comment by Loki-Afro** [comment]
@tosi88 well you could but haven't tested 4.x yet ;)

**Comment by bguerout** [comment]
You should use `ephemeralForTest` . 

See https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/166#issuecomment-425586048 for more informations
