### ISSUE TITLE
MongoDB 4.0

### ISSUE THREAD

**Issue by ThePinkPanther** [flapdoodle-oss/de.flapdoodle.embed.mongo#261]
Would like to have mongo 4 support to be able to test transactions

**Comment by Loki-Afro** [comment]
@ThePinkPanther keep in mind that you can define 4.x yourself
```
		EnumSet<Feature> features = Version.Main.PRODUCTION.getFeatures();
		IFeatureAwareVersion iFeatureAwareVersion = Versions.withFeatures(new GenericVersion("4.0.2"), features);
```

**Comment by faizan-talena** [comment]
@Loki-Afro When should we expect 2.1.2 release. I would love to upgrade to mongo 4.
