### ISSUE TITLE
What's the default location of the downloaded mongo?

### ISSUE THREAD

**Issue by challarao** [flapdoodle-oss/de.flapdoodle.embed.mongo#263]
What is the default location of the downloaded embedded mongo?

If it's already downloaded, say for a example for a unit test, does it download it again? How does flapdoodle knows if it exists or not?

Thank you

**Comment by Loki-Afro** [comment]
Binaries get downloaded and extracted in your home directory

```
zarathustra@hel ~ % tree .embedmongo
.embedmongo
├── extracted
│   ├── OS_X-B64--3.2.2
│   │   └── extractmongod
│   └── OS_X-B64--3.6.5
│       └── extractmongod
└── osx
    ├── mongodb-osx-ssl-x86_64-3.6.5.tgz
    └── mongodb-osx-x86_64-3.2.2.tgz

4 directories, 4 files
```

How does it know if it needs to download something?
Basically it looks for the existence of the archive 😉
