### ISSUE TITLE
question: how to disable embedded mongo for certain tests

### ISSUE THREAD

**Issue by dermoritz** [flapdoodle-oss/de.flapdoodle.embed.mongo#264]
i got no answer here: https://stackoverflow.com/questions/52604062/how-to-disable-flapdoodle-embedded-mongodb-in-certain-tests

I just added "testCompile('de.flapdoodle.embed:de.flapdoodle.embed.mongo:2.1.1')" to my test and now in all tests the embedded mongo is magically used, but how to easily disable embedded mongo for a given test class? (i guess i have to exclude a single class from discovering?!)

**Comment by Loki-Afro** [comment]
@dermoritz this is a spring related issue, please open an issue there and link it here, sorry for the inconvenience

**Comment by dermoritz** [comment]
Sorry but i am not completely understanding the mechanics - how embedded mongo is started by spring. How it is supposed to work? What issue to fix?
To what part of Spring is this related?

**Comment by Loki-Afro** [comment]
`To what part of Spring is this related?`
AFAIK adding this dependency causes spring **boot** to launch an mongodb for each test

**Comment by d3minem** [comment]
**Do we have any update on this issue?** It's really cumbersome for some tests now to have `de.flapdoodle.embed.mongo` by default. Another issue with `flapdoodle` connection **timeouts** - [Issue 276](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/276)

```
<dependency>
     <groupId>de.flapdoodle.embed</groupId>
     <artifactId>de.flapdoodle.embed.mongo</artifactId>
     <version>2.2.0</version>
</dependency>
```
