### ISSUE TITLE
de.flapdoodle.embed.process.runtime.Starter shouldn't log full exception and rethrow

### ISSUE THREAD

**Issue by ogerardin** [flapdoodle-oss/de.flapdoodle.embed.mongo#266]
Context: I need to try to prepare a Mongo executable using a specific configuration, and if it fails try with another configuration. I'm using de.flapdoodle.embed.mongo:2.1.1/de.flapdoodle.embed.process:2.0.5

If I call `de.flapdoodle.embed.process.runtime.Starter#prepare` and it fails for some reason, a `DistributionException` is raised, which I can catch and then try with my second configuration. This is good. 

The problem is: before throwing the exception a full stack trace is logged... I'd like to avoid that, as it pollutes the log with an error which is not fatal, and is contrary to the principle that you should not both log a full stack trace AND throw an exception. 

What I would do is change line 68 of de.flapdoodle.embed.process.runtime.Starter.java from:
			`logger.error(messageOnException, iox);`
to:
			`logger.error(messageOnException + ": " +  iox.toString());`

This way you still get the error in the log, but not the stack trace, and if the exception isn't caught it will eventually generate a full stack trace.

**Comment by Loki-Afro** [comment]
changed it in https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/commit/9aa0234dbd75df227a3d73af3d103a59769222aa

so it will be part of de.flapdoodle.embed.process:2.0.6

but don't ask me when it get released

in the meantime you can disable that specific logger if you want to ;)

**Comment by ogerardin** [comment]
Perfect! When will it be released? (just kidding)

Disabling the logger will work for now :)
