### ISSUE TITLE
Creation of @Bean of ReactiveMongoOperations with embedded mongoDB 4 and replicaset

### ISSUE THREAD

**Issue by vivekkalirawana** [flapdoodle-oss/de.flapdoodle.embed.mongo#272]
In our service, we are having method that use ReactiveMongoOperations with transaction.
The application is working fine with mongoDB with replicaset.
To create test cases for these methods with embedded mongodb, we need to create @Bean of ReactiveMongoOperations.
As per feedback #257 , we are able to create MongoTemplate with replica set but it is not supporting Reactive (ReactiveMongoOperations).

Snippet of code of service:
@Autowired
private ReactiveMongoOperations mongoOperations;
public Mono<Movement> createBookRequestWithTransaction(Movement movement)
{
	return mongoOperations.inTransaction().execute(action -> {
		return action.save(movement);
	}).next();
}

Snippet to create @Bean for MongoTemplate:

		private MongoTemplate mongoTemplate;
		private MongoClient mongo;
		private MongodProcess node1Mongod;
		private MongodExecutable mongodExecutable;		
		@Bean 
        public MongoTemplate reactiveMongoTemplate() throws Exception{
        MongodStarter runtime = MongodStarter.getDefaultInstance();
			int node1Port = 27017;
            EnumSet<Feature> features = Version.Main.PRODUCTION.getFeatures();
            IFeatureAwareVersion iFeatureAwareVersion = Versions.withFeatures(new GenericVersion("4.0.2"), features);

            mongodExecutable = runtime.prepare(new MongodConfigBuilder().version(iFeatureAwareVersion)
                                                                  .withLaunchArgument("--replSet", "rs0")
                                                                  .cmdOptions(new MongoCmdOptionsBuilder().useNoJournal(false).build())
                                                                  .net(new Net(node1Port, Network.localhostIsIPv6())).build());
            node1Mongod = mongodExecutable.start();
            mongo = new MongoClient(new ServerAddress(Network.getLocalHost(), node1Port));
            MongoDatabase adminDatabase = mongo.getDatabase("admin");

            Document config = new Document("_id", "rs0");
            BasicDBList members = new BasicDBList();
            members.add(new Document("_id", 0)
                                .append("host", "localhost:" + node1Port));
            config.put("members", members);
            adminDatabase.runCommand(new Document("replSetInitiate", config));
            System.out.println(">>>>>>>>" + adminDatabase.runCommand(new Document("replSetGetStatus", 1)));
            return new MongoTemplate(mongo, "test");
		}

Kindly provide support to create @Bean of ReactiveMongoOperations with embedded mongodb 4 (replicaset).
Other feedbacks are also welcome

**Comment by Loki-Afro** [comment]
`ReactiveMongoOperations` ... this is some "new" spring stuff to me.

If you are using Spring boot for spring embedded mongo stuff - it is an issue there.

If not: this library does not give any spring support what so ever so you should write your own Bean to provide a `ReactiveMongoOperations` implementation, I guess very similar to the `MongoTemplate` one
