### ISSUE TITLE
is there a place to read how flapdoodle works (besides reading the code)?

### ISSUE THREAD

**Issue by OhadR** [flapdoodle-oss/de.flapdoodle.embed.mongo#275]

**Comment by Loki-Afro** [comment]
Well .. the Readme? ;) https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo

What exactly are you looking for?

The basic concept is:
- download mongodb (and cache it)
- extract it (and cache it)
- java uses its process api to start and monitor  the mongo process
- you run your tests
- java kills the mongo process

**Comment by OhadR** [comment]
thanks for the answer! I looked at the README, but could not find there the info you wrote... :) thanks!
so is there a "real" mongo running on my localhost when the tests are running? if my system runs with a single-node-mongo on the localhost (not a replica-set), then flapdoodle runs a mongo upon tests, so it is exactly the same as a "production" run, right?

**Comment by Loki-Afro** [comment]
> so is there a "real" mongo running on my localhost when the tests are running?
yes

> is exactly the same as a "production" run, right?
You can configure it to your needs, to get as close as you want. 
Mostly one does not want to test the setup but the overall integration and some crazy queries

**Comment by OhadR** [comment]
thanks!

**Comment by OhadR** [comment]
by the way, this could be a great add to the readme :)

- "download mongodb (and cache it)
- extract it (and cache it)
- java uses its process api to start and monitor the mongo process
- you run your tests
- java kills the mongo process"
