### ISSUE TITLE
Proxy settings do not work when downloading version 3.5.5 

### ISSUE THREAD

**Issue by hakangurrr** [flapdoodle-oss/de.flapdoodle.embed.mongo#279]
I'm unable to get version 3.5.x to download with my proxy configuration.
I have created Mongodb Cofiguration beans in test class as follows:
```
@Bean
  public MongodStarter mongodStarter() {
    IRuntimeConfig runtimeConfig = new RuntimeConfigBuilder()
        .defaults(Command.MongoD)
        .artifactStore(new ExtractedArtifactStoreBuilder()
            .defaults(Command.MongoD)
            .download(new DownloadConfigBuilder()
                .defaultsForCommand(Command.MongoD)
        .proxyFactory(new HttpProxyFactory("proxy address", portNumber))))
        .build();
    return MongodStarter.getInstance(runtimeConfig);

  }

  @Bean
  public MongoClient mongoClient() {
    return new MongoClient("localhost", 12345);
  }

  @Bean
  public MongoDbFactory mongoDbFactory() throws IOException {
    if (mongodExecutable == null) {
      log.info("trying to start local mock mongodb...");
      mongodExecutable = mongodStarter().prepare(
          new MongodConfigBuilder()
              .version(Versions.withFeatures(new GenericVersion("4.0.7"), Feature.SYNC_DELAY, Feature.NO_HTTP_INTERFACE_ARG, Feature.ONLY_WITH_SSL))
              .net(new Net("localhost", 12345, Network.localhostIsIPv6())).build());
      mongodProcess = mongodExecutable.start();
    }
    return new SimpleMongoDbFactory(mongoClient(), "contracts");
  }

  @Bean
  public MongoTemplate mongoTemplate(MongoDbFactory mongoDbFactory) {
    return new MongoTemplate(mongoDbFactory);
  }


```
And successfully downloaded 4.0.7 version via proxy settings but also Flapdoodle trying to install version 3.5.x so failed to load ApplicationContext.

**Comment by rsercano** [comment]
+1

**Comment by rsercano** [comment]
Is anybody around here ????

**Comment by Loki-Afro** [comment]
Try setting the jvm proxy stuff instead

**Comment by SvSergey** [comment]
And why also Flapdoodle trying to additionally install version 3.5.5, even  in configuration specified only version 4.x? 
It downloads two archives: mongodb-win32-x86_64-2008plus-ssl-**4.0.12**.zip (we can configure download url for it through DownloadConfigBuilder) and mongodb-win32-x86_64-**3.5.5**.zip (and we can't configure download url for it!) 
@Loki-Afro Can you explain this behavior?

**Comment by Loki-Afro** [comment]
@SvSergey sounds like a strange issue, but not related to this one at all.

You can file a new issue with a code example and we can look into it

**Comment by SvSergey** [comment]
@Loki-Afro , I think its related, because in original problem:

> And successfully downloaded 4.0.7 version via proxy settings but **also Flapdoodle trying to install version 3.5.x** so failed to load ApplicationContext.
> 
I think the main problem of this issue is:

> It downloads two archives: mongodb-win32-x86_64-2008plus-ssl-4.0.12.zip (we can configure download url for it through DownloadConfigBuilder) and mongodb-win32-x86_64-3.5.5.zip (**and we can't configure download url for it!**)
>

**Comment by Loki-Afro** [comment]
@SvSergey got your point - chances are high for a spring misconfiguration / dependency madness.

Never play around with http proxies before :/ but I'm pretty sure it has nothing to do with proxies.

can you create a full project and push it to github so i can investigate further?

**Comment by SvSergey** [comment]
@Loki-Afro, you are right and it seems that I found the problem - **SpringBoot**, class **org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoProperties**:
`private String version = "3.5.5";`
To avoid installing version 3.5.5 we can add exclusion for this class to application:
`@SpringBootApplication(exclude = EmbeddedMongoAutoConfiguration.class)`

@Loki-Afro , thanks for idea!
