### ISSUE TITLE
Leaking mongod process when JVM is killed

### ISSUE THREAD

**Issue by yarinm** [flapdoodle-oss/de.flapdoodle.embed.mongo#282]
Hey,

I've started running embedded mongo for my UTs in jenkins and if the jenkins job gets aborted it interrupts the JVM with SIGKILL, causing the JVM to shutdown immediately. Shutdown hooks won't be called the mongod process stays alive. 

I couldn't find a work around  through flap doodle API for this.

I think the mongod process should be invoked using an intermediate process that checks if its parent pid has changed to 1 (meaning his parent died). In case that happens it should kill itself and signals mongod to shutdown using SIGTERM.

WDYT?

**Comment by Loki-Afro** [comment]
You are kinda right. 
But there is a shutdown hook. I guess it just don't get executed - are you running your tests with maven?

**Comment by yarinm** [comment]
Yeah, shutdown hooks are not guaranteed when dealing with SIGKILL, only SIGINT/SIGTERM

Running tests with maven, I'm using the latest of flapdoodle with mongo 3.6.12 enterprise edition (For the inMemory storage engine)

**Comment by Loki-Afro** [comment]
Can't find the issue now :/ but it all boiled down to that this is some kinda maven issue - but i guess and this depends on your maven config is some kinda hackable with some surefire/failsafe plugin configuration

some considerations
- is the jvm forked?
- if so how do shutdown hook calls get delegated?
- does it work outside of jenkins and sending the jvm a SIGTERM?

I know this all seems to work with small stuff - but sometimes its a bit more magic ...

**Comment by yarinm** [comment]
This has nothing to do with maven.

Even running the UTs using intellij and killing the process using SIGKILL reproduces this.

If I send a SIGTERM the process and the mongod subprocess shutdown properly. Like I said shutdown hook will most likely not work in SIGKILL scenario as the JVM forcibly destroying the process and its not waiting for the shutdown hook to trigger.

**Comment by Loki-Afro** [comment]
i overlooked that Jenkins uses SIGKILL to abort a job.
But I think that jenkins sends SIGTERM which is also described here https://wiki.jenkins.io/display/JENKINS/Aborting+a+build

so then why does your JVM receive a SIGKILL?

**Comment by yarinm** [comment]
Hmm, interesting. I'll have to a closer look there when I get to the office next week.
It might also be related to surefire forking the process which prevents jenkins from sending sigterm to the subprocess of the forked process. I'll have to check.

**Comment by yarinm** [comment]
You were right and surefire forking the JVM was the root cause here. I changed the shutdown option to "exit" and that solved my issue.

More can be read about it [here](https://maven.apache.org/surefire/maven-surefire-plugin/examples/shutdown.html)

Note that if you still kill the JVM with SIGKILL the mongod process will still be leaked. And I think there should be a solution for it within the framework.

**Comment by Loki-Afro** [comment]
any idea how?

you should never call SIGKILL first, always use INT or SIGTERM though ...

don't think this is possible to handle :/

**Comment by yarinm** [comment]
Before finding this solution the way I solved it was by spawning an additional subprocess.
That subprocess was a simple python script that checks if its parent pid has changed to 1, meaning its parent has died. Once it detects he is an orphan, it would send SIGTERM to the mongod process.

I believe this solution could be implemented as an intermediate process for running mongod or like I did as different subprocess.

There are some other methods to detect that the parent process has died in this [thread](https://stackoverflow.com/questions/269494/how-can-i-cause-a-child-process-to-exit-when-the-parent-does). 

WDYT?

**Comment by Loki-Afro** [comment]
sounds like a OS specific hack.

especially this one sounds funny https://stackoverflow.com/a/33676140/1248724 would be cool to try out - but again no laptop here for a while ;)

you can try to create a PR for the process lib, the relevant code is [here](https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/tree/process-2.x.x) in branch process-2.x.x

but I don't consider this as bug its more a new feature. so I'm closing this issue here.

Takeaways:
- do not call SIGKILL, always try SIGTERM or SIGIN to get a clean shutdown
- if you are using surefire/failsafe take a look [https://maven.apache.org/surefire/maven-surefire-plugin/examples/shutdown.html](here) first
- if this is something that happens regularly to you for what ever reason think about running your tests in a container and remove/stop it afterwards
