### ISSUE TITLE
Wrong version (2.2.1) mentioned in documentation

### ISSUE THREAD

**Issue by Research2Go** [flapdoodle-oss/de.flapdoodle.embed.mongo#283]
I've just tried to get the latest version of your library and I've found out that there are discrepancy between what you have in github, in 
https://search.maven.org/search?q=de.flapdoodle.embed.mongo

Which version should I use as the latest stable version? 2.2.1 as shown your maven example doesn't exist at all.

**Comment by Loki-Afro** [comment]
the maven example shows a snapshot version not a release.

2.2.0 is the latest release version.
