### ISSUE TITLE
Attempt to use a decimal BSON type when experimental decimal server support is not currently enabled.

### ISSUE THREAD

**Issue by Research2Go** [flapdoodle-oss/de.flapdoodle.embed.mongo#284]
Dear all, 

I'm facing an issue using version 1.50.5 as shown at the end of the post. 
I thought it might be some outdated old version issue, so I tried to use 2.2.0 version in Maven. However, after I changed that in my maven dependency, the project can't build due to unresolvable IMongodConfig etc. 

Following are the original problem I face before switching to 2.2.0. 
**Does anyone have any ideas what is the problem behind this error message?** 

1. pom.xml
	<dependency> 
		  <groupId>de.flapdoodle.embed</groupId>
		  <artifactId>de.flapdoodle.embed.mongo</artifactId>
		  <version>1.50.5</version>
                  
        </dependency>

2. Bean
I'm using springboot to use embedded mongodb if the external mongodb is not running. Here is my bean. 

        private MongodExecutable  mongodServer;
        ......
`@Bean(name = "MongodExecutable", initMethod = "start", destroyMethod = "stop")
	public MongodExecutable  embeddedMongoServer()
			throws IOException {
		
			IMongodConfig  mongodConfig = new MongodConfigBuilder()
					.version(Version.Main.PRODUCTION)
		            .net(new Net(mongoProperties.getPort(), Network.localhostIsIPv6()))
		            .build();
			MongodStarter mongodStarter = MongodStarter.getDefaultInstance();
			mongodServer =  mongodStarter.prepare(mongodConfig);
                        return mongodServer;
	}`
	

3. I'm storing decimal numbers in my tests and it works with external mongodb without any error, however, if I switch to embedded one, I have the following error: 

2019-05-03T23:46:14.082+0200 I -        [conn21] Assertion: 10307:Client Error: bad object in message: Attempt to use a decimal BSON type when experimental decimal server support is not currently enabled.
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    index_collator_extension+0x182593
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    index_collator_extension+0x14a9e4
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    index_collator_extension+0x13ef81
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    index_collator_extension+0x13ee83
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    ???
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    ???
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    ???
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    ???
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    index_collator_extension+0x66d4ce
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    index_collator_extension+0x153f0e
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    ???
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    index_collator_extension+0x670c1c
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    index_collator_extension+0x69ecbb
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] extract-4858fb8c-dbc7-4f2b-b0ef-ff6615187436extractmongod.exe    index_collator_extension+0x69ee62
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] kernel32.dll                                                     BaseThreadInitThunk+0xd
[mongod output] 2019-05-03T23:46:14.123+0200 I CONTROL  [conn21] 
[mongod output] 2019-05-03T23:46:14.123+0200 I NETWORK  [conn21] AssertionException handling request, closing client connection: 10307 Client Error: bad object in message: Attempt to use a decimal BSON type when experimental decimal server support is not currently enabled.
[mongod output] 2019-05-03 23:46:14.123  WARN 12112 --- [           main] org.mongodb.driver.connection            : Got socket exception on connection [connectionId{localValue:11, serverValue:21}] to localhost:27017. All connections to localhost:27017 will be closed.
2019-05-03 23:46:14.124  INFO 12112 --- [           main] org.mongodb.driver.connection            : Closed connection [connectionId{localValue:11, serverValue:21}] to localhost:27017 because there was a socket exception raised by this connection.
2019-05-03 23:46:14.138  INFO 12112 --- [      Thread-25] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@71178a52: startup date [Fri May 03 23:45:01 CEST 2019]; root of context hierarchy
2019-05-03T23:46:14.158+0200 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:58442 #22 (14 connections now open)
[mongod output] 2019-05-03T23:46:14.240+0200 I COMMAND  [conn22] terminating, shutdown command received
[mongod output] 2019-05-03T23:46:14.240+0200 I FTDC     [conn22] Shutting down full-time diagnostic data capture
[mongod output] 2019-05-03T23:46:14.247+0200 I CONTROL  [conn22] now exiting
[mongod output] 2019-05-03T23:46:14.248+0200 I NETWORK  [conn22] shutdown: going to close listening sockets...
[mongod output] 2019-05-03T23:46:14.248+0200 I NETWORK  [conn22] closing listening socket: 396
[mongod output] 2019-05-03T23:46:14.249+0200 I NETWORK  [conn22] shutdown: going to flush diaglog...
[mongod output] 2019-05-03T23:46:14.249+0200 I NETWORK  [conn22] shutdown: going to close sockets...
[mongod output] 2019-05-03T23:46:14.393+0200 I STORAGE  [conn22] WiredTigerKVEngine shutting down
[mongod output] 2019-05-03T23:46:14.394+0200 I NETWORK  [conn7] end connection 127.0.0.1:58416 (13 connections now open)
[mongod output] 2019-05-03T23:46:14.394+0200 I NETWORK  [conn10] end connection 127.0.0.1:58430 (13 connections now open)
[mongod output] 2019-05-03T23:46:14.395+0200 I NETWORK  [conn6] end connection 127.0.0.1:58415 (13 connections now open)
[mongod output] 2019-05-03T23:46:14.395+0200 I NETWORK  [conn3] end connection 127.0.0.1:58412 (13 connections now open)
[mongod output] 2019-05-03T23:46:14.395+0200 I NETWORK  [conn2] end connection 127.0.0.1:58411 (13 connections now open)
[mongod output] 2019-05-03T23:46:14.395+0200 I NETWORK  [conn11] end connection 127.0.0.1:58431 (13 connections now open)
[mongod output] 2019-05-03T23:46:14.395+0200 I NETWORK  [conn19] end connection 127.0.0.1:58439 (13 connections now open)
[mongod output] 2019-05-03T23:46:14.396+0200 I NETWORK  [conn5] end connection 127.0.0.1:58414 (9 connections now open)
[mongod output] 2019-05-03T23:46:14.396+0200 I NETWORK  [conn1] end connection 127.0.0.1:58403 (6 connections now open)
[mongod output] 2019-05-03T23:46:14.397+0200 I NETWORK  [conn17] end connection 127.0.0.1:58437 (6 connections now open)
[mongod output] 2019-05-03T23:46:14.397+0200 I NETWORK  [conn4] end connection 127.0.0.1:58413 (3 connections now open)
[mongod output] 2019-05-03T23:46:14.397+0200 I NETWORK  [conn16] end connection 127.0.0.1:58436 (2 connections now open)
[mongod output] 2019-05-03T23:46:14.397+0200 I NETWORK  [conn20] end connection 127.0.0.1:58440 (1 connection now open)
[mongod output] 2019-05-03T23:46:14.445+0200 I STORAGE  [conn22] shutdown: removing fs lock...
[mongod output] 2019-05-03T23:46:14.445+0200 I CONTROL  [conn22] dbexit:  rc: 0

**Comment by Loki-Afro** [comment]
first of all use the latest version of spring boot. even they got a version 2.x like.
second this error is mongodb related - you specified a version (with `PRODUCTION`) which does not support the decimal mongodb feature.
third in all versions there is `IMongodConfig` so this is a problem in your ide or something.

**Comment by Research2Go** [comment]
Do you know which version is supporting decimal mongodb feature then?

**Comment by Loki-Afro** [comment]
regarding your no such field error and spring boot version IDE issue / dependency madness - just search for a recent sprint boot tutorial for an up to date setup but this is beyond this library

regarding the decimal feature ... https://docs.mongodb.com/manual/tutorial/model-monetary-data/#numeric-decimal says since mongo 3.4

In any way, I recommend to institute the version yourself `IVersion`

for example like so 
````
		EnumSet<Feature> features = Version.Main.PRODUCTION.getFeatures();
		IFeatureAwareVersion iFeatureAwareVersion = Versions.withFeatures(new GenericVersion("6.6.6"), features);
```

but how you integrate that into spring boot: again not part of this library, but if you find a good solution others would be happy to find it ;)

**Comment by Research2Go** [comment]
Using external MongoDB within springboot automatically is indeed a challenging but interesting task, my first approach is to use embedded MongoDB instead of external one. But it seems not working...... 

The error message comes from de.flapdoodle.embed.mongo.MongodExecutable. 
I don't understand why the Version field is defined in the class, but we still meet up with this error. 


2019-05-06 11:44:16.095  WARN 8032 --- [           main] .... nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' threw exception; nested exception is java.lang.NoSuchFieldError: V3_6
