### ISSUE TITLE
nested exception is java.io.IOException: Could not start process: <EOF>

### ISSUE THREAD

**Issue by wjtlopez** [flapdoodle-oss/de.flapdoodle.embed.mongo#287]
Hello,

I've seen other issues with the same exception but thought this one is worth bringing to your attention as it looks like the cause is very different, and a lot simpler to resolve.

I am using spring-boot-dependencies:2.1.4.RELEASE

When these two properties are set:

spring.data.mongodb.host=
spring.data.mongodb.port=

The following exception is thrown:
```Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.io.IOException: Could not start process: <EOF>```

Regards,
Warren

**Comment by wjtlopez** [comment]
Closed as realised I had misread logs :)

**Comment by majitospost** [comment]
Hello friend, I have this problem, what did you solved this?

**Comment by naddison** [comment]
@majitospost Make sure in your application.properties to not have 
spring.data.mongodb.host=
spring.data.mongodb.port=

set. I had this issue, but I fixed it by commenting these two out.

**Comment by Dathin** [comment]
@naddison Thank you. You saved my life

**Comment by egaudino** [comment]
@naddison thanks man, it works!

**Comment by chillywhale** [comment]
> @majitospost Make sure in your application.properties to not have
> spring.data.mongodb.host=
> spring.data.mongodb.port=
> 
> set. I had this issue, but I fixed it by commenting these two out.

thanks for your solution, it does work. But what should be the most proper solution? 
The situation is that I want to use the embedded mongo while testing, but to use the local mogo server while running the application.  
The gradle build complains when I leave the spring.data.mongodb.host in the application.yml

**Comment by RafaelGomez1** [comment]
@naddison dude you really saved me with that one. Thanks a lot

**Comment by collinewait** [comment]
> > @majitospost Make sure in your application.properties to not have
> > spring.data.mongodb.host=
> > spring.data.mongodb.port=
> > set. I had this issue, but I fixed it by commenting these two out.
> 
> thanks for your solution, it does work. But what should be the most proper solution?
> The situation is that I want to use the embedded mongo while testing, but to use the local mogo server while running the application.
> The gradle build complains when I leave the spring.data.mongodb.host in the application.yml

Good question @chillywhale. You can have a specific profile for running your application e.g `application-dev.properties` where you can put your details. And then run the application with the following command line args `-Dspring-boot.run.profiles=dev`. You can also set `-Dspring-boot.run.profiles=dev` directly in your editor if you want to execute it with the editor.

**Comment by lorencole** [comment]
> > @majitospost Make sure in your application.properties to not have
> > spring.data.mongodb.host=
> > spring.data.mongodb.port=
> > set. I had this issue, but I fixed it by commenting these two out.
> 
> thanks for your solution, it does work. But what should be the most proper solution? The situation is that I want to use the embedded mongo while testing, but to use the local mogo server while running the application. The gradle build complains when I leave the spring.data.mongodb.host in the application.yml

I create a src/test/resources/application.properties file. Then src/main/resources/application.properties content is ignored when running tests.

**Comment by j-hrcan** [comment]
@lorencole have you tried putting it in `src/main/resources/config/application.properties`?
