### ISSUE TITLE
flapdoodle mongodExecutable.start() process is getting hanged

### ISSUE THREAD

**Issue by sayandg14** [flapdoodle-oss/de.flapdoodle.embed.mongo#288]
flapdoodle mongodExecutable.start() process is getting hanged , I have used proxy to create runTimeConfig . It is getting downloaded properly and the server is on the way of starting when it is getting hanged , printing ..

[mongod output] server was very slow 
[mongod output]

**Comment by michaelmosmann** [comment]
.. if this still is an issue, please reopen.
