### ISSUE TITLE
Change streams not swupported?

### ISSUE THREAD

**Issue by mingxhzhu** [flapdoodle-oss/de.flapdoodle.embed.mongo#289]
Does change streams supported? When I try to subscribe to changes I got the following error message:

--------------------------------------------------------------------
 "Exception in thread "SimpleAsyncTaskExecutor-1" org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 40324 (Location40324): 'Unrecognized pipeline stage name: '$changeStream'' on server localhost:49614. The full response is { "ok" : 0.0, "errmsg" : "Unrecognized pipeline stage name: '$changeStream'", "code" : 40324, "codeName" : "Location40324" }; nested exception is com.mongodb.MongoCommandException: Command failed with error 40324 (Location40324): 'Unrecognized pipeline stage name: '$changeStream'' on server localhost:49614. The full response is { "ok" : 0.0, "errmsg" : "Unrecognized pipeline stage name: '$changeStream'", "code" : 40324, "codeName" : "Location40324" }"

**Comment by philippreston** [comment]
Would be great to support change streams.

**Comment by Loki-Afro** [comment]
never played with it but this fully depends on the  mongodb version you are using.

And you can easy configure the one you wanna use up to 4.0.
