### ISSUE TITLE
support for ppc64le

### ISSUE THREAD

**Issue by shirodkara** [flapdoodle-oss/de.flapdoodle.embed.mongo#297]
[Paths.java](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/Paths.java) does not have support for ppc64le platform. 

The mongodb binaries for ppc64le are available here 
[https://www.mongodb.com/download-center/enterprise/releases/archive](https://www.mongodb.com/download-center/enterprise/releases/archive )

There is a separate "license agreement" that has to be agreed to before downloading the ppc64le binaries.

**Comment by Loki-Afro** [comment]
@shirodkara you can overwrite the download url or even set a path where the binary is located.

I don't consider this is useful for anybody else, sorry
