### ISSUE TITLE
Where is 2.2.1-SNAPSHOT

### ISSUE THREAD

**Issue by Kouroshb26** [flapdoodle-oss/de.flapdoodle.embed.mongo#298]
In the documentation you suggest that there is 2.2.1-SNAPSHOT but I have not seen this anywhere. I am wondering when it will be released.

**Comment by vgarmash** [comment]
Seems like they have changed snapshots deployment path but forgot to publish it. I noticed that when I tried to add 3.0.1-SNAPSHOT as it is described in Readme:

<img width="710" alt="2021-06-19 19_33_29 Readme about Snapshots" src="https://user-images.githubusercontent.com/1226001/122649388-415d3a00-d136-11eb-98ad-fcf8995b0d25.png">

I checked the contents of the https://oss.sonatype.org/content/repositories/snapshots/ and I found that  the last snapshot there is 1.50.6-SNAPSHOT:
<img width="632" alt="2021-06-19 19_34_29 Sonatype Snapshots content" src="https://user-images.githubusercontent.com/1226001/122649417-6fdb1500-d136-11eb-9e1c-dec0535b34eb.png">

**Comment by michaelmosmann** [comment]
There is a new release.. so i think there is no need for any snapshot version:)
