### ISSUE TITLE
Error "this version does not support 32Bit: PRODUCTION:Linux:B32" when travis job executed for ppc64le

### ISSUE THREAD

**Issue by rashmi-ibm** [flapdoodle-oss/de.flapdoodle.embed.mongo#300]
Link to travis job:-
https://travis-ci.org/rashmi-ibm/de.flapdoodle.embed.mongo/jobs/594994577

Error:
Download DEVELOPMENT:Windows:B64 DONE
Extract /home/travis/.embedmongo/win32/mongodb-win32-x86_64-2008plus-ssl-latest.zip START
Extract /home/travis/.embedmongo/win32/mongodb-win32-x86_64-2008plus-ssl-latest.zip extract mongodb-win32-x86_64-2008plus-ssl-4.1.0-158-g3d62f3cd37/bin/mongod.exe
Extract /home/travis/.embedmongo/win32/mongodb-win32-x86_64-2008plus-ssl-latest.zip nothing left
Extract /home/travis/.embedmongo/win32/mongodb-win32-x86_64-2008plus-ssl-latest.zip DONE
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 127.689 sec <<< FAILURE! - in de.flapdoodle.embed.mongo.MongoDBRuntimeTest
testCheck(de.flapdoodle.embed.mongo.MongoDBRuntimeTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.IllegalArgumentException: this version does not support 32Bit: PRODUCTION:Linux:B32
	at de.flapdoodle.embed.mongo.MongoDBRuntimeTest.testCheck(MongoDBRuntimeTest.java:149)
Running de.flapdoodle.embed.mongo.MongoImportExecutableTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.005 sec <<< FAILURE! - in de.flapdoodle.embed.mongo.MongoImportExecutableTest
testStartMongoImport(de.flapdoodle.embed.mongo.MongoImportExecutableTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.IllegalArgumentException: this version does not support 32Bit: PRODUCTION:Linux:B32
	at de.flapdoodle.embed.mongo.MongoImportExecutableTest.testStartMongoImport(MongoImportExecutableTest.java:56)

Created a fork of the repo and updated travis.yml apart from that there arent any changes.
Changes in travis.yml
os:
  - linux-ppc64le
jdk:
  - openjdk8

**Comment by hflaachiri** [comment]
I have the same problem,
I installed a gitlab runner on my raspberry pi 4 with an ubuntu 64 bit the integration tests are not executed I Have this message: 
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDbFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDbFactoryConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.core.MongoDbFactorySupport]: Factory method 'mongoDbFactory' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' threw exception; nested exception is java.lang.IllegalArgumentException: this version does not support 32Bit: Version{3.5.5}:Linux:B32`

**Comment by michaelmosmann** [comment]
.. if this still is an issue, please reopen.
