### ISSUE TITLE
Customizing extractDir and tempDir makes the extractmongod.exe path not found

### ISSUE THREAD

**Issue by nlenew** [flapdoodle-oss/de.flapdoodle.embed.mongo#301]
Hi,

I have customized my running config to change the artefact download path, temp dir and extract dir the ones I need. Here is the config : 

`IRuntimeConfig runtimeConfig = new RuntimeConfigBuilder()

                .defaults(command)

                .artifactStore(new ExtractedArtifactStoreBuilder()

                        .defaults(command)

                        .download(new DownloadConfigBuilder()

                                .defaultsForCommand(command)

                                .downloadPath("ftp://local:local@localhost/")

                                .artifactStorePath(new FixedPath("bundles/mongodb/"))

                                .build())

                        .extractDir(new FixedPath("bundles/mongodb"))

                        .tempDir(new FixedPath("bundles/mongodb")))

                .build();

        MongodStarter starter = MongodStarter.getInstance(runtimeConfig);`

Unfortunately, it ends up with that path to start the mongod : 

`\bundles\mongodb\bundles\mongodb\extract-f3fee836-b6cb-4e01-955b-94dd159404edextractmongod.exe`

As you can see, the \bundles\mongodb path is repeated in the path which results in a not found issue.

Any idea on why this happens or what am doing wrong?

Regards,

**Comment by Loki-Afro** [comment]
This is a bit crazy looking, why don't you change any path to even see which one the faulty might be?

In any way I'd recommend using absolute paths like here https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-artifact-storage

**Comment by michaelmosmann** [comment]
.. this is solved with this new version: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/tree/embed-mongo-4.x
