### ISSUE TITLE
Add timeoutSecs: 0 to shutdown command

### ISSUE THREAD

**Issue by shollander** [flapdoodle-oss/de.flapdoodle.embed.mongo#302]
Please merge pull request #299 and create a new release version. 

This fixes an issue where the shutdown of embedded mongo takes too long. By adding the `timeoutSecs` parameter to the shutdown command, we can force the shutdown to happen immediately. This is especially an issue when embedded mongo is configured as a replicaSet (required for some features of mongodb such as transaction support).

See related issue #268 for more details.

Thank you.

**Comment by gregRzn** [comment]
I would really appreciate that since I'm facing the same problem. Thank you!
