### ISSUE TITLE
Mongo Schema Validation does not work.

### ISSUE THREAD

**Issue by XeZZoR** [flapdoodle-oss/de.flapdoodle.embed.mongo#303]
Related to: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/245

I created a simple Testproject with a Unit Test to show the behavior here: 
[mongo.zip](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/files/3743446/mongo.zip)

The Unit test should fail since the field that is required via schema is not there. I can see the schema when I connect to the test DB but it does not seem to validate the entry.

Also when saving the Documents I actually cannot see them directly in the DB. Is there some "commit" command or something I have to hit before?

**Comment by emmaLP** [comment]
Did you ever get schema validation to work?

I'm experiencing the same issue and would really like to get it solved

**Comment by michaelmosmann** [comment]
.. if this still is an issue, please reopen.
