### ISSUE TITLE
Unable to excute queries with collation.

### ISSUE THREAD

**Issue by raghavendra-hegde** [flapdoodle-oss/de.flapdoodle.embed.mongo#304]
In our application, we are trying to test string search functionality and we have used collation with primary comparison level. 
 
Test cases are failing when the query is executed. while same query works fine in actual cses with mongo db.

**Comment by manuelwaltschek** [comment]
Any info on this one?
To me it seems that i cannot test unique indexes that are also case insensitive.
Integration tests that write to embedded mongodb ignore the collation, while it is working with real mongoDB version 5.0.6

**Comment by michaelmosmann** [comment]
which version do you use in test? can you provide some setup information: which spring version, which db version..

**Comment by michaelmosmann** [comment]
.. if this still is an issue, please reopen.
