### ISSUE TITLE
Embedded Mongo 3.6+ doesn't work on Windows

### ISSUE THREAD

**Issue by thundur** [flapdoodle-oss/de.flapdoodle.embed.mongo#309]
mongod.exe from 3.6 on requires libeay32.dll and ssleay32.dll in the same folder as mongod.exe to work. However, these files are not extracted, so mongod.exe exits with an error.

When I manually place the two dlls in <user>\AppData\Local\Temp, the embedded mongo server does work.

So I suppose that for windows, the dll files should be extracted and copied to the AppData\Local\Temp folder.

**Comment by michaelmosmann** [comment]
.. if this still is an issue, please reopen.

**Comment by ppkarwasz** [comment]
@michaelmosmann,

I can confirm that `ssleay32.dll` and `libeay32.dll` are still missing from the unpacked distribution. An example of a failing test can be found in [`MongoDb3Resolver.java`](https://github.com/apache/logging-log4j2/blob/2.x/log4j-mongodb3/src/test/java/org/apache/logging/log4j/mongodb3/MongoDb3Resolver.java).

**Comment by michaelmosmann** [comment]
@ppkarwasz thanks.
