### ISSUE TITLE
Mongod should add '--auth' if 'UserName' and 'Password' are set

### ISSUE THREAD

**Issue by Lacritz** [flapdoodle-oss/de.flapdoodle.embed.mongo#311]
Hi, 

As mentioned in the title you should introduce a check wether UserName and Password are set and enable authentication if so.  

Instead of 
```java
if (config.cmdOptions().auth()) {
    ret.add("--auth");
} else {
    ret.add("--noauth");
}
```

You could go with 
```java
if (config.cmdOptions().auth()) {
    ret.add("--auth");
} else if (credentialsProvided(config.params())) {
    ret.add("--auth");
} else {
    ret.add("--noauth");
}
```

```java
boolean credentialsProvided() {
    if (config.params() != null && !config.params().isEmpty()) {
        return (config.params.contains("Password") && config.params.contains("UserName"));
    } 
    return false;
}
```

The feature is necessary for testing purposes and mentioned in a issue on spring boot.
https://github.com/spring-projects/spring-boot/issues/19583

Best

**Comment by michaelmosmann** [comment]
this should be solved with this new version: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/tree/embed-mongo-4.x
