### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by shollander** [flapdoodle-oss/de.flapdoodle.embed.mongo#314]
Is this project dead? Issues are going unanswered for months and there are a bunch of pull requests that have been submitted and never merged.

**Comment by snava10** [comment]
If not, does this has support for change streams and transactions ?

**Comment by lucasoares** [comment]
@snava10 it ddownloads mongodb binary and executes it, so all MongoDB resources are available. But apparently the project do not support MongoDB 4.2 version =(

**Comment by ravening** [comment]
> Is this project dead? Issues are going unanswered for months and there are a bunch of pull requests that have been submitted and never merged.

Looks like it is. Last commit was 17 months ago

**Comment by willks** [comment]
> If not, does this has support for change streams and transactions ?

I dunno about mongo 4.2, but I got transactions working with this init code in my tests using cross collection transactions. It's in Kotlin though (convert back to Java?):


```
import com.mongodb.client.MongoClients
import de.flapdoodle.embed.mongo.MongodExecutable
import de.flapdoodle.embed.mongo.MongodStarter
import de.flapdoodle.embed.mongo.config.MongoCmdOptionsBuilder
import de.flapdoodle.embed.mongo.config.MongodConfigBuilder
import de.flapdoodle.embed.mongo.config.Net
import de.flapdoodle.embed.mongo.config.Storage
import de.flapdoodle.embed.mongo.distribution.Version
import de.flapdoodle.embed.process.distribution.GenericVersion
import de.flapdoodle.embed.process.runtime.Network
import org.bson.Document
import org.junit.jupiter.api.AfterAll
import org.junit.jupiter.api.BeforeAll
import org.springframework.data.mongodb.core.MongoTemplate
import kotlin.system.exitProcess

open class BaseMongoTest {

    init {
        System.setProperty("user.timezone", "UTC")
    }

    companion object {
        private lateinit var mongodExecutable: MongodExecutable
        private lateinit var mongoTemplate: MongoTemplate

        private val dbName = "admin"

        @BeforeAll
        @JvmStatic
        fun setupMongo() {
            val ip = "localhost"
            val port = 38000
            val version = de.flapdoodle.embed.mongo.distribution.Versions.withFeatures(
                    GenericVersion("4.0.0"),
                    Version.Main.PRODUCTION.features)

            val mongodConfig = MongodConfigBuilder().version(version)
                    .replication(Storage(null, "rs", 5000))
                    .cmdOptions(MongoCmdOptionsBuilder().useNoJournal(false).build())
                    .net(Net(ip, port, Network.localhostIsIPv6()))
                    .build()

            val starter = MongodStarter.getDefaultInstance()
            mongodExecutable = starter.prepare(mongodConfig)
            mongodExecutable.start()
            val mongoClient = MongoClients.create("mongodb://$ip:$port")
            val db = mongoClient.getDatabase(dbName)
            db.runCommand(Document("replSetInitiate", Document()))
            mongoTemplate = MongoTemplate(mongoClient, dbName)
        }

        @AfterAll
        @JvmStatic
        fun stopMongo() {
            try {
                mongodExecutable.stop()
                exitProcess(0)
            }catch(ex:Exception){
                mongodExecutable.stop();
            }finally {
                mongodExecutable.stop();
            }
        }
    }
}
```

**Comment by michaelmosmann** [comment]
As mongodb did a lot of changes (their download path could not be guessed anymore, different versions for different os, how mongodb shows that it is started) it took me to muich time to think about how to handle this change. As i don't use mongodb in my current projects there was just no time to fix this .. i thought, that this project is maybe not important anymore.. there is test container, cloud stuff .. so many options to deal with.

.. but there are people out there still using this. Hmm..

I don't know how to solve this.. i got some time and made a new release.. but maybe there must be an other way to provide some energy to this...
