### ISSUE TITLE
Exclude flapdoodle for some tests and socket timeouts

### ISSUE THREAD

**Issue by d3minem** [flapdoodle-oss/de.flapdoodle.embed.mongo#315]
Want to exclude the `flapdoodle` for some integration tests. And how can I solve these socket **timeouts** problem.

Can you please look into this issue? and provide some feedback.

StackOverflow: [Exclude flapdoodle for some tests and socket timeouts](https://stackoverflow.com/questions/61398247/exclude-flapdoodle-for-some-tests)

**Comment by michaelmosmann** [comment]
.. if this is still an issue, please reopen.
