### ISSUE TITLE
EmbeddedMongoAutoConfiguration Fails in AWS CodeBuild due to lack of resolution for local host

### ISSUE THREAD

**Issue by geoffmina** [flapdoodle-oss/de.flapdoodle.embed.mongo#316]
AWS CodeBuild does not provide DNS resolution for the local hostname.  This causes the constructor of the AbstractMongoConfigBuilder to fail - even in scenarios where the hostname is being provided explicitly either via config or pragmatically.  As there are only no-arg constructors available in MongodConfigBuilder and AbstractMongoConfigBuilder, there is no way to bypass the default call to new Net() which throws an UnknownHostException preventing the utilization of any auto-configuration features.

Patch file submitted to more elegantly deal with the default Net() object not being created properly.
[patch.txt](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/files/4545849/patch.txt)

**Comment by michaelmosmann** [comment]
.. if this still is an issue, than i would solve this in this new version https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/tree/embed-mongo-4.x  .. please reopen if needed.
