### ISSUE TITLE
flapdoodle embed: DistributionException: NoSuchFileException: /tmp/Linux-B64--3.6.5/extract-5a7ce234-e0a7-4801-9499-196040319c0emongod

### ISSUE THREAD

**Issue by mcherb** [flapdoodle-oss/de.flapdoodle.embed.mongo#317]
I'm using flapdoodle embed mongo for my tests. Now I'm trying to run my tests in parallel (before everything was working fine).

At first I've this error :

    java.io.IOException: Cannot run program "/tmp/extract-f77354d0-83fa-47e2-b7e1-47b3577bbf4eextractmongod": error=13, Permission denied`

I've managed to fix it like suggested in [this](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/174) issue by adding extractExecutableNaming to the ArtifactStore :

```java
new ExtractedArtifactStoreBuilder()
.defaults(Command.MongoD)
.executableNaming(new UUIDTempNaming())
.extractExecutableNaming(new UUIDTempNaming()) // adding this
```

Now I'm facing another problem, the exception says :

    de.flapdoodle.embed.process.exceptions.DistributionException: java.nio.file.NoSuchFileException: /tmp/Linux-B64--3.6.5/extract-5a7ce234-e0a7-4801-9499-196040319c0emongod, took 0.789 sec
    [error] at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:69)
    [error] at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49)
    [error] at testutils.EmbeddedMongo.start(EmbeddedMongo.java:87)
    [error] at testutils.AbstractDatabaseTestSuite.setUp(AbstractDatabaseTestSuite.java:32)
    [error] ...
    [error] Caused by: java.nio.file.NoSuchFileException: /tmp/Linux-B64--3.6.5/extract-5a7ce234-e0a7-4801-9499-196040319c0emongod
    [error] at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    [error] at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    [error] at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    [error] at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
    [error] at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
    [error] at java.nio.file.Files.copy(Files.java:1274)
    [error] at de.flapdoodle.embed.process.extract.ExtractedFileSets.copy(ExtractedFileSets.java:55)
    [error] at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:110)
    [error] at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:57)
    [error] ... 38 more

```java
@SneakyThrows
IRuntimeConfig runtimeConfig(Command cmd) {
    val artifactStoreBuilder = new ExtractedArtifactStoreBuilder()
            .defaults(cmd)
            .tempDir(new TempDirInPlatformTempDir())
            .extractDir(directory)
            .executableNaming(new UUIDTempNaming())
            .extractExecutableNaming(new UUIDTempNaming());

    return new RuntimeConfigBuilder()
            .defaults(cmd)
            .processOutput(ProcessOutput.getDefaultInstanceSilent())
            .artifactStore(artifactStoreBuilder)
            .build();
}
```

Any idea to fix this ?

**Comment by Loki-Afro** [comment]
Do not run your tests in parallel, that is not supported, sorry

**Comment by davebarda** [comment]
@Loki-Afro, do you have any plans to add it?

**Comment by kezhenxu94** [comment]
Would like to see parallel is supported, or any workaround, or any hints that I can start to contribute?

**Comment by michaelmosmann** [comment]
parallel tests are now supported..
