### ISSUE TITLE
Basic auth for custom MongoDB download URL

### ISSUE THREAD

**Issue by froblesmartin** [flapdoodle-oss/de.flapdoodle.embed.mongo#321]
Hi all!

I am trying to use the custom download URL (https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-download-url) but the server where we have mirrored the MongoDB repository requires basic authentication.

I have been checking the code for possibilities to specify them but I have not found anything 😞 .

Then the only way that comes to my mind is to specify the username and password on the URL following https://www.ietf.org/rfc/rfc1738.txt, with the format `<user>:<password>@<host>:<port>/<url-path>`, but it still does not work, receiving a 401 from the server. Using the same URL that I can get from the URL object on debug mode it works on a browser.

Is there any way to do this, or would this need to be added in the logic on this package?

Also, this is, in the end, using https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/master/src/main/java/de/flapdoodle/embed/process/store/Downloader.java, so I guess the functionality to manage credentials might be required there 😓 

Cheers,
Francisco Robles Martín

**Comment by froblesmartin** [comment]
As a workaround I was able to set the basic authentication credentials with the following code that I found at https://stackoverflow.com/a/496707/7653022:

```
import java.net.Authenticator;
import java.net.PasswordAuthentication;

String username = "RickSanchez"
String password = "c-137"

Authenticator.setDefault (new Authenticator() {
    protected PasswordAuthentication getPasswordAuthentication() {
        return new PasswordAuthentication (username, password.toCharArray());
    }
});
```

**Comment by michaelmosmann** [comment]
.. if this still is an issue, i would solve this in this new version: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/tree/embed-mongo-4.x .. please reopen, if needed.

**Comment by wazyk** [comment]
Hello.
I encountered exactly the same issue. Is there a way to workaround this, or do I need to wait for a fix in the tool ?
Thanks in advance.

**Comment by michaelmosmann** [comment]
@wazyk do you use basic auth for that? is this server some kind of internal proxy? can you create a new issue for that?

**Comment by wazyk** [comment]
Yes the custom url is an internal proxy (that I can't act on, it belongs to the client). The only acces I can get is with basic auth with login:pwd in url.
I can try to fill a new issue for that.

**Comment by michaelmosmann** [comment]
@wazyk the answer is in the new issue..
