### ISSUE TITLE
While compiling tests cases getting exception Caused by: java.io.IOException: Could not start process: <EOF> 

### ISSUE THREAD

**Issue by Panks1790** [flapdoodle-oss/de.flapdoodle.embed.mongo#324]
Hi Team,

Can you please check below issue.

###  [2020-10-08T12:30:57.272Z] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoAppConfiig': Invocation of init method failed; nested exception is java.io.IOException: Could not start process: EOF

[2020-10-08T12:30:57.272Z] Caused by: java.io.IOException: Could not start process: EOF

Version which we are using 

Java version "1.8.0_112" (64-Bit Server )
de.flapdoodle.embed.mongo.version:- 2.2.0
Spring Boot Version :- 2.2.5.RELEASE
 Mongo DB version(Embeded used in jenkins):-  4.0.2

**Comment by EthanNguyen132** [comment]
Exact same error message for me.

Java version "1.8.0_272" (64-Bit Server )
de.flapdoodle.embed.mongo.version:- 2.2.0
Spring Boot Version :- 2.3.4.RELEASE

**Comment by amvi23** [comment]
If you have this issue on a Windows machine check following DLLs using cmd
`WHERE libeay32.dll
WHERE ssleay32.dll`
Path to those files must be in declared in enviroment path.
If the files are missing you can get them from https://www.mongodb.com, download your required MongoDb Community Service version as zip file.

**Comment by alexaasha** [comment]
> If you have this issue on a Windows machine check following DLLs using cmd
> `WHERE libeay32.dll`
> `WHERE ssleay32.dll`
> Path to those files must be declared in environment path.
> If the files are missing you can get them from https://www.mongodb.com: download your required MongoDb Community Service version as zip file and extract them from it.

And what about Ubuntu 20.04?

**Comment by michaelmosmann** [comment]
I did a new release.. can you try if this problem still exist?

**Comment by gscaparrotti** [comment]
I encountered this problem when there was a previous instance of Embedded MongoDB still running after a test failed without killing it. You may want to check it this is the case. I used [CurrPorts](https://www.nirsoft.net/utils/cports.html) to discover the process from the port it was using.

**Comment by michaelmosmann** [comment]
It should be solved with this new version: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/tree/embed-mongo-4.x .. please reopen, if this issue still exist.
