### ISSUE TITLE
JUnit Extensions

### ISSUE THREAD

**Issue by kylep-dremio** [flapdoodle-oss/de.flapdoodle.embed.mongo#328]
We're using flapdoodle for some tests, and added support in our code for starting a sharded and non-sharded mongo instance for use with tests using JUnit Extensions: https://junit.org/junit5/docs/5.0.0/api/org/junit/jupiter/api/extension/Extensions.html

I think this would likely be useful as a contribution to the core project, and am willing to put time towards making our existing code generic such that it would then rely on the flapdoodle implementation.

Feedback is welcome.

**Comment by kylep-dremio** [comment]
For context - here is the specialized code: https://github.com/projectnessie/nessie/pull/792

**Comment by michaelmosmann** [comment]
sorry for this late answer.. this would be nice.. we have a new release.. so i can have a look at this.

**Comment by michaelmosmann** [comment]
maybe this is what you are looking for: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/embed-mongo-4.x/src/test/java/de/flapdoodle/embed/mongo/transitions/MongosTest.java
