### ISSUE TITLE
Can't find RuntimeConfig class

### ISSUE THREAD

**Issue by roeniss** [flapdoodle-oss/de.flapdoodle.embed.mongo#330]
I'm trying to follow [proxy config on readme](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-proxy-for-download) but can't find the RuntimeConfig.class, which makes the compiler message saying "Cannot resolve symbol 'RuntimeConfig'". 

I'm using latest version now. What should I do?

**Comment by michaelmosmann** [comment]
Is this still an issue? We have a new release..
