### ISSUE TITLE
Unable to download Mongo v3.6.4 (HTTP 403)

### ISSUE THREAD

**Issue by adamszczygielski** [flapdoodle-oss/de.flapdoodle.embed.mongo#331]
What I get is:
`Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://downloads.mongodb.org/win32/mongodb-win32-x86_64-ssl-3.6.4.zip`

**Comment by Kobee1203** [comment]
The correct URL for v3.6.4 is the following:
https://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.6.4.zip

(See https://www.mongodb.com/download-center/community/releases/archive)

Set the version to "2008plus-ssl-3.6.4"

**Comment by michaelmosmann** [comment]
i think i fixed this with the new release (3.2.0)... please try it:)
