### ISSUE TITLE
de.flapdoodle.embed.mongo dependency causing unrelated unit tests to fail

### ISSUE THREAD

**Issue by emarler7** [flapdoodle-oss/de.flapdoodle.embed.mongo#333]
I am currently experiencing an issue with unit tests (unrelated to flapdoodle) failing intermittently unrelated to flapdoodle.

```
11:49:16 CreateStepTest > updateTask success FAILED
11:49:16     java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132
11:49:16         Caused by: org.springframework.beans.factory.BeanCreationException at ConstructorResolver.java:655
11:49:16             Caused by: org.springframework.beans.BeanInstantiationException at SimpleInstantiationStrategy.java:185
11:49:16                 Caused by: java.lang.IllegalArgumentException at LocalArtifactStore.java:48
```
I'm at a loss because the test doesn't even use the dependency, but for some reason it fails at the below code:

```
if (!Files.moveFile(download, artifactFile))
	throw new IllegalArgumentException("Could not move " + download + " to " + artifactFile);
```

The odd part is that this works 100% of the time locally, but fails 50% of the time in Jenkins. If I remove the flapdoodle dependency, then it works everytime in Jenkins. Unfortunately, the above is all I have from Jenkins.

**Comment by michaelmosmann** [comment]
hmm .. maybe spring wants to create an instance of LocalArtifactStore because of some package scanning? ..

**Comment by michaelmosmann** [comment]
Is this still an issue?

**Comment by emarler** [comment]
It is not. The issue was related to excluding the class EmbeddedMongoAutoConfiguration from our SpringBootApplication as follows:

`@SpringBootApplication(`
    exclude = {MongoAutoConfiguration.class, EmbeddedMongoAutoConfiguration.class})`

**Comment by michaelmosmann** [comment]
ok.. so i close this ticket. Thanks:)
