### ISSUE TITLE
Cannot download Mongo db when running on FreeBSD

### ISSUE THREAD

**Issue by madbear2000** [flapdoodle-oss/de.flapdoodle.embed.mongo#345]
I have a Jenkins Server running FreeBSD to run tests for a project. When it tries to start up the test server the following occurs. 

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' threw exception; nested exception is de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOException: Could not open inputStream for https://fastdl.mongodb.org/freebsd/mongodb-freebsd-x86_64-3.5.5.tgz with proxy Optional.empty`

The code is using
`testImplementation group: 'de.flapdoodle.embed', name: 'de.flapdoodle.embed.mongo', version: '3.0.0'`

I have tried to manual access the link https://fastdl.mongodb.org/freebsd/mongodb-freebsd-x86_64-3.5.5.tgz
and get
` <Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6KF6HHS3FH355065</RequestId>
<HostId>
uk/LK4PhEoiv7QPPLGWHLHikyX8KGBZpUvDrH2d29zz8LrgdET/tVP4c3Gh1F8+Feu7wmerz1jQ=
</HostId>
</Error>
`

**Comment by michaelmosmann** [comment]
I think mongodb does not support freebsd anymore..
