### ISSUE TITLE
3.0.1-SNAPSHOT binary is not available on mavenCentral or sonatype repositories

### ISSUE THREAD

**Issue by innovationhub-asia** [flapdoodle-oss/de.flapdoodle.embed.mongo#347]
Trying to download the latest snapshot with support of higher versions of mongo but seems only 3.0.0 artefacts are available. Anyone knows where to pull the 3.0.1-SNAPSHOT as described in readme?

**Comment by michaelmosmann** [comment]
Do you still need the snapshot version? There is a new release ...
