### ISSUE TITLE
Embedded Mongo startup fails because of mongod process startup message change

### ISSUE THREAD

**Issue by krraghavan** [flapdoodle-oss/de.flapdoodle.embed.mongo#351]
In 4.4.x the mongo process the success message on startup changed to "Waiting for connections" from "waiting for connections on port".  This causes the log watcher to not see the success message and the method never returns from ```logWatch.waitForResult``` in the AbstractMongoProcess ```onAfterProcessStart``` (line 63 from version 3.0.0).  I ended up creating custom versions of MongodStarter, MongodExecutable and MongodProcess in order to override the successMessage.

Perhaps make this message easily customizable through builder methods so that these subclasses don't need to be created.

**Comment by YoavNaaman** [comment]
Log:
[mongod output] {"t":{"$date":"2021-10-31T14:34:59.414+02:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener",**"msg":"Waiting for connections"**,"attr":{"port":27027,"ssl":"off"}}

Code:
	protected String successMessage() {
		return **"waiting for connections on port"**;
	}

**Comment by michaelmosmann** [comment]
I would like to change this.. but to see if the server is up and running in trying to connect to it, i have to rely on information i do not have.. which port, must use a real mongo client to get a valid connection .. etc.

Fixed this.. there is a new release with some other changes. Please try if this solves your problem.
