### ISSUE TITLE
Support for MongoDB versions 3.7 - 3.11

### ISSUE THREAD

**Issue by jasonjkeller** [flapdoodle-oss/de.flapdoodle.embed.mongo#360]
I'm trying to set up JUnit tests against MongoDB 3.7, 3.8, 3.9, 3.10, and 3.11 but cannot get it to work no matter what I've tried.

I'm working on OSX for my local dev machine but ultimately need the tests to also support running on other OSes (such as Linux) for the test runner.

I noticed that there are no 3.x versions higher than `V3_6_5` defined in `de.flapdoodle.embed.mongo.distribution.Version`. I've tried defining these versions myself (e.g. `3.7.9`) and using them in my `MongodConfig`:

```
        IFeatureAwareVersion iFeatureAwareVersion = Versions.withFeatures(de.flapdoodle.embed.process.distribution.Version.of("3.7.9"),
                Feature.SYNC_DELAY, Feature.STORAGE_ENGINE, Feature.ONLY_64BIT, Feature.NO_CHUNKSIZE_ARG, Feature.MONGOS_CONFIGDB_SET_STYLE,
                Feature.NO_HTTP_INTERFACE_ARG, Feature.NO_SOLARIS_SUPPORT, Feature.NO_BIND_IP_TO_LOCALHOST);
```

And I've verified that it exists at the default download url (i.e. https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.7.9.tgz) but it always fails with the following exception:

```
osx distribution not supported: GenericFeatureAwareVersion{3.7.9}:Platform{operatingSystem=OS_X, architecture=X86_64}
java.lang.IllegalArgumentException: osx distribution not supported: GenericFeatureAwareVersion{3.7.9}:Platform{operatingSystem=OS_X, architecture=X86_64}
	at de.flapdoodle.embed.mongo.packageresolver.OSXPackageFinder.lambda$rules$0(OSXPackageFinder.java:159)
	at de.flapdoodle.embed.mongo.packageresolver.PlatformMatchRules.packageFor(PlatformMatchRules.java:43)
	at de.flapdoodle.embed.mongo.packageresolver.OSXPackageFinder.packageFor(OSXPackageFinder.java:46)
	at de.flapdoodle.embed.mongo.packageresolver.PlatformMatchRules.packageFor(PlatformMatchRules.java:43)
	at de.flapdoodle.embed.mongo.packageresolver.PlatformPackageResolver.packageFor(PlatformPackageResolver.java:58)
	at de.flapdoodle.embed.process.store.ArtifactStore.filesToExtract(ArtifactStore.java:93)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:82)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:59)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
   ...
```

This seems to be related to the rules defined in `OSXPackageFinder` not including versions 3.7 - 3.11 from what I can tell. Is what I'm trying to do even possible via config? Or will it always fail for versions not defined in the `PackageFinder` implementations? If it's the latter then it would be great if MongoDB versions 3.7 - 3.11 were supported.

Is there a workaround where I could simply download the MongoDB distributions myself and configure the test to use the pre-downloaded executables instead?

**Comment by michaelmosmann** [comment]
If you provide some download urls for the missing mongodb versions we could fix that. I could not find any on the current download page.

**Comment by jasonjkeller** [comment]
@michaelmosmann Thanks for getting back to me!

I see that at least the 3.7.1 thru 3.7.9 versions are listed here: https://www.mongodb.org/dl/osx

as well as at this domain:

https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.7.1.tgz
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.7.2.tgz
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.7.3.tgz
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.7.4.tgz
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.7.5.tgz
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.7.6.tgz
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.7.7.tgz
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.7.8.tgz
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.7.9.tgz

That said, you can go ahead and ignore this request. I think I had some confusion between Mongo database versus Mongo client versions. As best as I can tell the database doesn't have any versions beyond 3.7.9 for the 3.x line.
