### ISSUE TITLE
Add support for additional command line options

### ISSUE THREAD

**Issue by fluidsonic** [flapdoodle-oss/de.flapdoodle.embed.mongo#361]
To allow setting opts that are not supported out of the box, like `--quiet`.

**Comment by fluidsonic** [comment]
Looks like that there's the undocumented `.putArgs("--quiet", "")`.
And doesn't prevent logging output anyway 😔

**Comment by niroussel** [comment]
Would be nice to be able to remove some options too: '--smallfiles' and '--noprealloc' are not supported in newest mongo (4.2). So the process can't start at all.

**Comment by michaelmosmann** [comment]
@niroussel 
Which command line options should be used is encoded if you use the Version enum provided by this project.. as spring boot does something different, this information is lost. I have to think about this so that this information (which feature is supported) is encoded somewhere else..

**Comment by michaelmosmann** [comment]
@niroussel @fluidsonic i think this can be solved with this version: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/tree/embed-mongo-4.x and the matching spring integration: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.6.x--embed-mongo-4.x

... if this still an issue, please reopen.
