### ISSUE TITLE
Embedded mongo extraction processes

### ISSUE THREAD

**Issue by infoShare** [flapdoodle-oss/de.flapdoodle.embed.mongo#368]
Hello,

have you notices @michaelmosmann how embedded mongo is working on linux machines ?

Many processes with mongo extraction are still alive after tests ends.

 2445 jenkins   20   0 1516516  17268   3068 S   0.7  0.1  16:47.43 extract-c1e4611
 4984 jenkins   20   0 1518576  18048   2704 S   0.7  0.1  12:31.83 extract-8963eb1
14813 jenkins   20   0 1516380  23560   3032 S   0.7  0.1   9:22.54 extract-fbc0539
22801 jenkins   20   0 1519244  55528   2628 S   0.7  0.3   0:23.38 extract-2a73b60
24907 jenkins   20   0 1517160  14504   3036 S   0.7  0.1  22:50.48 extract-3ae1a48
25735 jenkins   20   0 1517324  12012   2888 S   0.7  0.1  23:01.85 extract-1f19a15
31024 jenkins   20   0 1516332  58728   2744 S   0.7  0.4   0:08.89 extract-a6cfedd
 2423 jenkins   20   0 1516448  17852   3124 S   0.3  0.1  16:45.30 extract-aed3400
 3037 jenkins   20   0 1515208  11868   2936 S   0.3  0.1  16:41.79 extract-96f0946
 9047 jenkins   20   0  216528   3428      0 S   0.3  0.0  23:14.26 extract-0ada627
 9994 jenkins   20   0 1516192  15100   2928 S   0.3  0.1  10:32.55 extract-e1e9c00
 9995 jenkins   20   0 1516332  19944   2988 S   0.3  0.1  10:48.14 extract-b5b40bb
10396 jenkins   20   0 1516380  13232   2908 S   0.3  0.1  10:16.92 extract-20432b1
14759 jenkins   20   0 1519184  15820   2400 S   0.3  0.1   9:28.52 extract-af8e503
14774 jenkins   20   0 1516380  22060   2840 S   0.3  0.1  10:17.21 extract-643e939
14801 jenkins   20   0 1516380  20252   2684 S   0.3  0.1   9:22.89 extract-0deb444
14814 jenkins   20   0 1516380  17208   3080 S   0.3  0.1   9:22.45 extract-231d841
14823 jenkins   20   0 1516380  20228   3300 S   0.3  0.1   0:28.40 extract-7256692
15211 jenkins   20   0 1516656  13356   3472 S   0.3  0.1   0:28.13 extract-814a746
15273 jenkins   20   0 1516656  12204   3004 S   0.3  0.1   0:28.21 extract-2d4bdd0
16907 jenkins   20   0 1517148  47048   2952 S   0.3  0.3   9:17.21 extract-9bf8454
16968 jenkins   20   0 1519260  12652   2864 S   0.3  0.1  14:00.46 extract-03aef4b
16985 jenkins   20   0 1519276  13624   2444 S   0.3  0.1  14:01.62 extract-e2271ea
23732 jenkins   20   0 1519168  14164   3072 S   0.3  0.1  13:09.29 extract-afa3e11
23733 jenkins   20   0 1519244  12548   3092 S   0.3  0.1  13:12.10 extract-7ab298e
23784 jenkins   20   0 1517572  13780   2976 S   0.3  0.1  13:15.03 extract-56d9ea3
23898 jenkins   20   0 1516240  12532   3268 S   0.3  0.1  13:09.47 extract-ce13674
24397 jenkins   20   0 1516308  11620   3076 S   0.3  0.1  13:08.63 extract-60c7b91
24915 jenkins   20   0 1516960  18004   3020 S   0.3  0.1  22:48.33 extract-9a1e9ec
25275 jenkins   20   0 1519276  32340   2732 S   0.3  0.2  20:40.61 extract-56b590b
25276 jenkins   20   0 1516612  14652   2984 S   0.3  0.1  21:03.53 extract-fdb0cda
25292 jenkins   20   0 1516404  18248   2832 S   0.3  0.1  20:31.47 extract-2261fc3
30161 jenkins   20   0  218608   5900      0 S   0.3  0.0 107:03.36 extract-6e2ffbf
30356 jenkins   20   0  216620  19428      0 S   0.3  0.1   9:05.71 extract-10a7c0d

Maybe it would be good to implement some configurable "timeout" ?

**Comment by michaelmosmann** [comment]
@infoShare 
hhmm.. if the jvm stops these process should be gone.. are they started inside of just one jvm?

**Comment by infoShare** [comment]
It's on single jvm. Maybe some shutdown hook which is stopping all remaining processes/removing temp files would be possible.

**Comment by michaelmosmann** [comment]
there are shutdown hooks for that.. hmm..

**Comment by michaelmosmann** [comment]
@infoShare there is a shutdown hook for that https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/05f0c5ca431037f40ec1797c76271dc56d02fa1e/src/main/java/de/flapdoodle/embed/process/runtime/AbstractProcess.java#L106 .. so maybe the jvm is still running

**Comment by infoShare** [comment]
I'll verify how Jenkins is killing processes on build timeout executed by timeout plugin. Maybe it's killing process in some weird way which is not handled by hook.

**Comment by michaelmosmann** [comment]
@infoShare on which platform does your jenkins run? maybe the build run should create a new process which is killed automatically

**Comment by infoShare** [comment]
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)

jenkins  23716  0.3  0.3 1519380 58396 ?       Sl   15:50   0:15 /var/tmp/extract-81672e62-53b3-44fd-b231-33329afe9d13extractmongod --dbpath /var/tmp/embedmongo-db-5d76b85e-f456-433d-88fa-c5c3fc626ac7 --noauth --nojournal --port 23802 --bind_ip 127.0.0.1 --syncdelay=0
jenkins  24794  0.3  0.3 1516392 58412 ?       Sl   15:51   0:13 /var/tmp/extract-cb73b15c-81c9-4bcd-833f-8ee216a89affextractmongod --dbpath /var/tmp/embedmongo-db-4d2f7b75-89b7-4dd9-8c50-18c7f77ac9da --noauth --nojournal --port 19778 --bind_ip 127.0.0.1 --syncdelay=0
jenkins  25054  0.3  0.3 1516072 59660 ?       Sl   15:53   0:12 /var/tmp/extract-8deae74d-42fe-4ee0-afd4-e85728615811extractmongod --dbpath /var/tmp/embedmongo-db-6d2cc8d1-618a-4b80-aa2a-833524c2f160 --noauth --nojournal --port 14366 --bind_ip 127.0.0.1 --syncdelay=0
jenkins  25150  0.3  0.3 1516252 58940 ?       Sl   15:53   0:12 /var/tmp/extract-843ec7be-16fe-48da-8a3f-4d41d751cb7cextractmongod --dbpath /var/tmp/embedmongo-db-cf6f3b38-01f7-41d3-b7a0-d53ff9f81a1f --noauth --nojournal --port 9528 --bind_ip 127.0.0.1 --syncdelay=0
jenkins  28353  0.3  0.3 1519364 58924 ?       Sl   16:02   0:10 /var/tmp/extract-e45385cc-d928-440f-a2d8-3afd32672e46extractmongod --dbpath /var/tmp/embedmongo-db-3956e4de-6061-49df-a4b5-8ba2abcee94e --noauth --nojournal --port 27305 --bind_ip 127.0.0.1 --syncdelay=0
jenkins  28399  0.2  0.3 1516072 59344 ?       Sl   16:02   0:09 /var/tmp/extract-8346cf31-f1fc-4833-bbba-444af3d88317extractmongod --dbpath /var/tmp/embedmongo-db-a9cb38b5-3751-4427-b4e7-075e4ca37849 --noauth --nojournal --port 14101 --bind_ip 127.0.0.1 --syncdelay=0
jenkins  28458  0.2  0.3 1519364 59036 ?       Sl   16:02   0:09 /var/tmp/extract-79c31485-e784-4911-ae8e-f60878cdf9b1extractmongod --dbpath /var/tmp/embedmongo-db-d5b9362b-c49f-4e98-9a3b-6aeb14a137ff --noauth --nojournal --port 5169 --bind_ip 127.0.0.1 --syncdelay=0
jenkins  28639  0.3  0.3 1516072 57832 ?       Sl   16:03   0:10 /var/tmp/extract-34e7f76a-0370-4b23-b8ba-d441c8b39e9fextractmongod --dbpath /var/tmp/embedmongo-db-8da9b9f9-15a4-4929-a044-1c462631d826 --noauth --nojournal --port 17207 --bind_ip 127.0.0.1 --syncdelay=0
jenkins  28699  0.3  0.3 1516372 58336 ?       Sl   16:04   0:10 /var/tmp/extract-c3270639-3e90-4d14-a68e-d989f9aad63dextractmongod --dbpath /var/tmp/embedmongo-db-2692a63f-0c5f-4688-b467-cfb7f16181e9 --noauth --nojournal --port 24229 --bind_ip 127.0.0.1 --syncdelay=0
jenkins  29242  0.3  0.3 1516384 58232 ?       Sl   16:05   0:09 /var/tmp/extract-22c0a020-6bcc-4e0d-a524-925f89490e25extractmongod --dbpath /var/tmp/embedmongo-db-a3acbe31-e6b7-4aca-a61c-62ac69ac3a0a --noauth --nojournal --port 9558 --bind_ip 127.0.0.1 --syncdelay=0

When maven build process is killed (by jenkins), these child processes are still alive.

**Comment by michaelmosmann** [comment]
@infoShare can you provide some test code (setup, framework etc.)? maybe i can get an better idea whats going on and why there is no shutdown...

**Comment by michaelmosmann** [comment]
Hmm.. if still an issue, please reopen.
