### ISSUE TITLE
Support for linux distribution Debian 11

### ISSUE THREAD

**Issue by Crovitz** [flapdoodle-oss/de.flapdoodle.embed.mongo#375]
Hi, I've the issue about unsupported version of Debian 11 which is currently the newest release of this linux distro, as below:

_Caused by: java.lang.IllegalArgumentException: could not resolve package for Version{5.0.5}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Debian}_

In the code I see:
```
public enum DebianVersion implements Version {
    DEBIAN_10(OsReleaseFiles.osReleaseFileVersionMatches("10")),
    DEBIAN_9(OsReleaseFiles.osReleaseFileVersionMatches("9"));
```

It's any chance for updating the package?
Regards!

**Comment by michaelmosmann** [comment]
@Crovitz there is a new release where debian 11 just uses the debian 10 version

**Comment by Crovitz** [comment]
Thank you so much for quick response and release. Professional approach :)

**Comment by michaelmosmann** [comment]
@Crovitz thanks.. i do my best:)
