### ISSUE TITLE
Embedded mongo doesn't work on Linux aarch64

### ISSUE THREAD

**Issue by mhalbritter** [flapdoodle-oss/de.flapdoodle.embed.mongo#379]
Hello,

i tried to get the embedded Mongo working on linux aarch64, but it fails because the executable is in the wrong format (x64 instead of aarch64)

Version: 3.4.1

```
2022-02-21 13:08:31.011 ERROR   --- [       Thread-1] o.s.b.a.mongo.embedded.EmbeddedMongo     : /tmp/extract-53fe8b9c-b58c-4a46-be49-c07429dd3453extractmongod: /tmp/extract-53fe8b9c-b58c-4a46-be49-c07429dd3453extractmongod: Kann die Datei nicht ausführen.
```

The extracted file is of the wrong architecture:

```
─$ file /tmp/extract-53fe8b9c-b58c-4a46-be49-c07429dd3453extractmongod

/tmp/extract-53fe8b9c-b58c-4a46-be49-c07429dd3453extractmongod: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=bf2a61192e28e72fb12ad9c50a08d9dfc37775b3, not stripped
```

Executing this file in a shell results in:

```
─$ /tmp/extract-53fe8b9c-b58c-4a46-be49-c07429dd3453extractmongod

zsh: fehler im Format der Programmdatei: /tmp/extract-53fe8b9c-b58c-4a46-be49-c07429dd3453extractmongod
```

which translates to "error in the format of the executable: ..."

Is it possible to provide an aarch64 (arm64) compiled version of the mongod binary?

**Comment by michaelmosmann** [comment]
@mhalbritter can you give me some more infos? which os do you use? which mongodb version?

**Comment by michaelmosmann** [comment]
@mhalbritter is this still an issue? please reopen if needed.
