### ISSUE TITLE
spring boot integration future :)

### ISSUE THREAD

**Issue by michaelmosmann** [flapdoodle-oss/de.flapdoodle.embed.mongo#380]
follow up of this discussion: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/378

**Comment by michaelmosmann** [comment]
@wilkinsona .. i am in an hurry, so i add more stuff later

**Comment by michaelmosmann** [comment]
created a repo for this: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring

**Comment by wilkinsona** [comment]
Thanks for this, @michaelmosmann. I've been looking at what it will entail to move over the support. Thus far I've spotted a couple of things:

1. The configuration properties should move out of the `spring.*` namespace to one that you own. This ensures that there won't be any naming clashes and also provides a signal to users about what's providing the support.
2. The use of `local.mongo.port` may need to change. Ideally, I'd like the embedded Mongo support to set `spring.data.mongodb.uri` instead but that has some problems of its own for which I've just opened https://github.com/spring-projects/spring-boot/issues/30067.

**Comment by michaelmosmann** [comment]
@wilkinsona

1. Hmmm.. i think i change this name space but add the spring.* namespace as a fallback to provide smooth transitions..

**Comment by michaelmosmann** [comment]
@wilkinsona at 2.: Do i understand this correctly? You get an URI out of testcontainers? So embedded mongo should als provide an URI instead of just a port?

**Comment by wilkinsona** [comment]
> Hmmm.. i think i change this name space but add the spring.* namespace as a fallback to provide smooth transitions..

We'd much prefer it if you didn't use the `spring.*` namespace, even as a fallback. Instead, it would be possible for your support to provide some metadata (it's a JSON file in the jar) that will provide users with feedback in their IDE and guide them to the new properties. We can of course help with creating that file.

> Do i understand this correctly? You get an URI out of testcontainers?

Yes, that's right. In fact a URI is all we get out of Testcontainers. It comes from [`getReplicaSetUrl`](https://github.com/testcontainers/testcontainers-java/blob/6dea9789db1f970da20fc04d11eb3c5323a8bd4f/modules/mongodb/src/main/java/org/testcontainers/containers/MongoDBContainer.java#L56). It's great as it's a self-contained to get everything that's needed to connect to the Mongo instead. It's not so great as it doesn't work perfectly in all cases but hopefully we can fix that on the Boot side.

> So embedded mongo should als provide an URI instead of just a port?

I think that'll be useful, yes. At the moment, the Embedded Mongo instance could be bound to a specific address and we might then fail to connect to it.

**Comment by michaelmosmann** [comment]
So there is a new repo for that: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring ..
