### ISSUE TITLE
GLIBC_2.29 CURL_OPENSSL_4 not found

### ISSUE THREAD

**Issue by jonathanbenedet** [flapdoodle-oss/de.flapdoodle.embed.mongo#382]
Hi guys, i'm with a problem when running embedded mongo in my jenkins pipeline:
```
07/03/2022 17:34:16 WARN  [main] LinuxPackageFinder:because there is no package for Version{4.4.9}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to Version{4.4.9}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
07/03/2022 17:34:16 ERROR [Thread-9] EmbeddedMongo:/tmp/extract-d4371e64-7f31-456d-b8ee-05d50c1802fcextractmongod: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/extract-d4371e64-7f31-456d-b8ee-05d50c1802fcextractmongod)
07/03/2022 17:34:16 ERROR [Thread-9] EmbeddedMongo:/tmp/extract-d4371e64-7f31-456d-b8ee-05d50c1802fcextractmongod: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /tmp/extract-d4371e64-7f31-456d-b8ee-05d50c1802fcextractmongod)
07/03/2022 17:34:16 WARN  [main] GenericWebApplicationContext:Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: 
```

Local on OSX the problem not happen, only in linux container, any thoughts?

`Spring Boot: 2.6.2`
`de.flapdoodle.embed.mongo: 3.4.3`
`spring.mongodb.embedded.version: 4.4.9`
`Java: 11`

Already tried with `de.flapdoodle.embed.mongo: 3.2.8` and had the same error.

**Comment by michaelmosmann** [comment]
@jonathanbenedet which kind of linux you are using in this container? the fallback is currently ubuntu which would lead to this error..

**Comment by jonathanbenedet** [comment]
I'm using the `maven:3.6.1-jdk-11`(https://hub.docker.com/layers/maven/library/maven/3.6.1-jdk-11/images/sha256-526a0fad13ae8e333f9e263899e822ecf12bc5ab4b1e47268b316075abd9ddfb?context=explore)

**Comment by michaelmosmann** [comment]
@jonathanbenedet the problem with is: as mongodb does not provide a distribution for a generic linux distribution some has to choose which dist to use.. i can not imagine which one should work best inside this docker container..

**Comment by michaelmosmann** [comment]
@jonathanbenedet did you try [testcontainer](https://www.testcontainers.org/modules/databases/mongodb/)?

**Comment by jonathanbenedet** [comment]
@michaelmosmann thanks for the tips. I will try the testcontainer and in last case, use a specific linux dist. By the way, which dists flapdoodle works?

**Comment by michaelmosmann** [comment]
@jonathanbenedet this is whats currently supported: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/main/src/test/resources/de/flapdoodle/embed/mongo/packageresolver/explainedSnapshot.txt (aggregation of all rules) .. but you have to have a look at the mongodb download page to see if you can find a docker image with a matching mongodb dist: https://www.mongodb.com/try/download/community

if nothing matches ubuntu is the fallback.. (until there is something better)

**Comment by jonathanbenedet** [comment]
Okay, thanks!!
