### ISSUE TITLE
Add UbuntuVersion.Ubuntu_22_04 support

### ISSUE THREAD

**Issue by user4me** [flapdoodle-oss/de.flapdoodle.embed.mongo#386]
Hello,

Since I moved to Ubuntu 22.04 i'm unable to launch my unit tests, is it possible to add support of it ?

Thanks for everything

**Comment by michaelmosmann** [comment]
@user4me yes.. will do.

**Comment by flopezgresystems** [comment]
Hello, 

Last week I upgraded to  Ubuntu 22.04 and started suffering from the problem detailed above, I couldn't run my unit tests. 

Mongo requires the **libssl1.1** library and, as it is detailed in the following issue (https://askubuntu.com/questions/1403619/mongodb-install-fails-on-ubuntu-22-04-depends-on-libssl1-1-but-it-is-not-insta), it is deprecated in version Ubuntu 22.04.

Following the steps detailed in the issue, I managed to manually install the library.  

`echo "deb http://security.ubuntu.com/ubuntu impish-security main" | sudo tee /etc/apt/sources.list.d/impish-security.list
sudo apt update
sudo apt install libssl1.1`

Once the library was installed the unit tests started to work.

I hope this approach work for you, as I have done for me, until official support is released.

Regards.

**Comment by FranciscoLopezNavarro** [comment]
Hello, 

Last week I upgraded to  Ubuntu 22.04 and started suffering from the problem detailed above, I couldn't run my unit tests. 

Mongo requires the libssl1.1 library and, as it is detailed in the following issue (https://askubuntu.com/questions/1403619/mongodb-install-fails-on-ubuntu-22-04-depends-on-libssl1-1-but-it-is-not-insta), it is deprecated in version Ubuntu 22.04.

Following the steps detailed in the issue, I managed to manually install the library.  

`echo "deb http://security.ubuntu.com/ubuntu impish-security main" | sudo tee /etc/apt/sources.list.d/impish-security.list`
`sudo apt update`
`sudo apt install libssl1.1`

Once the library was installed the unit tests started to work.

I hope this approach work for you, as I have done for me, until official support is released.

Regards.

**Comment by michaelmosmann** [comment]
@FranciscoLopezNavarro which mongodb version did you use?

**Comment by michaelmosmann** [comment]
@user4me release with 22.04 support is de.flapdoodle.embed.mongo 3.4.5.

**Comment by diegoqueres** [comment]
I added this version, 3.4.5, on pom.xml:
`
		<dependency>
			<groupId>de.flapdoodle.embed</groupId>
			<artifactId>de.flapdoodle.embed.mongo</artifactId>
			<version>$3.4.5</version>
			<scope>test</scope>
		</dependency>
`
On src/test/resources/application.yaml, i've added:
`
spring:
  mongodb:
    embedded:
      version: 3.4.5
`

If you use application.properties, must be: `spring.mongodb.embedded.version=3.4.5`

After these steps, it's working again on my Ubuntu 22.04 system.

**Comment by michaelmosmann** [comment]
@diegoqueres maybe you should switch to https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring .. everthing below de.flapdoodle.embed.mongo:4.0.0 is not maintained anymore ..
