### ISSUE TITLE
Issue with aggregation LookupOperation - when we use _id vs id as foreign key

### ISSUE THREAD

**Issue by jchobantonov-runbuggy** [flapdoodle-oss/de.flapdoodle.embed.mongo#392]
If you have following spring mongo data entities:

```
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class Entity1 {
     @Id
    private String id;
}
```
and this entity : 

```
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class Entity2 {
     @Id
    private String id;
    private List<Entity1> entities1;
}

public class Entity2Full extends Entity2Full
```

Then following do NOT work:
```
        LookupOperation lookup = LookupOperation.newLookup()
                .from("entity1")
                .localField("entities1._id")
                .foreignField("_id")
                .as("entities1Full");

        ....       
        MatchOperation matchOperation = ...

        Aggregation agg = Aggregation.newAggregation(matchOperation, lookup);
        List<Entity2Full> user = mongoTemplate.aggregate(agg, Entity2.class, Entity2Full.class).getMappedResults(); // query Entity2 and link with Entity1

```

If I change the LookupOperation to : 
```
        LookupOperation lookup = LookupOperation.newLookup()
                .from("entity2")
                .localField("entities1.id") //CHANGE _id to id
                .foreignField("id") //CHANGE _id to id
                .as("entities1Full");
       

```

Then it works. 

E.g. changing "_id" to "id" in LookupOperation will make the above working - the issue is that on real mongo the _id works and id do not as it should be.

I have tried to put 
```
    import org.springframework.data.mongodb.core.mapping.Field;

    @Field(name = "_id")
     @Id
    private String id;

```

on the id but this did not solve the issue - only when I put id and not _id it will work

**Comment by jchobantonov-runbuggy** [comment]
FYI following operation works correctly : 

```
mongoTemplate.count(new Query(Criteria.where("entities1._id").is("ent1")), "entity2")
```
e.g. using entities1._id works and entities1.id do not which is the correct way but for LookupOperation the usage of _id do not work - only id works

here is the aggregation query using LookupOperation: 
```
[{ "$match" : { "_id" : "ent2"}}, { "$lookup" : { "from" : "entity1", "localField" : "entities1._id", "foreignField" : "_id", "as" : "entities2Full"}}]
```

this has been tested against 3.4.5 version of de.flapdoodle.embed.mongo

**Comment by michaelmosmann** [comment]
@jchobantonov-runbuggy .. maybe you should report this issue in here https://github.com/spring-projects/spring-data-mongodb/issues

**Comment by michaelmosmann** [comment]
@jchobantonov-runbuggy maybe there is a little confusion.. this project does NOT create a "memory enbed mongo" (i just guess that you might expect some in-memory implementation of some mongodb compatible server thing). It is a official mongodb database with code from mongodb which is started as a process and cleaned after stopped. I suspect that the mongodb version used is just different. This project does NOT interfere with any spring abstraction over mongodb driver stuff. It just downloads the needed archive from mongodb.com, extracts the binary, starts the binary and.. if whatever is done is ready .. stops the binary and cleans up. I hope this makes things a little bit more understandable.

So just check if the mongodb version is the same in all situations.

**Comment by n4kong** [comment]
@jchobantonov-runbuggy Hi, i got same issue, and resolved by change mongodb version in the test application.properties

`spring.mongodb.embedded.version=4.0.2`

**Comment by sbg-sh** [comment]
> @jchobantonov-runbuggy Hi, i got same issue, and resolved by change mongodb version in the test application.properties
> 
> `spring.mongodb.embedded.version=4.0.2`

Hello @n4kong ,
I have the same issue but it does not work for me, could you please tell more details.
