### ISSUE TITLE
Extraction does not respect EMBEDDED_MONGO_ARTIFACTS environment variable

### ISSUE THREAD

**Issue by TamasSzerb** [flapdoodle-oss/de.flapdoodle.embed.mongo#394]
Hello,

As the downloader respect, the extraction should also respect same way the EMBEDDED_MONGO_ARTIFACTS env var, and should extract it under $EMBEDDED_MONGO_ARTIFACTS and should run it from there.

**Comment by michaelmosmann** [comment]
@TamasSzerb i did a rework of this project.. maybe the new version solves your issue: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/tree/embed-mongo-4.x

so i close this issue .. reopen if needed.
