### ISSUE TITLE
MacOS Quarkus & Embedded MongoDB Issue

### ISSUE THREAD

**Issue by v-shalimov** [flapdoodle-oss/de.flapdoodle.embed.mongo#397]
### Discussed in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/discussions/396

<div type='discussions-op-text'>

<sup>Originally posted by **v-shalimov** April 27, 2022</sup>
I am developing using Quarkus on MacBook Pro. When I used Quarkus version 2.7.1-Final with embedded MongoDB (de.flapdoodle.embed.mongo) version 3.2.0 included - everything was OK. But when I upgrade it to the latest version (2.8.1-Final) with embedded MongoDB version 3.3.0 I am constantly getting an error:
```
Extract /Users/vshalimov/.embedmongo/tools/db/mongodb-database-tools-macos-x86_64-100.5.1.zip START
2022-04-22 13:00:03,524 WARN  [de.fla.emb.pro.ext.AbstractExtractor] (main) 
--------------------------
If you get this exception more than once, you should check if the file is corrupt.
If you remove the file (/Users/vshalimov/.embedmongo/tools/db/mongodb-database-tools-macos-x86_64-100.5.1.zip), it will be downloaded again.
--------------------------: java.io.IOException: Input is not in the .gz format
```
Will be very thankful for any assistance in that regard.</div>

**Comment by v-shalimov** [comment]
Resolved

**Comment by v-shalimov** [comment]
> @v-shalimov ah.. thanks .. can you have a look if `/Users/vshalimov/.embedmongo/tools/db/mongodb-database-tools-macos-x86_64-100.5.1.zip` does contain anything?

yep, MongoDB Tools.
<img width="637" alt="image" src="https://user-images.githubusercontent.com/12111065/168886608-e6c334a4-35e0-4695-bb89-aa305d72540d.png">

**Comment by michaelmosmann** [comment]
@v-shalimov hmm... will have a look

**Comment by michaelmosmann** [comment]
@v-shalimov is this still an issue?

**Comment by michaelmosmann** [comment]
@v-shalimov .. will close this issue. If needed, just reopen.
