### ISSUE TITLE
Cannot build from source for the lack of toolchains.xml

### ISSUE THREAD

**Issue by ZeroOne3010** [flapdoodle-oss/de.flapdoodle.embed.mongo#401]
Hello,

I tried forking the repo and building the project from the source according to the instructions, i.e. with the `mvn package` command. However, it fails with the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-toolchains-plugin:3.0.0:toolchain (default) on project de.flapdoodle.embed.mongo: Cannot find matching toolchain definitions for the following toolchain types:
[ERROR] jdk [ version='[1.8,)' ]
[ERROR] Please make sure you define the required toolchains in your ~/.m2/toolchains.xml file.
[ERROR] -> [Help 1]
```

What are the required toolchain definitions? This is the first time I run into this toolchain tool.

**Comment by michaelmosmann** [comment]
@ZeroOne3010 have a look at this one: https://maven.apache.org/guides/mini/guide-using-toolchains.html ..

i use this to compile the project with an real jdk8 compiler

...
`  <toolchain>
    <type>jdk</type>
    <provides>
      <version>1.8</version>
    </provides>
    <configuration>
      <jdkHome>/usr/lib/jvm/java-8-openjdk-amd64</jdkHome>
    </configuration>
  </toolchain>
`
