### ISSUE TITLE
windows: Embedded mongodb processes remains active after test run in Maven

### ISSUE THREAD

**Issue by ThomasAtAcerta** [flapdoodle-oss/de.flapdoodle.embed.mongo#405]
Hello,

I've got a very annoying problem using embedded mongodb. 
Setup:
`<mongo-embedded-version>3.4.6</mongo-embedded-version>`
Java 11
Maven 3.6.3
Spring-boot 2.6.6
Spring-cloud 3.2.4
Windows 10
spring.mongodb.embedded.version=4.2.19

I'm not a local admin on the machine, maybe related but I don't know.

The problem is that the extract-<uuid>extractmongod.exe process gets spawned by the tests but afterwards won't go away.  It then eats my CPU and I have to kill the processes (8+ of them) manually.  See attached screenshot.
The problem occurs half of the time I run the tests in the project using Maven.  My colleague using a Mac does not seem to have a similar problem.

![embedmongo-issue](https://user-images.githubusercontent.com/104349047/172820061-8f8a9807-0821-4ebf-90da-5217fc5a3a0f.jpg)

**Comment by michaelmosmann** [comment]
@ThomasAtAcerta is your code public? IMHO the shutdown does not work as expected.. the processes are not killed. maybe you should add @DirtiesContext to your test

**Comment by ThomasAtAcerta** [comment]
@michaelmosmann The code is not public.  The issue occurs with tests in combination with:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-maven-intellij
and
https://docs.microsoft.com/en-us/samples/azure-samples/hello-spring-function-azure/hello-spring-function-azure/

Likely the way the Spring context is constructed has something to do with it.

There's a workaround I found using 
`            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <forkCount>1</forkCount>
                    <reuseForks>false</reuseForks>
                </configuration>
            </plugin>
`

Especially the reuseForks seems to help, but it does have a significant impact on the test performance.

**Comment by behindsun** [comment]
before start server, setDaemonProcess true,then everingthing is ok, process will be killed when jvm stop
ImmutableRuntimeConfig.Builder.isDaemonProcess(true)

**Comment by michaelmosmann** [comment]
hmm.. this is strange... there is a refactoring ahead.. to solve this kind of issues.. but not in the next days.

**Comment by michaelmosmann** [comment]
@behindsun there are new releases, so if this is still an issue, please reopen:)
