### ISSUE TITLE
Embed mongo does not start when running single test using IDEA

### ISSUE THREAD

**Issue by ArchitektDieWelt** [flapdoodle-oss/de.flapdoodle.embed.mongo#407]
Hi everyone, Im new to Kotlin and Spring environment, so its possible its not really an issue per se.

I installed flapddodle.embed.mongo in my Kotlin Spring Boot project based on Maven:

`<dependency>
			<groupId>de.flapdoodle.embed</groupId>
			<artifactId>de.flapdoodle.embed.mongo</artifactId>
			<scope>test</scope>
			<version>3.4.6</version>
		</dependency>`

Then I set in my test/application.properties embedded mongo version as follows:

```
spring.profiles.active=test
spring.mongodb.embedded.version=3.4.6
```

When i run tests using mvn test lifecycle function in IDEA, embedded mongo starts and all the tests pass.
However, when I try to run single test from my IDEA by click on the play button next to test or Test class, the tests fail because connection to mongo is refused ( as no embedded mongo instance is started in this case, its not even trying to start embedded mongo ).

Is it something that needs to be configured or its how its expected to work?

**Comment by michaelmosmann** [comment]
@ArchitektDieWelt is your code public so i can have a look?

**Comment by michaelmosmann** [comment]
.. as there a no news on this issue, i will close this. reopen if needed:)
