### ISSUE TITLE
Authentication Error When Using mongoTemplate.

### ISSUE THREAD

**Issue by vam012** [flapdoodle-oss/de.flapdoodle.embed.mongo#408]
I am running into an issue when trying to use this library with MongoTemplate in the test suite for my SpringBoot project.  In one of my services we have an auto-wired MongoTemplate bean that will drop and restore views on service initialization.  But when the call is made to ensure if a collection exists, the error

`Caused by: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='${MONGO_USER}', source='admin', password=<hidden>, mechanismProperties=<hidden>}`

is thrown.  I've tried supplying a dummy username/password such as <username/password> or <admin/password> but the same error occurs.

Any ideas why this may be occurring or any ideas how to resolved this would be greatly appreciated.

OS: Windows
Flapdoodle Version: 3.4.6
MongoDB zip version: 3.5.5

**Comment by michaelmosmann** [comment]
Do you use any auth stuff in your spring boot setup?

**Comment by vam012** [comment]
Hey sorry, yeah I use auth on the production instance.  I tried overwriting those variables in the test properties file or just omitting them but it seems to still occur.

**Comment by vam012** [comment]
spring.data.mongodb.host=<db_host>
spring.data.mongodb.port=<port>
spring.data.mongodb.database= <db_name>
spring.data.mongodb.username=<username>
spring.data.mongodb.password=<password>
spring.data.mongodb.authentication-database=<authentication_database>

Example spring properties used in prod /\
=============================================
Example spring properties attempted to run test suites with \/

spring.data.mongodb.host=localhost
spring.data.mongodb.port=0
spring.data.mongodb.database=tests
spring.mongodb.embedded.version=3.5.5

**Comment by vam012** [comment]
New test properties file:

`spring.data.mongodb.host=localhost`
`spring.data.mongodb.port=0`
`spring.data.mongodb.database=tests`
`spring.mongodb.embedded.version=3.5.5`
`spring.data.mongodb.username=`
`spring.data.mongodb.password=`

Same issue occurs:

`
java.lang.IllegalStateException: Failed to load ApplicationContext
.....
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bizCardController': Unsatisfied dependency expressed through field 'bizCardService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bizCardService': Unsatisfied dependency expressed through field 'positionService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'positionService': Unsatisfied dependency expressed through field 'employeeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Invocation of init method failed; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}
......
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bizCardService': Unsatisfied dependency expressed through field 'positionService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'positionService': Unsatisfied dependency expressed through field 'employeeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Invocation of init method failed; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}
.....
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'positionService': Unsatisfied dependency expressed through field 'employeeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Invocation of init method failed; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}
.....
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Invocation of init method failed; nested exception is org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}
.....
Caused by: org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}
.....
Caused by: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='', source='admin', password=<hidden>, mechanismProperties=<hidden>}
....
Caused by: com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server localhost:60530. The full response is {"ok": 0.0, "errmsg": "Authentication failed.", "code": 18, "codeName": "AuthenticationFailed"}
`

**Comment by michaelmosmann** [comment]
@vam012  .. and removing username+password from prod-properties is working?

**Comment by vam012** [comment]
I cannot remove those properties b/c our prod database requires authentication.

**Comment by vam012** [comment]
Is there anyway to tell embedMongo to spin up a mongo instance without authentication required?  Since that is what appears to be causing the problem.

**Comment by michaelmosmann** [comment]
hmm.. the mongodb instance does not expect any auth unless configured.. but i will try create an test in this project: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring

**Comment by vam012** [comment]
> .. just to test if the tests runs.. not as a permanent solution.

If I remove them then the test is able to run.

**Comment by michaelmosmann** [comment]
ah.. so i guess that if the driver tries to connect with out an mongodb without out will deny access

**Comment by vam012** [comment]
So is there a way to avoid this?

**Comment by michaelmosmann** [comment]
@vam012 hmm.. the only way to fix this: make your test-mongodb use auth too.. but this will not come out of the box. 
or add the auth information on deployment .. hmm... 

I am very busy .. so it will take time to add some kind of support to my version of spring integration.. but i am not sure how long you can wait.

**Comment by vam012** [comment]
How would I go about adding auth to the deployment of the test db?  That's currently handled by this package.

**Comment by michaelmosmann** [comment]
@vam012 which spring version do you use? i have done my refactoring and could add this feature:)

**Comment by vam012** [comment]
Currently I use spring-boot-starter-parent version 2.6.2.

**Comment by michaelmosmann** [comment]
ok.. thanks.. stay tuned. i will write to this ticket if i have finished this.

**Comment by michaelmosmann** [comment]
Hi.. i did a new release.. 
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.6.x--embed-mongo-4.x

There should be an 4.0.0-beta in maven central in about 12 hours.. 

It works this way: if spring...username and spring...passwd is set, it will start a mongodb instance and after that a matching user is created.

If anything does not work as expected, please write a comment. I will try to fix this as soon as possible.

**Comment by vam012** [comment]
Hi.... I tried with beta 4.0.0, 4.0.1, and 4.0.2.  When running I now get this error:

`java.lang.IllegalStateException: Failed to load ApplicationContext`

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bizCardController': Unsatisfied dependency expressed through field 'bizCardService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bizCardService': Unsatisfied dependency expressed through field 'positionService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'positionService': Unsatisfied dependency expressed through field 'employeeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]`

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bizCardService': Unsatisfied dependency expressed through field 'positionService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'positionService': Unsatisfied dependency expressed through field 'employeeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]`

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'positionService': Unsatisfied dependency expressed through field 'employeeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]`

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'employeeService': Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]`

`Caused by: org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]`

`Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:0, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.BindException: Cannot assign requested address: connect}}]`

**Comment by michaelmosmann** [comment]
@vam012 hmmmm.. address=localhost:0 looks .. funny.. can you see if the mongod server starts?

**Comment by vam012** [comment]
How can I check that?

**Comment by michaelmosmann** [comment]
@vam012 is there anything else in the log? i can only see spring exceptions .. 
you can try to set a breakpoint somewhere in the spring integration code..

**Comment by toritsejuFO** [comment]
Hi @michaelmosmann. I encountered the same issue. Seems embedded mongo is configured to require auth, and there's no way to disable auth for tests. When I leave username and password as empty, I get an error in creating the bean, and it propagates the error upwards. When I put a random username and password, it fails with 

```java
org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 13 (Unauthorized): 'command find requires authentication' on server localhost:60826. The full response is {"ok": 0.0, "errmsg": "command find requires authentication", "code": 13, "codeName": "Unauthorized"}
```

**Comment by michaelmosmann** [comment]
@toritsejuFO i have created an issue for your problem: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/issues/14 .. can you tell me there which spring and mongodb version you are using?

**Comment by toritsejuFO** [comment]
Major version Spring Framework is 6, boot is 3.0.1, flapdoodle is4.41.

**Comment by michaelmosmann** [comment]
@toritsejuFO is your repo somehow public? .. maybe i have to create some setup to see if this works as expected..
.. but we should discuss this here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/issues/14 :)

**Comment by toritsejuFO** [comment]
No, it's not public.

So, I had to comment out spring data mongo config entirely from application.yml and application-test.yml for it to work. So I'm guessing, when the username and password config isn't in the test profile, it picks up the one in application.yml and does a merge, but fails, because that is empty.

This means I'd have to set these config in the different profile yml files, and not in application at all.

**Comment by michaelmosmann** [comment]
@toritsejuFO AFAIK you can not disable auth in test only, as spring merges both configs .. but i tried to make this work... i think i have somewhere a working example

**Comment by michaelmosmann** [comment]
@toritsejuFO i have a canary project to see if my implementation works with spring2.6.x, spring2.7.x and spring3.0.x .. https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary .. there is a minimal example, where (and i think this is just your case) in application.yml username/password is set.. 

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary

you can try this by yourself and see if this works.. and whats the difference to your project

**Comment by toritsejuFO** [comment]
Alright, thanks @michaelmosmann. I'll check it out and give you feedback. Appreciate the timely responses.

**Comment by michaelmosmann** [comment]
@toritsejuFO your welcome:)

**Comment by NazarDovgiyTrach** [comment]
Hi! I faced a such issue: 
 I specified the auth properties in the test application.yml
 `spring: data:  mongodb: username: test password: test`
therefore embedded mongo creates a new user:
 `INFO [main] de.flapdoodle.embed.mongo.spring.autoconfigure.AbstractServerFactory [TRXID:] [MSISDN:] --- credentials: Optional.empty, action: RunCommand{database=admin, command=Document{{createUser=test, pwd=test, roles=[root]}}}`, and it works fine for a single test class but when I run several tests in a row, it fails:
 `RunCommand{database=admin, command=Document{{createUser=test, pwd=test, roles=[root]}}} failed`,
 `Command failed with error 13 (Unauthorized): 'command createUser requires authentication' on server kubernetes.docker.internal:27017. The full response is {"ok": 0.0, "errmsg": "command createUser requires authentication", "code": 13, "codeName": "Unauthorized"}`.

Spring boot: 3.0.3, flapdoodle: 4.6.1
 
Thanks!

**Comment by michaelmosmann** [comment]
@NazarDovgiyTrach did you annotate your class with @DirtiesContext so that for each test a new mongodb instance is created?

**Comment by NazarDovgiyTrach** [comment]
> @NazarDovgiyTrach did you annotate your class with @DirtiesContext so that for each test a new mongodb instance is created?

Using @DirtiesContext helped. But is it possible to use a single mongodb instance without trying to create a new user or disable authentication altogether?

**Comment by michaelmosmann** [comment]
@NazarDovgiyTrach AFAIK spring uses user/passwd if set to connect to the mongodb .. as properties are merged there is AFAIK no way to remove user/passwd from tests .. if you find a way, let me know:) .. so if you have user/passwd in your spring properties i must enable authenticated access to the database .. so there is IMHO no way around it.

**Comment by michaelmosmann** [comment]
@NazarDovgiyTrach .. reusing an mongod instance across tests is IMHO not possible with spring in an reproducible way.. the best you will get is an instance per testclass.. so if you put more tests in one clase it might speedup the test run a little bit

**Comment by NazarDovgiyTrach** [comment]
I see, thanks for your help)

**Comment by cskarapapas** [comment]
Hello @michaelmosmann, we are facing the same issue 
```
org.springframework.data.mongodb.UncategorizedMongoDbException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='root', source='admin', password=<hidden>, mechanismProperties=<hidden>}; nested exception 
is com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='root', source='admin', password=<hidden>, mechanismProperties=<hidden>}
...
        Caused by:
        com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='root', source='admin', password=<hidden>, mechanismProperties=<hidden>}

...
Caused by:
            com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "Authentication failed.", "code": 18,
 "codeName": "AuthenticationFailed"}```
```
We have tried to set the properties in both of the following ways, but we are getting the same error.

@ActiveProfiles("int")
@DirtiesContext
@DataMongoTest(properties = {
        "spring.cloud.config.enabled=false",
        "server.ssl.enabled=false",
        "management.server.ssl.enabled=false",
        "de.flapdoodle.mongodb.embedded.version=4.6.3",
        "spring.data.mongodb.uri=mongodb://root:example@localhost:27017/SampleDB?authSource=admin&authMechanism=SCRAM-SHA-1"})
```

Is this a known issue? 
Are there standard credentials that we need to use to be able to connect to the embedded mongoDB?


```
@ActiveProfiles("int")
@DirtiesContext
@DataMongoTest(properties = {
        "spring.cloud.config.enabled=false",
        "server.ssl.enabled=false",
        "management.server.ssl.enabled=false",
        "de.flapdoodle.mongodb.embedded.version=4.6.3",
        "spring.data.mongodb.authMechanism=SCRAM-SHA-1",
        "spring.data.mongodb.authentication-database=admin",
        "spring.data.mongodb.port=27017",
        "spring.data.mongodb.database=SampleDB",
        "spring.data.mongodb.username=root",
        "spring.data.mongodb.password=example"})
```
Our configuration:
```
implementation group: 'org.springframework.boot', name: 'spring-boot-starter-data-mongodb', version: '2.3.12.RELEASE'
implementation group: 'org.mongodb', name: 'mongo-java-driver', version: '3.12.8' 
testImplementation group: 'de.flapdoodle.embed', name: 'de.flapdoodle.embed.mongo', version: '4.6.3'
```

**Comment by michaelmosmann** [comment]
@cskarapapas which spring version do you use?

**Comment by cskarapapas** [comment]
@michaelmosmann We have tried mainly with 2.3.12.RELEASE and many versions up to 2.6.3 but the behavior remains the same.

**Comment by michaelmosmann** [comment]
@cskarapapas as i have spring integrations from 2.5.x fo 3.1.x you should use 2.6.x as this is not that old. A minimal setup can be found here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary
