### ISSUE TITLE
Incorrect packageresolver version

### ISSUE THREAD

**Issue by infoShare** [flapdoodle-oss/de.flapdoodle.embed.mongo#411]
Version: 3.4.6

Maven is trying to get packageresolver in version 1.0.6- SNAPSHOT but last release is 1.0.5

[INFO] --- maven-dependency-plugin:2.1:get (default-cli) @ standalone-pom ---
Downloading from temp: https://repo.maven.apache.org/maven2/de/flapdoodle/embed/de.flapdoodle.embed.mongo.packageresolver/jar/de.flapdoodle.embed.mongo.packageresolver-jar.1.0.6-SNAPSHOT

Maybe it would be good to use here only existing versions - [1.0.3,1.0.5] instead of [1.0.3,1.1.0) ?

```
<dependency>
  <groupId>de.flapdoodle.embed</groupId>
  <artifactId>de.flapdoodle.embed.mongo.packageresolver</artifactId>
  <version>[1.0.3,1.1.0)</version>
</dependency>
```

**Comment by infoShare** [comment]
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/412

**Comment by michaelmosmann** [comment]
Hmm.. as i understand it, snapshots should not be included in version ranges. but i remember that there were troubles in past times.. maybe i must switch back to no-version-ranges at all.

**Comment by infoShare** [comment]
Yeah @michaelmosmann. Stable versions = stable builds = less troubles !
