### ISSUE TITLE
Avoid re-downloading installation archives

### ISSUE THREAD

**Issue by stefanbethke** [flapdoodle-oss/de.flapdoodle.embed.mongo#414]
There should be documentation that clearly shows:
* which paths should be cached between executions, so the same archive is not downloaded repeatedly
* how to configure a different URL for downloading the archive(s), so projects can use their own mirror

**Comment by michaelmosmann** [comment]
@stefanbethke please use my new version of this tool.

configure a different url: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/embed-mongo-4.x/Howto.md#customize-by-builder

Now there we use hashes to solve this issue. Archives are only downloaded once..
