### ISSUE TITLE
Flapdoodle  error for embaded MongoDB

### ISSUE THREAD

**Issue by henok-tesfa-kr** [flapdoodle-oss/de.flapdoodle.embed.mongo#419]
### Discussed in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/discussions/418

<div type='discussions-op-text'>

<sup>Originally posted by **henok-tesfa-kr** August  4, 2022</sup>
Hi All
 I am onboarding with existing spring project that use embedded mongoDB which use flapdoodle  on MacBook Pro and getting this issue, is there any solution for this error?
   
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' threw exception; nested exception is de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOException: Could not open inputStream for https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-3.5.5.tgz with proxy Optional.empty</div>

**Comment by michaelmosmann** [comment]
@henok-tesfa-kr is this still an issue? reopen if needed.

**Comment by henok-tesfa-kr** [comment]
Hi @michaelmosmann , Yes it is still  an issue, you have seen multiple ppl are also reporting this, but for now I have a workaround not a solution.

**Comment by michaelmosmann** [comment]
@henok-tesfa-kr what is your workaround? "Could not open inputStream for .." is some kind of network issue. Is there a firewall?

you could also check if my new version does behave different: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.6.x--embed-mongo-4.x

**Comment by santik** [comment]
For me it is definitely a firewall. I'm wondering if I can pack that file into my application jar. #428

**Comment by michaelmosmann** [comment]
@santik  hmm.. its a little big i guess...
