### ISSUE TITLE
Unable to run embedded Mongo instance on Linux Mint after upgrade to Mint 21.

### ISSUE THREAD

**Issue by TimTim74** [flapdoodle-oss/de.flapdoodle.embed.mongo#421]
I upgraded my Linux Mint from version 20.3 to 21 to other day. And now my tests are failing:

```
Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' threw 
exception; nested exception is java.lang.IllegalArgumentException: could not resolve 
package for Version{5.0.6}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=LinuxMint}
```

POM.xml has this dependency:

```
<dependency>
   <groupId>de.flapdoodle.embed</groupId>
   <artifactId>de.flapdoodle.embed.mongo</artifactId>
   <version>3.4.6</version>
</dependency>
```

And I am trying to run Mongo 5.0.6.

**Comment by michaelmosmann** [comment]
@TimTim74 as there is no entry in https://github.com/flapdoodle-oss/de.flapdoodle.os/blob/main/src/main/java/de/flapdoodle/os/linux/LinuxMintVersion.java for mint 21 there is which package to use..  i have to add this version or.. if you like, you can create an pull request.

**Comment by michaelmosmann** [comment]
@TimTim74  If this still is an issue, please reopen.
