### ISSUE TITLE
could not stop mongod with db command if auth is enabled

### ISSUE THREAD

**Issue by lilithyang2018** [flapdoodle-oss/de.flapdoodle.embed.mongo#423]
version: 3.4.8

description:
when auth is enabled for the mongo server, the mongod could not be stopped properly

[https://www.mongodb.com/docs/manual/reference/command/shutdown/#behavior](url)

from the above link , we know that 'For a mongod started with Authentication, you must run shutdown over an authenticated connection.'

from the code it seems the username and password are never sent
![send stop to mongo instance](https://user-images.githubusercontent.com/39897706/191433163-bdd215ac-d397-42f2-b52d-cb5bc3168c44.png)

**Comment by michaelmosmann** [comment]
Ah.. yes.. you are right. Try to solve this next week:)

**Comment by michaelmosmann** [comment]
@lilithyang2018 which integration are you using? how do you enable auth for mongodb?

**Comment by michaelmosmann** [comment]
@lilithyang2018 did a new release of https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.7.x--embed-mongo-4.x and https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.6.x--embed-mongo-4.x which should handle this case..

**Comment by michaelmosmann** [comment]
@lilithyang2018 if you have any problems trying the new stuff give me a hint:)

**Comment by michaelmosmann** [comment]
@lilithyang2018 .. did it work? reopen if the issue still exists.
