### ISSUE TITLE
Add support for mongodb 6.0

### ISSUE THREAD

**Issue by chrismgrayftsinc** [flapdoodle-oss/de.flapdoodle.embed.mongo#424]
There are some new features in version 6.0 that I would like to test my server with.  https://www.mongodb.com/docs/upcoming/release-notes/6.0-changelog/

**Comment by michaelmosmann** [comment]
Will add this next week:)

**Comment by michaelmosmann** [comment]
@chrismgrayftsinc  did a new release ... mongodb 6.0.1 is now supported..

**Comment by Lucasark** [comment]
> @chrismgrayftsinc did a new release ... mongodb 6.0.1 is now supported..

Simple question, on Maven Repository still on 3.4.x, is there any reason?
https://mvnrepository.com/artifact/de.flapdoodle.embed/de.flapdoodle.embed.mongo

**Comment by michaelmosmann** [comment]
@Lucasark it takes some time so that the sonatype repo is synced to maven central..

**Comment by michaelmosmann** [comment]
@chrismgrayftsinc mongodb 6.0.1 and 6.0.2 support released.

**Comment by chrismgrayftsinc** [comment]
Much appreciated! @michaelmosmann
