### ISSUE TITLE
Could not start process: <EOF> (with MongoDB 4.2.13, running on Linux Debian 11, inside a Docker Container)

### ISSUE THREAD

**Issue by acarlstein** [flapdoodle-oss/de.flapdoodle.embed.mongo#426]
# Summary

While our Spring Boot service runs locally (on macOS Monterey 12.6), and in the cloud (with Cloud Run), it fails when running inside a Docker container with Docker Desktop 4.12.0

_Note: I apologize if this issue is a little long. I'm trying to provide as much information as I'm allowed in hopes that a solution can be reached._

# Description

We are getting this logs only when running our Spring Boot app on a Docker container. When we run it locally or in the cloud it works fine.

## Logs
_Note: For security purposes, I can only show some parts of the logs and applied obfuscation using `xxx`._

> Download V4_2:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Debian, version=DEBIAN_11} DONE
Extract /root/.embedmongo/linux/mongodb-linux-x86_64-debian10-4.2.13.tgz START
Extract /root/.embedmongo/linux/mongodb-linux-x86_64-debian10-4.2.13.tgz extract mongodb-linux-x86_64-debian10-4.2.13/bin/mongod
Extract /root/.embedmongo/linux/mongodb-linux-x86_64-debian10-4.2.13.tgz nothing left
Extract /root/.embedmongo/linux/mongodb-linux-x86_64-debian10-4.2.13.tgz DONE

> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sampleController' defined in URL [jar:file:/app/classpath/xxx-latest-plain.jar!/com/xxx/xxx/xxx/SampleController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoTemplate' defined in class path resource [com/xxx/xxx/xxx/config/EmbeddedMongoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.core.MongoTemplate]: Factory method 'mongoTemplate' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not start process: <EOF>

> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoTemplate' defined in class path resource [com/xxx/xxx/xxx/config/EmbeddedMongoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.core.MongoTemplate]: Factory method 'mongoTemplate' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not start process: <EOF>

> Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.core.MongoTemplate]: Factory method 'mongoTemplate' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not start process: <EOF>

> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not start process: <EOF>

## build.gradle.tks

```bash
    implementation("org.springframework.boot:spring-boot-starter-data-mongodb")
    implementation("de.flapdoodle.embed:de.flapdoodle.embed.mongo:3.4.8")
    implementation("de.flapdoodle.embed:de.flapdoodle.embed.mongo.packageresolver:1.0.7")
```

### application-local.yml

```bash
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: test
            authentication-database: none
```

### EmbeddedMongoConfig.kt

```bash
lass EmbeddedMongoConfig(
    @Autowired private val properties: MongoProperties
) {
    @Bean
    fun embeddedMongoRuntimeConfig(): RuntimeConfig {
        val command = Command.MongoD

        val downloadConfig = Defaults.downloadConfigDefaults()
            .packageResolver(PlatformPackageResolver(command))
            .proxyFactory(HttpProxyFactory("internet.ford.com", 83))
            .fileNaming(UserTempNaming())
            .build()

        val artifactStore = Defaults.extractedArtifactStoreFor(command)
            .withDownloadConfig(downloadConfig)

        val runtimeConfig = Defaults.runtimeConfigFor(command)
            .processOutput(ProcessOutput.silent())
            .artifactStore(artifactStore)
            .build()

        assert(runtimeConfig != null)

        return runtimeConfig
    }

    @Bean
    fun embeddedMongoConfiguration(): MongodConfig {
        val config = MongodConfig.builder()
            .version(Version.Main.V4_2)
            .net(Net(properties.port, Network.localhostIsIPv6()))
        return config.build()
    }

    @Bean
    fun mongoTemplate(): MongoTemplate {
        return MongoTemplate(this.mongoClient(), properties.database)
    }

    @Bean
    fun mongoClient(): MongoClient {
        return MongoClients.create("mongodb://localhost:${properties.port}")
    }
}
```
_Note: When using breaking points, we can see that the properties are setup correctly._

### MongoProperties
```bash
@Configuration
@ConfigurationProperties(prefix = "mongo")
class MongoProperties {
    var host: String = "localhost"
    var port: Int = 27017
    var database: String = "test"
    var username: String = ""
    var password: String = ""
    var certificate: String? = null
}
```

# What We Tried

We tried many suggested solutions found by reading the closed issues here, visiting StackOverflow, and searching online in general.

We added configuration such as:

## Adding these to `application.yml`:
```bash
  mongodb:
    embedded:
      version: 4.2.13
      features: ONLY_WITH_SSL, ONLY_64BIT, NO_HTTP_INTERFACE_ARG
```

```bash
    mongodb:
        embedded:
            version: 4.2.13
```

## Adding Environment Variables

`export os.arch=x86_64`
`System.setEnv("os.arch", "x86_64")`

## Other solutions 
We tried many things that we can't include here because we don't remember and we would have to find the articles, posts, issues, to do so. So, we apologize. 

# What would be nice to have

It would be nice to have more content in the logs that can help to pinpoint the issue.
Perhaps a property that can be added so this dependency could provide such information.

# Thanks

Thank you for taking a look at this issue. Much appreciated.

**Comment by michaelmosmann** [comment]
as a first guess: dependency collision

are you sure that spring-boot-starter-data-mongodb does not come with an other version of de.flapdoodle.embed.mongo?
Maybe you don't need de.flapdoodle.embed.mongo.packageresolver as extra dependency..

**Comment by michaelmosmann** [comment]
@acarlstein btw.. this long issue is awesome:)

**Comment by acarlstein** [comment]
I found the issue!!! 

By removing this line: `.processOutput(ProcessOutput.silent())`, I got access to more logs. One of them was:
```bash
[mongod error]/tmp/extract-62b5eb9e-811f-40bb-a523-2fb7132bf82eextractmongod: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

This told me right away that a quick fix would be to install `curl`.
So, to test it out, I shell into the container, run:
```bash
apt-get update
apt-get install curl

**Comment by michaelmosmann** [comment]
@acarlstein it would be interesting why mongodb needs libcurl ..
