### ISSUE TITLE
Is it possible to download the mongo during the build?

### ISSUE THREAD

**Issue by santik** [flapdoodle-oss/de.flapdoodle.embed.mongo#428]
Until we don't have a real mongo in our system we decided to use embedded mongo, but when we run our application it tries to download the package to start the server. Our infra by default doesn't allow any external connections. Is it possible to download all the necessary packages during the build so that when the application starts up it doesn't need to download anything extra?

**Comment by michaelmosmann** [comment]
@santik .. as there are more than one possible solution, can you explain your use case a little bit? If your application is build, is it deployed somewhere?

- If external connections are not allowed, you could put these files on an internal server an change the download location...
- You could setup a proxy and enable just the download of the mongodb archives.. 
- You could copy local downloaded files to the server where the application runs..

As i did some "breaking" changes into the new version of this tool, the way i store the downloads have changed. Maybe this could be beneficial in this situation, as i use hashes do avoid collisions.

**Comment by santik** [comment]
@michaelmosmann I managed to use the 3rd option from your list. The potential problem could be when the filename changes in the resolver.  Also, the archive with the file is too big to put in repo. So still would be nice to download the file during the compilation rather than during the test phase.

**Comment by michaelmosmann** [comment]
@santik do you use gradle, maven .. something different?

As i understand this, and please correct me if i am wrong:
- you build this application somewhere where the download of the archives is possible
- you deploy your application somewhere else (for testing) where downloads are forbidden
- it would be nice if during the build the archive is downloaded and can be deployed with your application
- the running application should use the deployed archive

.. or do i miss the point?

**Comment by michaelmosmann** [comment]
@santik is this still an issue?

**Comment by michaelmosmann** [comment]
I will close this issue... please reopen if needed.
