### ISSUE TITLE
Ubuntu 22.10 support is missing

### ISSUE THREAD

**Issue by mmuruev** [flapdoodle-oss/de.flapdoodle.embed.mongo#431]
Test just failed on the start no support Ubuntu 22.10

 `de.flapdoodle.embed:de.flapdoodle.embed.mongo:3.5.1`

**Comment by mmuruev** [comment]
Found new version. Sorry !

**Comment by michaelmosmann** [comment]
@mmuruev alway like self closing issues:) .. have fun:)
