### ISSUE TITLE
Cannot run mongo on amazoncorretto:17-al2-jdk build

### ISSUE THREAD

**Issue by mmuruev** [flapdoodle-oss/de.flapdoodle.embed.mongo#435]
Seems weird I just changed from openjdk 11 and got this error

` Caused by:
                    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not start process: `

`         Caused by:
                        java.lang.RuntimeException: Could not start process: 
                        ----------------------
                        Hmm.. no failure message.. 
                        ...the cause must be somewhere in the process output
                        ----------------------
`

**gradle.build**
`testImplementation 'de.flapdoodle.embed:de.flapdoodle.embed.mongo:3.5.3'`

Not really clear why it failed.

**Comment by michaelmosmann** [comment]
@mmuruev is there some more logs? AFAIK "Hmm.. no failure message.." is an indicator that the process start failed with an unknown error cause (have to listen to the process output to detect if it started successful or failed) .. so if there is any more logging?

**Comment by michaelmosmann** [comment]
@mmuruev is there a way that you can use some of my spring integration modules? https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.7.x this comes with the latest embed-mongo release where it should be much easier to so some modifications..

**Comment by mmuruev** [comment]
Already tried it. The same results. Frustrating...

**Comment by michaelmosmann** [comment]
@mmuruev as spring and this project uses slf4j logging, you can set log level for 'de.flapdoodle.embed.mongo.spring.autoconfigure' to info or debugging.

**Comment by mmuruev** [comment]
```     2022-12-13 09:47:13.028 WARN [Test worker] WARN d.f.e.m.p.l.LinuxPackageFinder@211 - because there is no package for GenericFeatureAwareVersion{4.2.19}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to GenericFeatureAwareVersion{4.2.19}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
    2022-12-13 09:47:13.030 INFO [Test worker] INFO o.s.b.a.m.e.EmbeddedMongo@42 - Extract /root/.embedmongo/linux/mongodb-linux-x86_64-ubuntu1804-4.2.19.tgz : starting...
    2022-12-13 09:47:13.993 INFO [Test worker] INFO o.s.b.a.m.e.EmbeddedMongo@42 - Extract /root/.embedmongo/linux/mongodb-linux-x86_64-ubuntu1804-4.2.19.tgz : extract mongodb-linux-x86_64-ubuntu1804-4.2.19/bin/mongod
    2022-12-13 09:47:13.995 INFO [Test worker] INFO o.s.b.a.m.e.EmbeddedMongo@42 - Extract /root/.embedmongo/linux/mongodb-linux-x86_64-ubuntu1804-4.2.19.tgz : nothing left
    2022-12-13 09:47:13.996 INFO [Test worker] INFO o.s.b.a.m.e.EmbeddedMongo@42 - Extract /root/.embedmongo/linux/mongodb-linux-x86_64-ubuntu1804-4.2.19.tgz : finished
    2022-12-13 09:47:14.071 ERROR[Thread-5] ERROR o.s.b.a.m.e.EmbeddedMongo@52 - /tmp/extract-4d426ba0-93f7-4d5d-b060-4cc6690c271fextractmongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

Looks like crypto has failed even here.

**Comment by michaelmosmann** [comment]
@mmuruev maybe this helps: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/393 .. in the end libcrypto.so is needed and does not come with mongodb itself..

**Comment by mmuruev** [comment]
I've been thinking why not use something like AppImage/Flatpack for mongo? This will solve the dependency issues once and for all.

**Comment by michaelmosmann** [comment]
@mmuruev they only provide zip/tar archives and install packages.. so there is no way i can work around that.

**Comment by mmuruev** [comment]
But I believe appImage kinda open source.. nobody forbids creating the package. Issue it that this lib clime. that it 'supports' a wide range of versions, but in reality, it's not, because mongo just can't start missing some lib.. which is also not clear from the error. And since huge amount of docker images and quite minimal ones.. surprises always will be in it.

**Comment by michaelmosmann** [comment]
@mmuruev I can only support platforms with a matching distribution mongodb .. and as there is support for some linux versions, the don't support anything .. and i would guess that amazoncorretto != amazon linux 2 .. 

even with f.i. ubuntu there is some kind of limitation .. currently there is no version for 22.04 .. only for 20.04 .. but the "old" version works on 22.04 to.. 

maybe you should try testcontainers .. or just bundle your own image with the mongodb version you want..

**Comment by michaelmosmann** [comment]
@mmuruev i close this issue.. reopen, if needed.
