### ISSUE TITLE
MongoImport logs to error even when successful 

### ISSUE THREAD

**Issue by froth** [flapdoodle-oss/de.flapdoodle.embed.mongo#438]
MongoImport logs all its output to `error`, even successful operations.

```
[mongoimport error]2022-12-15T09:07:50.453+0100	connected to: mongodb://localhost:41729/
[mongoimport error] 2022-12-15T09:07:50.454+0100	dropping: products.produkt
```

**Comment by michaelmosmann** [comment]
@froth which version are you using?

**Comment by froth** [comment]
4.3.0

**Comment by michaelmosmann** [comment]
@froth i will have a look into this..

**Comment by michaelmosmann** [comment]
@froth .. as far as I could see mongoimport uses the error channel for this kind of message.. I will try to see if I can validate this behaviour if I start this on the command line.. strange.

**Comment by michaelmosmann** [comment]
@froth same behavior if i start mongoimport on the command line .. so is there anything i can do?

**Comment by froth** [comment]
@michaelmosmann the only thing coming to mind would be writing everything to INFO, but that would only reverse the problem. I think we will have to live with the behaviour Thanks for looking into it!

**Comment by michaelmosmann** [comment]
.. or create an issue somewhere for the wrong mongoimport behaviour.
