### ISSUE TITLE
MongoDB 6.0.3 not working

### ISSUE THREAD

**Issue by XSpielinbox** [flapdoodle-oss/de.flapdoodle.embed.mongo#440]
When changing the mongodb.embedded.version to 6.0.3 it does not download MongoDB Version 6.0.3. (tested with version 4.3.1 of embedded Mongo)

I suppose this is due to the definition for Version 6.0.3 in [Versions.java](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java#L247) referring to Version 6.0.2. This seems like a typo to me.

**Comment by michaelmosmann** [comment]
Oh.. yes.. it is a typo.

**Comment by michaelmosmann** [comment]
@XSpielinbox .. there is a new release ahead.

**Comment by XSpielinbox** [comment]
Yes, it works now with version 4.3.2. Thank you!
