### ISSUE TITLE
Access control: listCollections action not implemented

### ISSUE THREAD

**Issue by rechvs** [flapdoodle-oss/de.flapdoodle.embed.mongo#442]
Granting a user a role that includes the [_listCollections_ action](https://www.mongodb.com/docs/manual/reference/privilege-actions/#mongodb-authaction-listCollections) (e.g., the [_readAnyDatabase_ role](https://www.mongodb.com/docs/manual/reference/built-in-roles/#mongodb-authrole-readAnyDatabase)) does not actually allow that user to perform the [_listCollections_ command](https://www.mongodb.com/docs/manual/reference/command/listCollections/#mongodb-dbcommand-dbcmd.listCollections). Performing the command instead throws a MongoCommandException:
> Command failed with error 13 (Unauthorized): 'not authorized on customdb-database to execute command { listCollections: 1, cursor: {}, nameOnly: true, $db: "customdb-database", lsid: { id: UUID("4f6c09aa-836a-44c1-b13d-c528e07aacf4") } }' on server localhost:41819. The full response is {"ok": 0.0, "errmsg": "not authorized on customdb-database to execute command { listCollections: 1, cursor: {}, nameOnly: true, $db: \"customdb-database\", lsid: { id: UUID(\"4f6c09aa-836a-44c1-b13d-c528e07aacf4\") } }", "code": 13, "codeName": "Unauthorized"}

**Comment by michaelmosmann** [comment]
@rechvs now i had some time to look into this.. are you using https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring with user and password set as in this test: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/main/src/test/java/de/flapdoodle/embed/mongo/spring/autoconfigure/EmbeddedMongoAutoConfigurationTest.java#L194 ?

**Comment by rechvs** [comment]
Thank you for looking into this.  
I’ve finally had time to set up an [example project](https://github.com/rechvs/de.flapdoodle.embed.mongo-Issue442). To answer your question: no, I don’t use the Spring integration but rather setup everything manually (including role and user creation), so it’s very well possible that I’m screwing up there.
The project actually exemplifies three types of unexepected behavior (I’ve conflated the first and second one in [my first comment](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/442#issue-1507503103), sorry about that):
1. a custom role that includes the _listCollections_ action but doesn’t actually grant permission to execute the `com.mongodb.client.MongoDatabase::listCollectionNames` method (see [Issue442Test::customRole](https://github.com/rechvs/de.flapdoodle.embed.mongo-Issue442/blob/master/src/test/java/Issue442Test.java#L34))
 **This is the main concern of this issue.**
1. the [_readAnyDatabase_ role](https://www.mongodb.com/docs/manual/reference/built-in-roles/#mongodb-authrole-readAnyDatabase) doesn’t seem to be implemented (see [Issue442Test::readAnyDatabaseRole](https://github.com/rechvs/de.flapdoodle.embed.mongo-Issue442/blob/master/src/test/java/Issue442Test.java#L69)))
1. a test throws a `de.flapdoodle.reverse.TearDownException` at the end (see [Issue442Test::readRole](https://github.com/rechvs/de.flapdoodle.embed.mongo-Issue442/blob/master/src/test/java/Issue442Test.java#L102)))

**Comment by michaelmosmann** [comment]
@rechvs thanks.. i will have a look into this sample project..

**Comment by rechvs** [comment]
I forgot to add this in my last comment: [this](https://www.mongodb.com/docs/manual/reference/privilege-actions/#mongodb-authaction-listCollections) is the offical documentation for the _listCollections_ action.

**Comment by michaelmosmann** [comment]
@rechvs no problem..

**Comment by michaelmosmann** [comment]
@rechvs i would like to use the testcode from your example as part of this project.. if this is ok? and would add an author line for this..

**Comment by michaelmosmann** [comment]
@rechvs as i understand this the readAnyDatabase can not be assigned to a new user https://www.mongodb.com/docs/manual/reference/built-in-roles/#readAnyDatabase

**Comment by rechvs** [comment]
> but i hope i can solve this better then that.. stay tuned.

:+1: 

> i would like to use the testcode from your example as part of this project.. if this is ok?

Shure, I’m glad I managed to cobble together something useful for this project. :slightly_smiling_face: 

> as i understand this the readAnyDatabase can not be assigned to a new user

Maybe you’re right: it seems that while users can be created on an arbitrary (non-_admin_) database, the _readAnyDatabase_ role (like all [all-database roles](https://www.mongodb.com/docs/manual/reference/built-in-roles/#all-database-roles)) only exists on the _admin_  database. So if we want to eventually grant a user one of the all-database roles, we **must** create that user on the _admin_ database? I added a [commit](https://github.com/rechvs/de.flapdoodle.embed.mongo-Issue442/commit/158ebbe701cf3178612141490f061c693e737193) to the example project that seems to verify this: the assertions of the _readAnyDatabaseRole_ test now work, but the test throws a `de.flapdoodle.reverse.TearDownException` at the end.
On the other hand, [here](https://www.mongodb.com/docs/manual/tutorial/create-users/#create-additional-users-for-your-deployment) the docs explicilty say (emphasis mine)

> The database where you create the user (in this example, `test`) is that user's [authentication database](https://www.mongodb.com/docs/manual/core/security-users/#std-label-user-authentication-database). Although the user authenticates to this database, **the user can have roles in other databases**. The user's authentication database does not limit the user's privileges.

But maybe I’m misunderstanding the _roles in other dabatases_ part and it only means that users can have roles that _grant access to_ other databases, while I initially thought it meant that users can have roles that are _defined in_ other databases.

**Comment by michaelmosmann** [comment]
@rechvs in teardown i try to stop the mongodb by sending a shutdown command to the database, which does not work if auth==true .. i am working on this..

**Comment by rechvs** [comment]
I think I found out what was wrong with my attempt to grant the _readAnyDatabase_ role: when granting the role (either via [`createUser`](https://www.mongodb.com/docs/manual/reference/command/createUser/) or via [`grantRolesToUser`](https://www.mongodb.com/docs/manual/reference/command/grantRolesToUser/)) you can specify the role as a document like this:  
`{ role: "<role>", db: "<database>" }`  
So if you want to grant the _readAnyDatabase_ (which only exists on the _admin_ database), you would specify the role like this (credit goes to @ydylla for pointing me in the right direction):  
`{"role": "readAnyDatabase", "db": "admin"}`  
I’ve adjusted the corresponding test in the example project accordingly. However, the test now fails with  
_com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='test-db-user', source='admin', password=<hidden>, mechanismProperties=<hidden>}_,   
which I think is a flapdoodle issue.

**Comment by michaelmosmann** [comment]
@rechvs i will have to look into this change.. thanks for your efforts:)

**Comment by michaelmosmann** [comment]
@rechvs hmm... did you tried this directly on a mongodb? without this java-test-stuff? I am by far no expert on these issues...

**Comment by rechvs** [comment]
No, not yet. I’ll verify the expected behavior against a normal MongoDB instance, but it might be a while until I have some time on my hands.

**Comment by michaelmosmann** [comment]
@rechvs no hurry:)

**Comment by michaelmosmann** [comment]
@rechvs .. any progress with that?

**Comment by michaelmosmann** [comment]
@rechvs .. no problem:) it stays open..

**Comment by rechvs** [comment]
I’ve finally managed to verify that the behavior expected by me is actually the appropriate behavior.

I’ve attached a [ZIP of shell scripts](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/files/10793158/shell-scripts.zip) that’ll hopefully also help you in verifying the expected behavior (at least if you’re on Linux with systemd):  
1. Ensure that access control is deactivated in your local MongoDB instance.  
   Judging from [these docs](https://www.mongodb.com/docs/manual/tutorial/configure-scram-client-authentication/#use-scram-to-authenticate-clients) it should be enough to start the instance without explicitly activating access control.
1. Execute `./mongodb-create-collections-without-auth`.
1. Execute `./mongodb-create-user-and-role-without-auth`.
1. [Activate access control](https://www.mongodb.com/docs/manual/tutorial/configure-scram-client-authentication/#re-start-the-mongodb-instance-with-access-control) in your local MongoDB instance.  
   On my machine (Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux with systemd) the relevant config file is `/etc/mongod.conf` 
1. Execute `./stop-mongod-via-systemd; ./start-mongod-via-systemd` to restart your local MongoDB instance.
1. Execute `./mongodb-list-collections-with-auth`.  
   This should return something like the following:
   ```json
   {
        "cursor" : {
                "id" : NumberLong(0),
                "ns" : "issue-442-test-db.$cmd.listCollections",
                "firstBatch" : [
                        {
                                "name" : "issue-442-test-coll-1",
                                "type" : "collection",
                                "options" : {

                                },
                                "info" : {
                                        "readOnly" : false,
                                        "uuid" : UUID("545ccde1-4362-4326-aeec-1798ecfb93d2")
                                },
                                "idIndex" : {
                                        "v" : 2,
                                        "key" : {
                                                "_id" : 1
                                        },
                                        "name" : "_id_"
                                }
                        },
                        {
                                "name" : "issue-442-test-coll-2",
                                "type" : "collection",
                                "options" : {

                                },
                                "info" : {
                                        "readOnly" : false,
                                        "uuid" : UUID("70d8c260-b933-45dd-92bd-37d70578cf6d")
                                },
                                "idIndex" : {
                                        "v" : 2,
                                        "key" : {
                                                "_id" : 1
                                        },
                                        "name" : "_id_"
                                }
                        }
                ]
        },
        "ok" : 1
    }
    ```

**Comment by michaelmosmann** [comment]
@rechvs i could create a test from that .. https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/src/test/java/de/flapdoodle/embed/mongo/scenario/AccessControlAndListCollectionsActionTest.java .. now i can check which modification will break this:)

**Comment by rechvs** [comment]
> IMHO this should be possible in one go

I’m not sure. If I understand [the procedure for SCRAM](https://www.mongodb.com/docs/manual/tutorial/configure-scram-client-authentication/#procedure) correctly, you _have_ to start the instance without access control in order to be able to at least create the user admin (or whatever users you need for your test scenario), which you can then (when access control is enabled) use to create all other users. I don’t see a way around this. :frowning_face:

**Comment by michaelmosmann** [comment]
@rechvs .. i will try:) and then i have e test for that.. :)

**Comment by michaelmosmann** [comment]
@rechvs did update the test.. works in one go .. there are now to tests, hope it helps to spot the difference.. so i try to make this work in my spring adapter too:) thanks for your work and very helpful input:)

**Comment by michaelmosmann** [comment]
@rechvs after some fun with spring i could create this tests: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/main/src/test/java/de/flapdoodle/embed/mongo/spring/autoconfigure/AuthTest.java .. which now works with spring3.x, spring2.7.x and spring2.6.x .. i had to upgrade the mongodb drivers to make it work with spring2.7.x and spring2.6.x .. which was kind of surprise .. 

.. and after all this i might wonder if the problem was a mongodb driver issue and not something we did wrong.. 

.. anyway. could remove a lot of code.. :)  thanks for this inspiration:) i close this issue.. just reopen or create a new if still something is wrong.
