### ISSUE TITLE
upgrade to org.mongodb:mongodb-driver-sync:4.7.2 

### ISSUE THREAD

**Issue by debu999** [flapdoodle-oss/de.flapdoodle.embed.mongo#443]
Currently the flapdoodle depends on org.mongodb:mongodb-java-driver:3.12.11 can we upgrade the library to org.mongodb:mongodb-driver-sync:4.7.2

**Comment by michaelmosmann** [comment]
@debu999 i think that's possible .. but i am not sure if the new driver can still talk to old versions of mongodb .. so i have to tests this..

but as this dependency is for tests only which kind of problem do you have with that?

**Comment by debu999** [comment]
https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/

New driver supports mongodb from 2.x.

Just another library for test is not a overkill but we want to stick with the limited no. Of jars as possible.

**Comment by debu999** [comment]
I am trying to use flapdoodle in windows and with Quarkus. Taking refernece from the spring implementation can you guide which one is for replica set config

**Comment by debu999** [comment]
@michaelmosmann older version does not work with windows ci so wanted to try new one with quarkus

**Comment by debu999** [comment]
https://github.com/quarkusio/quarkus/tree/main/test-framework%2Fmongodb%2Fsrc%2Fmain%2Fjava%2Fio%2Fquarkus%2Ftest%2Fmongodb

The test resource implementation in Quarkus. If you can advise any pointers will be able to do the upgrade pr to quarkus

**Comment by michaelmosmann** [comment]
@debu999 ah.. ok.. i will have a look

**Comment by debu999** [comment]
Currently using Quarkus 2.15.0.Final @michaelmosmann

**Comment by debu999** [comment]
Driver sync 4.7.x

**Comment by debu999** [comment]
If the documentation can have some update to create a default mongdb on port 27017 and replicaset on 27017 and 27018 it should suffice with start and stop options

**Comment by michaelmosmann** [comment]
@debu999 i did create a pull request in quarkus -> https://github.com/quarkusio/quarkus/pull/30243 .. currently i did only replace existing code without checking if the way the cluster is initialized makes sense.. 

I do strugle to open quarkus without compile errors bc of missing dependencies etc.. so could not start any test.

**Comment by michaelmosmann** [comment]
@debu999 so this is done or is there something else?

**Comment by debu999** [comment]
flapdoodle still depends on 
<dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.12.11</version>
            <scope>test</scope>
        </dependency>
        but it works with quarkus and spring boot. May be we can keep it open for next iteration to fix the same with new version. Its no longer a blocker.

**Comment by michaelmosmann** [comment]
@debu999 but IMHO test dependencies are not transitive.. or not?

**Comment by michaelmosmann** [comment]
@debu999 is this still an issue? or should we close this?

**Comment by debu999** [comment]
Let's close this it's not a blocker

**Comment by michaelmosmann** [comment]
@debu999 btw.. the new driver needs at least a mongodb >= 3.6, but i hope nobody is using a mongodb older than that ..
