### ISSUE TITLE
Error 401 with custom download URL having basic auth

### ISSUE THREAD

**Issue by wazyk** [flapdoodle-oss/de.flapdoodle.embed.mongo#448]
Using a the custom URL with the format <user>:<password>@<host>:<port>/<url-path> (basically an internal proxy that I can't act on as it belongs to the client) results in a 401 error.
Any fix to manage basic auth necessary ?
Regards

**Comment by michaelmosmann** [comment]
@wazyk is this an https-proxy and an https server?

**Comment by wazyk** [comment]
Tricky situation I have.
A little bit of context : embedded Mongo is used in unit tests as par of a Gitlab CI pipeline.
On the client's side, the only possible Internet access during pipeline execution must be done through proxies defined on Nexus repository manager, which is the only "door" to the outside.
The URL to that proxy is done in simple HTTP, as it is an internal access between middlewares (Gitlab to Nexus), with login/password basic auth in URL. Then the proxy reroutes on the default URL (fastdl.mongodb.org).
It works locally when no auth is required in our Nexus access.

**Comment by michaelmosmann** [comment]
@wazyk ah.. ok.. thanks.. as there are some issues to provide proxy stuff in code it will take a little time (esp https is ugly).. but the use case is obviously a valid one:)

**Comment by wazyk** [comment]
Thanks. No hurry.
We just managed to workaround for the moment. A curl through Nexus proxy is done to locally store the tar.gz. Then we have managed to set a custom download URL with file:// protocol.
It works quite good right now...

**Comment by michaelmosmann** [comment]
@wazyk i tried a lot and i am afraid that this is some kind of hard problem:) .. it is not possible (AFAIK) to set an proxy for a url connection WITH basic auth for the proxy if the requested url is https .. it looks like that one can only set this at jvm level..

**Comment by michaelmosmann** [comment]
@wazyk one way to solve this: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/Howto.md#customize-downloader-implementation you could use your own implementation to download an archive .. this way you can avoid the jdk implementation and replace it with something else where https over proxy with auth is not a problem.

**Comment by wazyk** [comment]
> @wazyk one way to solve this: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/Howto.md#customize-downloader-implementation you could use your own implementation to download an archive .. this way you can avoid the jdk implementation and replace it with something else where https over proxy with auth is not a problem.

Thanks. We'll try to look into that with this lead.
