### ISSUE TITLE
Please add support for Ubuntu 22.04 by supporting the download of MongoDB 6.0.4

### ISSUE THREAD

**Issue by sevokn** [flapdoodle-oss/de.flapdoodle.embed.mongo#451]
According to the table at https://www.mongodb.com/docs/manual/administration/production-notes/#platform-support-matrix , MongoDB supports Ubuntu 22.04 from release 6.0.4 onwards. The 6.x branch of MongoDB is as far as I can see the only version that specifically supports Ubuntu 22.04. Also, the MongoDB community releases download page at https://www.mongodb.com/download-center/community/releases lists a build for Ubuntu 22.04, at download link https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-6.0.4.tgz .

However, even when using the newest release 4.4.1 of `de.flapdoodle.embed.mongo` library, and requesting to use version 6.0.4 of MongoDB, it is unable to download that version, the debug output contains:

```
could not resolve package for GenericFeatureAwareVersion{6.0.4}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_22_04}
```

and

```
(os=Linux)
  (os=Linux and (version is any of Ubuntu_16_04, Ubuntu_16_10, Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_10, Ubuntu_22_04))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_10, Ubuntu_22_04)) and (6.0.1-6.0.1 or 5.0.12-5.0.12 or 5.0.5-5.0.6 or 5.0.0-5.0.2 or 4.4.16-4.4.16 or 4.4.13-4.4.13 or 4.4.11-4.4.11 or 4.4.0-4.4.9)
      url=/linux/mongodb-linux-x86_64-ubuntu2004-{version}.tgz (TGZ)
```

As far as I can see there are two problems here:

1. The current logic maps a detected Ubuntu 22.04 to the Ubuntu 20.04 build of MongoDB (which will in general not work at all because of the shared native library `libcrypto.so.1.1` being not available on 22.04, as was stated above only MongoDB 6.0.4 and onwards supports Ubuntu 22.04). The Ubuntu 20.04 build of MongoDB should not be mapped to Ubuntu 22.04.
2. The version 4.4.1 of `de.flapdoodle.embed.mongo` does not support/recognize MongoDB versions above 6.0.1 at all, and 6.0.4 would be required for Ubuntu 22.04 support.

Please make the download of MongoDB version 6.0.4 possible, so that Ubuntu 22.04 can be supported.

As far as I can see, the only version of embedded MongoDB that is currently running on Ubuntu 22.04 is the generic Linux/x64 version, and its most recent available version is 4.0.28. Trying to use any newer versions of MongoDB than 4.0.28 on Ubuntu 22.04 results in the Ubuntu 20.04 build of MongoDB being used, and using it will fail with the aforementioned missing `libcrypto.so.1.1` error. That's why supporting 6.0.4 is important, since 4.0.28 is so old.

**Comment by sevokn** [comment]
If/when this will be fixed, I'm adding in here also the request to fix this issue in the legacy 3.x branch of `de.flapdoodle.embed.mongo` since that is used by Spring Boot 2.7.x. For example, the current Spring Boot 2.7.8 uses `de.flapdoodle.embed.mongo` version 3.4.11.

As Spring Boot 3.x is such a breaking change from Spring Boot 2.7.x, the support window for the 2.7.x branch has been extended compared to other previous 2.x branches (see https://spring.io/projects/spring-boot#support ) which will mean that the 2.7.x branch of Spring Boot will apparently receive minor releases for quite some time forward. And it would be very beneficial to projects on Spring Boot 2.7.x to be able to in the future use a newer Spring Boot 2.7.x release that would have its dependencies updated so that it would include a version greater than 3.4.11 of `de.flapdoodle.embed.mongo` dependency, that would support MongoDB 6.0.4 or greater on Ubuntu 22.04.

**Comment by michaelmosmann** [comment]
@sevokn there is a new release (will be in maven central in 12-24hrs) where you can use mongodb 6.0.4. For spring 2.7.x and spring 2.6.x you should use https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.7.x (or https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.6.x) ..

**Comment by Abstraxt-AA** [comment]
Waiting for OP to reply but in the meanwhile, I had the same issue as OP and can confirm 4.5.0 fixes it on Ubuntu 22.04 with Mongo 6.0.4

**Comment by michaelmosmann** [comment]
@Abstraxt-AA you should use 4.5.1 .. there was a bug (wrong url for ubuntu 20.xx and 6.0.4) ..

**Comment by michaelmosmann** [comment]
@Abstraxt-AA i close this issue.. reopen if needed:)
