### ISSUE TITLE
Local MongoDB Download

### ISSUE THREAD

**Issue by Lucasark** [flapdoodle-oss/de.flapdoodle.embed.mongo#453]
Using this:

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/Howto.md#customize-artifact-storage

Can I pass direct local path without download?

this `.embeddedMongodbCustomPath` is my path lick /path/path/path/same.tgz ?

**Comment by michaelmosmann** [comment]
@Lucasark its easier to change the download url to something local as the storage path is the base directory where all different artifacts stored based on url and content hashes .. so just provide an url to your local file.. this should word: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/Howto.md#customize-download-url

**Comment by Lucasark** [comment]
> @Lucasark its easier to change the download url to something local as the storage path is the base directory where all different artifacts stored based on url and content hashes .. so just provide an url to your local file.. this should word: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/Howto.md#customize-download-url

There is any exemple of usage of any customize in complete file? I did not understand how to use, it is a Bean? Should I create a @Configuration ? 

```
@DataMongoTest()
@ExtendWith(SpringExtension.class)
class DeFlapTest {
    @Test
    void example(@Autowired final MongoTemplate mongoTemplate) {
        Assertions.assertThat(mongoTemplate.getDb()).isNotNull();

    }
}
```

I am trying just to do this little test using local path, where should I create mongod in this exemple?

**Comment by michaelmosmann** [comment]
@Lucasark which spring version do you use? I will create an example how to customize such properties with spring.. (maybe tomorrow)

**Comment by Lucasark** [comment]
> @Lucasark which spring version do you use? I will create an example how to customize such properties with spring.. (maybe tomorrow)

I am using 2.6.7 and 2.3.12, both in diferent projects and using de.flapdoodle

**Comment by Lucasark** [comment]
To bring more specific informations, I am try to do this ExempleIT using Canary:

[Canary Exemple](https://github.com/Lucasark/de.flapdoodle.embed.mongo.canary/blob/main/embed-spring-boot-26/src/test/java/example/ExampleIT.java)

**Comment by michaelmosmann** [comment]
@Lucasark i will have a look..

**Comment by michaelmosmann** [comment]
@Lucasark i did a new release and updated the documentation how to customize the mongod starter further: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/spring-2.6.x/HowTo.md#customize-mongod

**Comment by michaelmosmann** [comment]
> To bring more specific informations, I am try to do this ExempleIT using Canary:
> 
> [Canary Exemple](https://github.com/Lucasark/de.flapdoodle.embed.mongo.canary/blob/main/embed-spring-boot-26/src/test/java/example/ExampleIT.java)
> 
> Using MockMvc it show some errors, if you could bring this exemple with this I will appreciate.

To setup MockMvc this blog post might be helpfull: https://rieckpil.de/guide-to-testing-spring-boot-applications-with-mockmvc/
