### ISSUE TITLE
verbose = false does not  get rid of verbous output on stdout 

### ISSUE THREAD

**Issue by bodote** [flapdoodle-oss/de.flapdoodle.embed.mongo#475]
when using  
```
<groupId>de.flapdoodle.embed</groupId>
<artifactId>de.flapdoodle.embed.mongo.spring30x</artifactId>
```
and 
```
@Bean
    MongodArguments mongodArguments() {
        return MongodArguments.defaults().withIsVerbose(false);
    }
```
I get tons of log output on stdout:
```
[mongod output]{"t":{"$date":"2023-08-11T08:24:57.648+02:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"main","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":13},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion":13},"outgoing":{"minWireVersion":0,"maxWireVersion":13},"isInternalClient":true}}}
...
```
I would expect that either setting verbose to `false` would supress all those lines or there should be a  `MongodArguments.defaults().withIsQuiet(true);` option . 

(I have tried `MongodArguments.defaults().withParams(..)` and  `MongodArguments.defaults().withArgs(..)` but that did not work at all.)

**Comment by michaelmosmann** [comment]
@bodote hmm.. i have to check this..

**Comment by michaelmosmann** [comment]
@bodote there is a new release .. withIsQuiet(true) should work as expected.

**Comment by michaelmosmann** [comment]
@bodote does it work like expected?

**Comment by bodote** [comment]
I did not try yet, since I found a different solution  using [this method ](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Howto.md#usage---custom-mongod-process-output).
(The [Howto.md](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Howto.md) was a little hard to find for me  at first , but finally found it.)
Nevertheless the `withIsQuiet(true)` seems a very good idea, I will let you know as soon as I have test it.

**Comment by michaelmosmann** [comment]
@bodote i close this.. just reopen if needed.

**Comment by bodote** [comment]
> @bodote does it work like expected?

not really: 
  ```
@Override
            public Transition<MongodArguments> mongodArguments() {
                return Start.to(MongodArguments.class)
                        .initializedWith(MongodArguments.defaults()
                                .withIsQuiet(true)
                                .withReplication(Storage.of("testRepSet", 5000))
                                .withUseNoJournal(false));
            }

```
does not work, I still get all the "[mongod output]...."  lines

**Comment by michaelmosmann** [comment]
@bodote ah.. sorry. isQuiet and verbose are mongodb command line arguments.. to get rid of any output from starting the mongodb you may use this: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Customizations.md#-to-null-device

**Comment by michaelmosmann** [comment]
@bodote there are two things..  

the mongod process and the things thats starts this stuff.. isQuiet, verbose etc are mongod arguments.. and will change what and how much mongod dumps to the terminal on startup .. 

but for instance to detect if the mongod is started, we have to wait mongod writing "waiting for connections" to the terminal (see https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/e8be33009f215c47335dc852f5c9dc2cf96b6aa9/src/main/java/de/flapdoodle/embed/mongo/transitions/RunningMongoProcess.java#L195).

So we have the read everything that mongod spills out to the terminal, and per default each line is wrapped with [mongod output]. To get rid of that you have to redirect or disable the process output.
