### ISSUE TITLE
Flapdoodle 4.8.0 doesn't support MongoDB < 6 on MacOS ARM

### ISSUE THREAD

**Issue by Rocker93** [flapdoodle-oss/de.flapdoodle.embed.mongo#477]
After upgrading from Flapdoodle 4.7.1 to 4.8.0 it is no longer possible to run MongoDB lower than 6 on MacOS with ARM.
I'm not able to provide an exact log, as I don't own a MacOS machine. What I've gathered from my colleagues the MongoDB downloader no longer discovers any compatible MongoDB version lower than 6 with MacOS ARM architecture.
As MongoDB 4.4 and 5.0 are still supported versions (5.0 until Oct 2024), I believe they should be supported under Flapdoodle on MacOS ARM as well.

**Comment by michaelmosmann** [comment]
@Rocker93 ah.. thanks. I have to look into this. Consider this as an bug:)

**Comment by michaelmosmann** [comment]
@Rocker93 there is a new release (in maven central in about 12hrs i think) which should use the x86-binaries on the arm platform again...

**Comment by Rocker93** [comment]
I can confirm the new version is working on MacOS ARM. Thank you.
