### ISSUE TITLE
MongoDB 6.0.9 support

### ISSUE THREAD

**Issue by XSpielinbox** [flapdoodle-oss/de.flapdoodle.embed.mongo#478]
When using `de.flapdoodle.mongodb.embedded.version=6.0.9` via the Spring integration it works, but how can it work, when [Version.java](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java) is missing a 6.0.9 entry? Does [flapdoodle-oss/de.flapdoodle.embed.mongo.spring](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring) work directly with [de.flapdoodle.embed.mongo.packageresolver](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver) and bypass [de.flapdoodle.embed.mongo](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo)?

**Comment by michaelmosmann** [comment]
@XSpielinbox .. i close this issue.. reopen if needed, but i guess its a little bit outdated..
