### ISSUE TITLE
custom-url to download mongo distribution.

### ISSUE THREAD

**Issue by kaushikranjan** [flapdoodle-oss/de.flapdoodle.embed.mongo#482]
In one of our projects, For integration-testing, we are using 
de.flapdoodle.embed:de.flapdoodle.embed.mongo=3.0.0
de.flapdoodle.embed:de.flapdoodle.embed.process=3.0.1

The mongo version we are running right now is +4.2 in production.
Setting spring.mongodb.embedded.version=4.4.24 doesn't work as the distribution url generated by de.flapdoodle.embed.mongo is **https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-4.4.24.tgz**  
whereas it should be **https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-7.0.1.tgz**

Is there a way to specify a custom url? What is the ideal workaround?

**Comment by michaelmosmann** [comment]
@kaushikranjan can you use a recent version of this library? I am not sure why setting spring.mongodb.embedded.version to 4.4.24 should give a download url for the 7.0.1 version of mongodb. To use a more recent version of mongodb i think you must upgrade to a recent version of this library as the old version may not support a clean start of mongodb >= 7.x

**Comment by michaelmosmann** [comment]
@XSpielinbox i have to look into this..

**Comment by michaelmosmann** [comment]
@XSpielinbox @kaushikranjan .. should work with the next release
