### ISSUE TITLE
de.flapdoodle.embed.process.runtime.Starter prepare from behind a proxy

### ISSUE THREAD

**Issue by spstorey** [flapdoodle-oss/de.flapdoodle.embed.mongo#49]
I've used the embeded-mongo-plugin successfully (whcih can be configured to download the mongo exe's from behind a proxy) and I now need to programatically startup mongo but I can't see how you can provide the proxy address and port ?

**Comment by AnilRahul** [comment]
Hello Michael,

When i try to customize proxy for downloading mongo db as shown in the above link.
The method download(AbstractBuilder<IDownloadConfig>) from the type ArtifactStoreBuilder is deprecated in the version - 1.50.2.

Can you please suggest me how can i customize the proxy.

**Comment by matlockx** [comment]
Copy from readme:

```
Command command = Command.MongoD;

    IRuntimeConfig runtimeConfig = new RuntimeConfigBuilder()
        .defaults(command)
        .artifactStore(new ExtractedArtifactStoreBuilder()
            .defaults(command)
            .download(new DownloadConfigBuilder()
                .defaultsForCommand(command)
                .proxyFactory(new HttpProxyFactory("fooo", 1234))))
            .build();
    ...
```
