### ISSUE TITLE
Manjaro support

### ISSUE THREAD

**Issue by mmuruev** [flapdoodle-oss/de.flapdoodle.embed.mongo#495]
Will be ever manjaro support? Or its mongo server itself issues?

**Comment by michaelmosmann** [comment]
@mmuruev If you can get a mongodb server running on manjaro linux, it is not that hard to add this to my project.. you can try it yourself if any package for an other linux distribution will run on manjaro.. if this is the case, i just need which packages did run..

**Comment by michaelmosmann** [comment]
@mmuruev .. are there any updates on this issue?

**Comment by mmuruev** [comment]
Yes, I just tired from embedded mongo being broken with dist upgrade, still without any good error info just failing tests( no check that actually mongo started successfully). So testcontainers my friend now. With its own drawback but more predictable. And besides somehow testcontainers are faster with tests.

**Comment by michaelmosmann** [comment]
@mmuruev ah.. ok.. i am glad that this works for you.. as i don't have manjaro linux installed, i can not check this by myself.. 

i close this issue.. reopen if needed.
