### ISSUE TITLE
Fedora 39 detection not working

### ISSUE THREAD

**Issue by XSpielinbox** [flapdoodle-oss/de.flapdoodle.embed.mongo#498]
The Fedora 38 detection is working great.
But with Fedora 39, that released two weeks ago, is does not work anymore.

Adding
```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.2</version>
                <configuration>
                    <systemPropertyVariables>
                        <de.flapdoodle.os.override>Linux|X86_64|CentOS|CentOS_9</de.flapdoodle.os.override>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
```
to my `pom.xml` does the trick again, as it did in #468.

As Fedora Linux has releases twice a year, listing every version individually, seems like quite a high and unnecessary maintenance overhead to me.

Would it perhaps be possible to map all Fedora releases since Fedora Linux 34 to RHEL 9? Then it would only possibly break on every new major RHEL release, which happen way less frequently, though.
As only Fedora Linux 37 (and that only for three more weeks) and newer are currently supported, it would also make sense to me to map all Fedora releases to RHEL 9 for now. This would be a bit dirty, but perhaps save maintenance effort and no one should be using these ancient Fedora releases anymore anyway and even if, it would be trivial to map it to a different release using e.g. above method.

**Comment by michaelmosmann** [comment]
@XSpielinbox hmm.. i will think about that.

**Comment by michaelmosmann** [comment]
@XSpielinbox it should work again with the latest release.. and i did change it, so that fedora 40 and fedora 41 is detected too.. and it should be easier to change it, if things are changing...

**Comment by michaelmosmann** [comment]
@XSpielinbox spring integration follows with the next release as there are some refactorings ahead..

**Comment by michaelmosmann** [comment]
@XSpielinbox spring integration released.. should be in maven central soon.. :)
