### ISSUE TITLE
de.flapdoodle.embed.mongo updated to 4.11.1 and adding dependency org.immutables 

### ISSUE THREAD

**Issue by kmstrzelec** [flapdoodle-oss/de.flapdoodle.embed.mongo#500]
I changed de.flapdoodle.embed.mongo from 2.20 to 4.11.1. 
Then in classes from this  library problem:  "cannot resolve symbol" with @Value.Immutable occurred (import org.immutables.value.Value).
I had to add dependecnies in my project org.immutables artifactId: value and artifactId: value builder and then problem was solved.
These dependencies  are in pom below with scope: provided 

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/pom.xml

But I have a question: Was this pom intentionally prepared this way?

**Comment by michaelmosmann** [comment]
@kmstrzelec These annotations are only used for code generation and not for runtime behavior.. so it is not necessary to add these dependencies just to use them. Yes, your IDE will show some errors is you are opening the class or source files of this library, but this is the case with any other third-party annotation with RetentionPolicy.CLASS .. (the default).

So yes: its intentionally. But are there any other problems beside these warnings from your IDE?

**Comment by kmstrzelec** [comment]
@michaelmosmann Thank you for your answer, I just need to know.
It was first time I've had situation like this one.
No, there is no more problems.

**Comment by michaelmosmann** [comment]
@kmstrzelec so i close this issue.. :)
