### ISSUE TITLE
Requesting library support to add $search aggregation pipeline for integration testing.

### ISSUE THREAD

**Issue by silambarasan** [flapdoodle-oss/de.flapdoodle.embed.mongo#504]
Opened issue in this repository : https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/issues/45 and copied over here as well for the better visibility. Any help would be greatly helpful.

**Comment by michaelmosmann** [comment]
@silambarasan i close this issue, reopen if needed.
