### ISSUE TITLE
@silambarasan i close this issue, reopen if needed. See linked issue for an answer.

### ISSUE THREAD

**Issue by silambarasan** [flapdoodle-oss/de.flapdoodle.embed.mongo#506]
@silambarasan i close this issue, reopen if needed. See linked issue for an answer.

_Originally posted by @michaelmosmann in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/504#issuecomment-1883608334_
            
I found this documentation from mongo : https://www.mongodb.com/blog/post/introducing-local-development-experience-atlas-search-vector-search-atlas-cli 
Is this something can be incorporated in flapdoodle ?

**Comment by michaelmosmann** [comment]
@silambarasan i did transfer everthing to this issue -> https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/507
