### ISSUE TITLE
Requesting library support to add $search aggregation pipeline for integration testing.

### ISSUE THREAD

**Issue by silambarasan** [flapdoodle-oss/de.flapdoodle.embed.mongo#507]
We are facing exception while running the testcase with $search aggregation pipeline as shown below,
`org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 40324 (Location40324): 'Unrecognized pipeline stage name: '$search'' on server localhost:27018. The full response is {"ok": 0.0, "errmsg": "Unrecognized pipeline stage name: '$search'", "code": 40324, "codeName": "Location40324"}`

Upon investigation it has been found, it's missing support for this. Please share us any workaround or any updates for this operation to be included.

**Comment by michaelmosmann** [comment]
@silambarasan so far, not so good .. i did try to use the atlas cli tool to create an local cluster which failed.. (see requirements: https://www.mongodb.com/docs/atlas/cli/stable/atlas-cli-deploy-local/). So i guess this will work only on macos or centos/redhat. And even if this would work i can not see how this tools works, how i could create local isolated deployments for each running test.. i am not sure if this tool just wraps a enterprise version of mongodb or more than that.

So with any other good idea how to solve this, i would recommend some testcontainer or custom docker image..

Sorry...

**Comment by michaelmosmann** [comment]
@silambarasan i will close this issue.. reopen, if needed
