### ISSUE TITLE
Support for ubuntu 24.04

### ISSUE THREAD

**Issue by lsfischer** [flapdoodle-oss/de.flapdoodle.embed.mongo#517]
Hi!

Ubuntu 24.04 was released 25/04/2024. There's currently no support for it when trying to use falpdoodle's embeded mongodb.
When running on a ubuntu 24.04 machine, we get 
```
Caused by: java.lang.IllegalArgumentException: could not resolve package for V7_0:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu} 
...
(os=Linux)
  (os=Linux and (version is any of Ubuntu_16_04, Ubuntu_16_10, Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10))
  'UbuntuPackageFinder'
```
As visible in the message and here https://github.com/flapdoodle-oss/de.flapdoodle.os/blob/main/src/main/java/de/flapdoodle/os/linux/UbuntuVersion.java, there's currently no support for `Ubuntu_24_04`.

**Comment by michaelmosmann** [comment]
@lsfischer .. ah.. ok, i will add ubuntu 24.04.

**Comment by michaelmosmann** [comment]
@lsfischer .. the real fun happens here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver .. but the required change is not obvious.. so i think i will build a new release of everything in the evening..

**Comment by michaelmosmann** [comment]
@lsfischer release done.. 4.13.0
