### ISSUE TITLE
Could not run in gitlab-runner

### ISSUE THREAD

**Issue by michaelmosmann** [flapdoodle-oss/de.flapdoodle.embed.mongo#525]
The strange thing is, that it works locally (Ubuntu 22 and 24) and locally in a docker container, e.g. with image maven:3.9-eclipse-temurin-17 but as soon as it is run in the gitlab pipeline (even with docker) or the gitlab virtual machine (Debian 12) itself it fails to start

```
#11 138.4 Caused by: java.lang.RuntimeException: Could not start process: 
#11 138.4 ----------------------
#11 138.4 Hmm.. no failure or success message after 60000ms .. 
#11 138.4 ...the cause must be somewhere in the process output:
#11 138.4 - 8<- - - - - - - - - -
#11 138.4 
#11 138.4 
#11 138.4 
#11 138.4 - >8- - - - - - - - - -
#11 138.4 
#11 138.4 	at de.flapdoodle.embed.mongo.transitions.RunningMongoProcess.lambda$null$1(RunningMongoProcess.java:180) ~[de.flapdoodle.embed.mongo-4.1
```

_Originally posted by @F-Node-Karlsruhe in https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/413#issuecomment-2188813669_

**Comment by F-Node-Karlsruhe** [comment]
gitlab shell runner 16.11.1 on debian 12
Docker build with image maven:3.9-eclipse-temurin-17

**Comment by F-Node-Karlsruhe** [comment]
It also happens on other debian 12 virtual machines when just building with docker

**Comment by michaelmosmann** [comment]
@F-Node-Karlsruhe do you have some more logging information? When you see 
`Hmm.. no failure or success message after 60000ms ..` in your log, then the binary did behave different than expected.. i inspect the process log to see if there is some error message or some success message (open port .. bla bla bla). If both did not happen, i kill everything after one minute.

**Comment by F-Node-Karlsruhe** [comment]
afaiu. the not started process is the root cause. i played a little with the mongodb versions. For 4 and 5 for instance therre is an error where the mongodb binary complains about a missing `libcrypto1.1` but for 6 and 7 it fails silently

```
#11 83.73   State(ProgressListener)=de.flapdoodle.embed.process.io.progress.Slf4jProgressListener@1b3ab4f9,
#11 83.73   State(Command)=MongoD,
#11 83.73   State(Version)=GenericFeatureAwareVersion{5.0.27},
#11 83.73   State(Net)=Net{bindIp=127.0.0.1, port=38209, isIpv6=false},
#11 83.73   State(MongodArguments)=MongodArguments{syncDelay=0, useDefaultSyncDelay=false, isVerbose=false, verbosityLevel=1, isQuiet=false, useNoPrealloc=true, useSmallFiles=true, useNoJournal=true, enableTextSearch=false, auth=false, master=false, isConfigServer=false, isShardServer=false, params={}, args={}}
#11 83.73 
#11 83.73 	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:190) ~[de.flapdoodle.reverse-1.7.2.jar:na]
#11 83.73 	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:69) ~[de.flapdoodle.reverse-1.7.2.jar:na]
#11 83.73 	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:65) ~[de.flapdoodle.reverse-1.7.2.jar:na]
#11 83.73 	at de.flapdoodle.embed.mongo.spring.autoconfigure.MongodWrapper.start(MongodWrapper.java:45) ~[de.flapdoodle.embed.mongo.spring3x-4.14.0.jar:na]
#11 83.73 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
#11 83.73 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
#11 83.73 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
#11 83.73 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
#11 83.73 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1892) ~[spring-beans-6.1.8.jar:6.1.8]
#11 83.73 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-6.1.8.jar:6.1.8]
#11 83.73 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784) ~[spring-beans-6.1.8.jar:6.1.8]
#11 83.73 	... 156 common frames omitted
#11 83.73 Caused by: java.lang.RuntimeException: Could not start process: 
#11 83.73 ----------------------
#11 83.73 Hmm.. no failure or success message after 60000ms .. 
#11 83.73 ...the cause must be somewhere in the process output:
#11 83.73 - 8<- - - - - - - - - -
#11 83.73 
#11 83.73 
#11 83.73 
#11 83.73 - >8- - - - - - - - - -
```

**Comment by michaelmosmann** [comment]
@F-Node-Karlsruhe can you increase the logging for "de.flapdoodle.embed." .. there should be some output from the starting process ..

**Comment by michaelmosmann** [comment]
@F-Node-Karlsruhe i do not know your spring app setup.. is there any way to run this on your setup: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary

**Comment by F-Node-Karlsruhe** [comment]
this is the most specific log above the start failure timeout
```
#11 79.91 Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0: Error creating bean with name 'syncClientServerWrapper' defined in class path resource [de/flapdoodle/embed/mongo/spring/autoconfigure/EmbeddedMongoAutoConfiguration$SyncClientServerWrapperConfig.class]: rollback after error on transition to State(RunningMongodProcess), successful reached:
```

**Comment by michaelmosmann** [comment]
@F-Node-Karlsruhe is there a chance that you can start the downloaded binary on this instance? you can find the location in the log.. from the last log it is 

`/root/.embedmongo/fileSets/0795fd5091b94992525658a7f10f8d51c8af2f4588091c13d65abccd532b3c40/mongod`

**Comment by F-Node-Karlsruhe** [comment]
Maxbe related to this issue https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/467

**Comment by michaelmosmann** [comment]
@F-Node-Karlsruhe .. did you execute the binary inside the docker container? If your docker is a debian i am surprised that the os detection thinks thats an ubuntu.. 

can you show me the content of the os-release file of the docker container?

**Comment by F-Node-Karlsruhe** [comment]
The container is a maven 3.9 container which is based on ubuntu 24.04

when executing the binary there i get

`Illegal instruction (core dumped)`

**Comment by michaelmosmann** [comment]
@F-Node-Karlsruhe can you provide the output of  /proc/cpuinfo inside your docker container?

**Comment by F-Node-Karlsruhe** [comment]
We found the issue. Gitlab is running on a virtual machine and the virtual CPU was not supporting AVX while the host machine did. Changing the virtual CPU type from the default virtual one to the one on the host machine (EPYC) made it work :)

**Comment by michaelmosmann** [comment]
@F-Node-Karlsruhe ah.. ok.. interesting .. did not expect that. So everything is working right now?

**Comment by F-Node-Karlsruhe** [comment]
Like a charm :)

**Comment by michaelmosmann** [comment]
then i close this issue.. reopen if needed.
