### ISSUE TITLE
Could not download embedded mongo from custom download path cause URL mismatch

### ISSUE THREAD

**Issue by nandanibansal** [flapdoodle-oss/de.flapdoodle.embed.mongo#526]
We were using flapdoodle 2.2.0 before, we used to give the custom path like this -

```

MongodStarter starter = MongodStarter
        .getInstance(new RuntimeConfigBuilder()
          .defaults(Command.MongoD)
          .artifactStore(new ExtractedArtifactStoreBuilder()
            .defaults(Command.MongoD)
            .download(new DownloadConfigBuilder()
              .defaults()
              .packageResolver(new MongoDownloadPath(Command.MongoD))
              .downloadPath(downLoadPath)))
          .build());
      log.info("mongodb starter config = {}"
```

Now we need mongo 7.0.5 and ubuntu_22 support, so we migrated to flapdoodle 4.13.0, here we are not able to find hot to give particular download path.

```
MONGO = Mongod.instance()
              .withMongodArguments(
                      Start.to(MongodArguments.class)
                              .initializedWith(
                                      MongodArguments.defaults()
                                              .withUseNoPrealloc(false)
                                              .withUseSmallFiles(false)
                              ))
         .withNet(Start.to(Net.class).initializedWith(Net.builder().bindIp(bindIp).port(port).isIpv6(Network.localhostIsIPv6()).build()))
              .start(Versions.withFeatures(Version.of("7.0.5")));
```

we customized the mongod download url with this guide:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Customizations.md#customize-download-url

We are getting this error:
{We are giving url without username and password}
Caused by: java.lang.IllegalArgumentException: parts missing: 'https://mydomain/osx/mongodb-macos-arm64-7.0.5.tgz' != 'UrlParts{protocol='https', userInfo='null', host='artifacts.com', path='/artifactory/.../osx/mongodb-macos-arm64-7.0.5.tgz'}' 

It is adding this extra **/osx/mongodb-macos-arm64-7.0.5.tgz** in our path.

**Comment by michaelmosmann** [comment]
@nandanibansal there are two options: the one you chosed is the easiest one: you just changed the base path to the artifacts.. to make this work, the required artifacts must be stored in the same path as in the official mongodb artifact repository .. 

If this is not an option, you have to implement your own package resolver.. this is more complicated, here you can find some guidance for that: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Customizations.md#customize-package-resolver

**Comment by nandanibansal** [comment]
@michaelmosmann Thanks for the above reference. I tried using this, but getting this error

	"Caused by: java.lang.IllegalArgumentException: parts missing: 'https://{host}:{port}/...mongodb-macos-x86_64-7.0.5.RELEASE.tgz' != 'UrlParts{protocol='https', userInfo='null', host='{host}, path='...mongodb-macos-x86_64-7.0.5.RELEASE.tgz'}'",

I checked the code:
@VisibleForTesting
	static UrlParts partsOf(URL url) {
		boolean portIsPartOfTheUrl = url.getPort() != -1 && url.getPort() != url.getDefaultPort();

		return UrlParts.of(
			url.getProtocol(),
			url.getUserInfo(),
			url.getHost().isEmpty() ? null : url.getHost() + (portIsPartOfTheUrl ? ":" + url.getPort() : ""),
			pathPart(url));
	}
	
	
the value of portIsPartOfTheUrl is coming false because my port is same as default port.

**Comment by nandanibansal** [comment]
@michaelmosmann 
I am getting below error while running my test cases in Docker.

```
Caused by: java.lang.RuntimeException: could not start process
Caused by: java.io.IOException: Cannot run program "/root/.embedmongo/fileSets/a2e5309c8465ece8427865fc6a37e49cbfea639352752c9cab799b58c1d62904/mongod" (in directory "/tmp/temp--9ba1a91e-ab50-494f-8c4c-a64649c90cdd/workingDir4540246169661976121"): error=8, Exec format error
Caused by: java.io.IOException: error=8, Exec format error
```
Please help

**Comment by michaelmosmann** [comment]
@nandanibansal do you use the same binary for docker?

**Comment by michaelmosmann** [comment]
@nandanibansal Can you execute the binary `/mnt/looper/.embedmongo/fileSets/a2e5309c8465ece8427865fc6a37e49cbfea639352752c9cab799b58c1d62904/mongod` inside your docker container?

**Comment by nandanibansal** [comment]
@michaelmosmann 
I tried looking for the mongod binary inside the /mnt/looper/.embedmongo/fileSets/a2e5309c8465ece8427865fc6a37e49cbfea639352752c9cab799b58c1d62904

```
ARG mavenVersion=3-jdk-8-alpine
ARG zuluJDKVersion=8-jdk-alpine
ARG scannerVersion=0.0.26
ARG baseRepoBranch=main

##Stage 0 certs stage
FROM docker.ci.artifacts.com/wce-docker/ca-roots:latest as roots

##Stage 1 maven build
FROM docker.ci.artifacts.com/hub-docker-release-remote/maven:${mavenVersion} AS build
ARG kittBuildVersion=0.0.1-SNAPSHOT
ARG mvnGoals="clean install -Dtest="ClaimOverrideServiceIntegrationTest" -Dmaven.test.failure.ignore=true"
WORKDIR /app
RUN curl -SLk https://repository.com/content/repositories/thirdparty/settings.xml -o ${MAVEN_HOME}/conf/settings.xml
COPY . .

RUN mvn versions:set -DnewVersion=${kittBuildVersion}
RUN mvn -B -e -f /app/pom.xml ${mvnGoals} || true

RUN ls -l /root/.embedmongo/fileSets
RUN ls -l /root/.embedmongo/fileSets/a2e5309c8465ece8427865fc6a37e49cbfea639352752c9cab799b58c1d62904 
```

There is no file that exists inside this folder.

**Comment by michaelmosmann** [comment]
@nandanibansal I think you must login into the running docker container and then search for this file.. but as I saw some details I guess this will not work if you use alpine based images .. because there is no mongodb version for alpine.. you have to use at least some more common.. like Ubuntu, Debian, redhat... or the same like your production environment.

**Comment by nandanibansal** [comment]
@michaelmosmann Thank, it is working now.
