### ISSUE TITLE
de.flapdoodle.embed.mongo:4.14.0 stopped working starting from with Spring Boot Starter Parent:3.3.0

### ISSUE THREAD

**Issue by dimylik** [flapdoodle-oss/de.flapdoodle.embed.mongo#527]
Interesting, latest de.flapdoodle.embed.mongo:4.14.0 stopped working starting from with Spring Boot Starter Parent:3.3.0

https://mvnrepository.com/artifact/de.flapdoodle.embed/de.flapdoodle.embed.mongo/4.14.0 
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent/3.3.0

It was working with all previous combinations of **embed.mongo** and **Spring boot** parent including version **spring-boot-starter-parent:3.2.7**.

Not sure what is the error: IllegalState APplicationContext failure threshold (1) exceeded: skipping repeated attempt to load context for WebMergedComtextConfiguration.

We do have @SpringBootTest as suggested in here https://stackoverflow.com/questions/65903358/test-failure-java-lang-illegalstateexception-failed-to-load-applicationcontex

Failing on MacOS, Java 21.0.1

**Comment by michaelmosmann** [comment]
@dimylik hmm.. so spring changed stuff.. i guess i have to extend https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary with spring 3.3.x to see whats changed.

**Comment by michaelmosmann** [comment]
@dimylik i did an update of https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary and it worked without any issue with spring 3.3.1 ..

**Comment by michaelmosmann** [comment]
I will close this issue .. reopen if needed.
