### ISSUE TITLE
The correct configuration for "de.flapdoodle.mongodb.embedded.version"

### ISSUE THREAD

**Issue by willgss** [flapdoodle-oss/de.flapdoodle.embed.mongo#529]
I am using the following version of "de.flapdoodle.embed.mongo"
 <dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo</artifactId>
            <version>4.12.0</version>
            <scope>test</scope>
 </dependency>

I'd like to know the correct "de.flapdoodle.mongodb.embedded.version" configuration for the version "4.12.0" and where can i find this configuration for other version component, for example "4.15.0".
Thank you!

**Comment by michaelmosmann** [comment]
@willgss what other components? Do you use spring?

**Comment by willgss** [comment]
@michaelmosmann 
Actually this question is trying to fix the issue in [530](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/530)， so i will close it and continue the discussion in 530.
Thank you!

**Comment by willgss** [comment]
@michaelmosmann
Actually this question is trying to fix the issue in [530](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/530)， so i will close it and continue the discussion in 530.
Thank you!
