### ISSUE TITLE
Unusefull because maven-mongodb-plugin have download link for MongoDB incorrect. It go in broken link MongoDB signin page not in community version ! Please ask to Syncleus to FIX LINK TO DOWNLOAD MONGODB !

### ISSUE THREAD

**Issue by skyblackhawk** [flapdoodle-oss/de.flapdoodle.embed.mongo#531]
Hi to all,
   I lost all night on your code and on maven-mongodb-plugin to discovered that the problem is on maven-mongodb-plugin and there are opened issues on follow links that ask to fix path to download MongoDB v7.0.0 LTS and other versions. I added what happened and why download go in error because MongoDB changed links to download application.

Actual MongoDB download link called by maven-mongodb-plugin is **old** and **return access denied because that link ask to sign in to download non community versions**.

In below issues in maven-mongodb-plugin github there are correct link to download community versions by maven-mongodb-plugin to fix the error:

- **https://github.com/Syncleus/maven-mongodb-plugin/issues/5 and**
- **https://github.com/Syncleus/maven-mongodb-plugin/issues/7**

**Could you press maven-mongodb-plugin team to fix these URLs ?
Must be simple,they will be in application.properties file in Java or in remote resources where recover these download links !**

In our projects we can't try maven integration tests with MongoDB v7.0.0 LTS version in memory, so we need to mock service by code !
A lot of work added.

In our apps we are using your dependency and configure MongoDB in java heap memory by maven-mongodb-plugin for maven integration tests with MongoDB in memory before to build and deploy in CI/CD on cloud because maven in CI/CD can't access to internet it can access only for save docker image and deploy:

- **SpringBoot v3.2.0 with WebFlux**
-  **JDK 21.0.2**
- **MongoDB v7.0.0 LTS in reactive mode**

Thanks a lot for your available, help us !

**Comment by skyblackhawk** [comment]
Please specify in wiki page to add this plugin so in alternative not arrive the execution to download MongoDB from MongoDB server.
I arrived to download MongoDB after inserted:
			
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.3.1</version>
				<configuration>
					<argLine>
						--add-exports org.junit.platform.commons/org.junit.platform.commons.util=ALL-UNNAMED
						--add-exports org.junit.platform.commons/org.junit.platform.commons.logging=ALL-UNNAMED
						--illegal-access=warn
					</argLine>
				</configuration>
			</plugin>

After dependency try to download file using maven-mongodb-plugin but URL to download is incorrect as write in first comment of this issue.

Could you fix UNAMED too to avoid to add surefire configuration ?

Thanks a lot for your available.

**Comment by michaelmosmann** [comment]
@skyblackhawk .. ok, hmm.. step by step..

- maven-mongodb-plugin --> the last commit in this project was 7 years ago.. you should not use this plugin..
- Could you press maven-mongodb-plugin team to fix these URLs ? --> i guess not
- ... using your dependency and configure MongoDB in java heap memory .. --> this projects starts a real mongodb server which is NOT working on java heap memory.. its a platform specific binary that is started as a process..
- CI/CD can't access to internet it can access only for save docker image and deploy --> you can host these artifacts by yourself (see https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Customizations.md#customize-download-url and if you are using the spring integration: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/main/HowTo.md#customize-mongod)
- Could you fix UNAMED - i guess you are using modules in test run which i would not recommend if not necessary .. to make this work i guess i have to change some stuff.. so its not an easy fix.
