### ISSUE TITLE
UncategorizedMongoDbException: Command failed with error 73 (InvalidNamespace)

### ISSUE THREAD

**Issue by patriciayogi** [flapdoodle-oss/de.flapdoodle.embed.mongo#532]
We upgraded de.flapdoodle.embed to 4.13.1 and the mongo client doesn't work with Mongo V5 or V6. On MAC it works on Mongo V7 version, but our prod environment is on V6. 

Ubuntu 18.04
Embed Mongo version to V6_0_15.

Errror:
```
oorg.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 73 (InvalidNamespace): 'Can't create user databases on a --configsvr instance test.tenants' on server localhost:25629. The full response is {"ok": 0.0, "errmsg": "Can't create user databases on a --configsvr instance test.tenants", "code": 73, "codeName": "InvalidNamespace", "lastCommittedOpTime": {"$timestamp": {"t": 1722415486, "i": 1}}, "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1722415486, "i": 1}}, "signature": {"hash": {"$binary": {"base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "subType": "00"}}, "keyId": 0}}, "operationTime": {"$timestamp": {"t": 1722415486, "i": 1}}}

	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:135)
	at 
```

**Comment by michaelmosmann** [comment]
@patriciayogi what was the last working version you used?

**Comment by patriciayogi** [comment]
We upgraded de.flapdoodle.embed from 3.4.7 to 4.13.1

**Comment by michaelmosmann** [comment]
@patriciayogi i was on vacation.. 

do you have any special configuration?

**Comment by michaelmosmann** [comment]
@patriciayogi you can close https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/issues/58 as we can this problem in this issue..

**Comment by michaelmosmann** [comment]
@patriciayogi can you check if it works on your system at all? You can just build this project https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary .. it contains a minimal setup for each spring version.
