### ISSUE TITLE
Unable to query multiple documents while testing. 

### ISSUE THREAD

**Issue by SOCRATESZZ** [flapdoodle-oss/de.flapdoodle.embed.mongo#533]
Whenever I am trying to retrieve two documents. It is throwing connection time out error.
The code works correctly when I try to retrieve 1 document. But when I try to query multiple documents. It throws connection time out error
I am using Morphia. 
```
function to return datastore
mongodb = Mongod.instance().start(Version.V7_0_12);
    ServerAddress serverAddress = mongodb.current().getServerAddress();
    MongoClient mongoClient = MongoClients.create("mongodb://" + serverAddress);
    datastore = Morphia.createDatastore(mongoClient, MorphiaConfig.load());
```

`datastore.find(mongoModelType).filter(Filters.eq("id", user.getId()))`

**Comment by michaelmosmann** [comment]
@SOCRATESZZ do you have any stack trace?

**Comment by michaelmosmann** [comment]
@SOCRATESZZ i close this issue.. reopen if needed..
