### ISSUE TITLE
Allow distributionBaseUrl to be set using a system property

### ISSUE THREAD

**Issue by mmorrisontx** [flapdoodle-oss/de.flapdoodle.embed.mongo#540]
In large build systems, it would be useful for distributionBaseUrl to be overridable using a java system property or environment variable, so that the binary download can be redirected to a caching mirror without needing to touch the source of every involved project.

**Comment by michaelmosmann** [comment]
@mmorrisontx so just change the base url to an mirror, right?

**Comment by mmorrisontx** [comment]
Yep! Basically just a way to do this from the environment without needing a code change:

```
@Override
public Transition<DistributionBaseUrl> distributionBaseUrl() {
    return Start.to(DistributionBaseUrl.class)
    .initializedWith(DistributionBaseUrl.of("http://my.custom.download.domain"));
}
```

**Comment by michaelmosmann** [comment]
@mmorrisontx now you can set `de.flapdoodle.embed.mongo.baseUrl` system property to override this..

**Comment by antdolg1** [comment]
@michaelmosmann will this work also for spring3x?
