### ISSUE TITLE
Query with pattern + options doesn't take options into account

### ISSUE THREAD

**Issue by Cimballi** [flapdoodle-oss/de.flapdoodle.embed.mongo#543]
It looks like the following query doesn't take the options "i" into account = case sensitive
`{ "xxx_field_name_xxx": /^true$/i }`

But the following query does take the options "i" into account = case insensitive
`{ "xxx_field_name_xxx": { $regex: /^true$/, $options: "i" } }`

Both works when directly executed on MongoDB.

**Comment by michaelmosmann** [comment]
@Cimballi which mongodb version do you use in your tests? (this tool does run a real mongodb, so i guess it's an mongodb version issue).

**Comment by Cimballi** [comment]
It seems to be a Spring Data Mongo bug, thanks !

**Comment by michaelmosmann** [comment]
@Cimballi wish you luck:)
