### ISSUE TITLE
TokuMX support

### ISSUE THREAD

**Issue by kdkeck** [flapdoodle-oss/de.flapdoodle.embed.mongo#84]
I'd like to be able to use embedmongo to test against TokuMX distros:

https://github.com/Tokutek/mongo

For most applications TokuMX should be a drop-in replacement for vanilla MongoDB, but it would be really handy to be able to test that the same way you would test against multiple versions and platforms.

**Comment by matlockx** [comment]
@kdkeck quite a while but are you still interested in this? if so I would suggest to provide a pr since we do not have the resources currently to provide that change. otherwise i would close this issue for now.. sorry

**Comment by benmccann** [comment]
We can close this issue. I work with @kdkeck and we no longer use TokuMX

**Comment by csarrazi** [comment]
TokuMX is EOL, so there's no point in supporting it.

**Comment by Loki-Afro** [comment]
@csarrazi thanks for letting me know ;)
