### ISSUE TITLE
Question; Database server extraction cache?

### ISSUE THREAD

**Issue by Fristi** [flapdoodle-oss/de.flapdoodle.embed.mongo#90]
Hi,

Loving your embedded mongo server, great work. Is it possible to only 'cache' the extraction of the db server itself?

Each time I start a test I happen to see this hanging a few seconds;

`Extract /Users/mark/.embedmongo/osx/mongodb-osx-x86_64-2.6.0.tgz START`

Would be nice if that could be cached somehow

**Comment by Loki-Afro** [comment]
This is already implemented, closing
