### ISSUE TITLE
please allow to inject IRuntimeConfig in MongodForTestsFactory

### ISSUE THREAD

**Issue by n0mer** [flapdoodle-oss/de.flapdoodle.embed.mongo#98]
Hello,
thanks for great product - it helps a lot. Please review the following suggestion.

When using windows, code in constructor

``` java
        final MongodStarter runtime = MongodStarter.getInstance(new RuntimeConfigBuilder()
                .defaultsWithLogger(Command.MongoD, logger)
                .build());
```

does not allow you to change `IRuntimeConfig` that is passed to `MongodStarter#getInstance(IRuntimeConfig cfg)` method to use `UserTempNaming` like this:

``` java
IRuntimeConfig runtimeConfig = new RuntimeConfigBuilder()
            .defaults(Command.MongoD)
            .artifactStore(new ArtifactStoreBuilder()
                    .defaults(Command.MongoD)
                    .executableNaming(new UserTempNaming())
            )
            .build()
```

Tricky part here is that you should still somehow conform to this:

> store Starter or RuntimeConfig in a static final field if you want to use artifact store caching (or else disable caching)

Moreover, it is impossible to subsclass `MongodForTestsFactory` (to override your constructor) because fields `mongodExecutable` and `mongodProcess`are private, not protected.

So please do the same to IRuntimeConfig as you're already very well doing with `IMongodConfig` here

``` java
    protected IMongodConfig newMongodConfig(final IFeatureAwareVersion version) throws UnknownHostException, IOException {
        return new MongodConfigBuilder().version(version).build();
    }
```

**Comment by Loki-Afro** [comment]
@n0mer can I close this issue or is there anything left to do? ;)

**Comment by n0mer** [comment]
@Loki-Afro if now it's possible to inject - then go ahead :)
