### ISSUE TITLE
Add ability to create instance of MongodConfigBuilder without any exceptions.

### ISSUE THREAD

**Issue by baev** [flapdoodle-oss/de.flapdoodle.embed.mongo#99]
I tried to create MongodConfigBuilder:

``` java
MongodConfigBuilder builder = new MongodConfigBuilder()
                        .version(Version.Main.PRODUCTION)
                        .cmdOptions(cmdOptions)
                        .net(new Net(host, port, Network.localhostIsIPv6()));
```

but it throws UnknownHostException at the following line (AbstractMongoConfigBuilder):

``` java
net().setDefault(new Net());
```

Seems like this default will be overwritten

PS. The error occurs at `Network.getFreeServerPort()` at `new Net()`.

**Comment by Loki-Afro** [comment]
@nscavell I know today is 2018 but ... 

wouldn't be the only way to call `Network.getFreeServerPort()` and `Network.localhostIsIPv6()`lazy to resolve this issue or am Im not getting this issue?

**Comment by geoffmina** [comment]
There should be no default value for Net() created at construction time.  If no values are set by the time build() is called, it would then be appropriate for the default Net() to be built - as it would give people time to set their own host to avoid the UnknownHostException issue.

**Comment by michaelmosmann** [comment]
reopen if this still is an issue...
